### ISSUE TITLE
react应用导入富文本插件报错有人知道怎么解决吗

### ISSUE THREAD

**Issue by louzhonghua** [wanglin2/mind-map#1003]
ERROR in ./node_modules/quill/core/editor.js 1:0-37
Module not found: Error: Can't resolve 'lodash-es/merge' in '/Users/didi/Desktop/前端代码/qa-case/node_modules/quill/core'
Did you mean 'merge.js'?
BREAKING CHANGE: The request 'lodash-es/merge' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.

**Comment by wanglin2** [comment]
看来没人知道，建议通过搜索引擎或gpt的方式来解决
