### ISSUE TITLE
初始化及使用"SET_NODE_TEXT"时有问题

### ISSUE THREAD

**Issue by 30940417** [wanglin2/mind-map#1006]
从外网导入内网，mindmap初始化时，报错 this.mindmap.event.listenerCount is not a function ，在使用this.mindmap. execCommand('SET_NODE_TEXT')时，会有同样的 error；
使用场景：点击node，打开dialog，dialog中有input，输入内容后，blur调用this.mindmap. execCommand('SET_NODE_TEXT', node, inputValue) 报错 this.mindmap.event.listenerCount is not a function

**Comment by wanglin2** [comment]
不知道怎么复现。

listenerCount方法是库引用的https://www.npmjs.com/package/eventemitter3包的方法，可以检查一下你安装的这个包的版本的有没有这个方法
