### ISSUE TITLE
两个思维之间不能互相复制粘贴

### ISSUE THREAD

**Issue by YanLeSi** [wanglin2/mind-map#1010]
http环境下 同一个思维导图可以复制粘贴，但是两个思维导图就不能复制粘贴。如果是http环境引起的。为什么同一个思维导图可以成功。

**Comment by wanglin2** [comment]
在单个思维导图页面内复制和粘贴仅需要拦截Ctrl+c或Ctrl+v按键即可，复制和粘贴的数据可以简单的通过一个变量来保存，而其他情况需要读写用户剪贴板的数据，需要使用[clipboard](https://developer.mozilla.org/zh-CN/docs/Web/API/Navigator/clipboard)API，该特性仅在https协议下可用。
