### ISSUE TITLE
图片缩放问题

### ISSUE THREAD

**Issue by qgyd** [wanglin2/mind-map#1011]
如果是一个独立页面,例如路由页面,图片缩放是正常的,
![微信图片_20241119164708](https://github.com/user-attachments/assets/382d5f0a-66de-45c2-b18a-9dda51f8fdfc)
但是如果在其他页面通过 遮罩层去渲染组件,就会导致图片退拽缩放失效
正常的图片是这样的
![Uploading 微信图片_20241119164847.png…]()

**Comment by qgyd** [comment]
![微信图片_20241119164847](https://github.com/user-attachments/assets/56b6223b-f9f5-4edf-948b-64c47540f0ac)
这个是正常的

**Comment by wanglin2** [comment]
失效是什么意思，按钮没显示出来？
