### ISSUE TITLE
【咨询】请问作者后续特性考虑增加节点（批量）创建的动画效果么？

### ISSUE THREAD

**Issue by dqx-eterning** [wanglin2/mind-map#1014]
问作者后续特性考虑增加节点（批量）创建的动画效果么？
类似
此项目的效果
https://github.com/PastKing/MarkMap-OpenAi-ChatGpt/blob/master/doc/PastKing_2024-06-05_13-14-09.gif

**Comment by wanglin2** [comment]
不会考虑动画效果，一耗性能，二会带来一些bug
