### ISSUE TITLE
bug反馈：切换主题后，可以执行撤销，但变的是某些节点的字体样式(颜色)

### ISSUE THREAD

**Issue by ZhangMingZhao1** [wanglin2/mind-map#1015]
https://wanglin2.github.io/mind-map/#/

在线demo就可以复现

**Comment by ZhangMingZhao1** [comment]
![image](https://github.com/user-attachments/assets/b2773260-4129-416b-8828-37ea9dbfa1e3)

原因是切换主题会触发每个节点的set_node_data，给history 加了一条记录，但是主题的其他配置信息没有加进去，导致撤销，只会撤销掉这个节点的set之前的样式，整体就很怪。

**Comment by wanglin2** [comment]
已修改，切换主题后不会添加历史记录，v0.13.0+生效
