### ISSUE TITLE
bug反馈：初始化脑图时，如果是是以readonly option传入，history数组不会初始化

### ISSUE THREAD

**Issue by ZhangMingZhao1** [wanglin2/mind-map#1016]
![image](https://github.com/user-attachments/assets/5f94f296-c380-45c3-832c-07b8e2d1434f)

![image](https://github.com/user-attachments/assets/83ff4ca4-efea-4cad-bba5-f8650321d161)

这可能会导致用户扩展history时出现一些奇怪的问题，建议解决办法是进入edit时调用下addHistory

**Comment by wanglin2** [comment]
已修改，v0.12.2+生效。
