### ISSUE TITLE
自定义组件切换主题后，节点自定义数据被覆盖了

### ISSUE THREAD

**Issue by xinnai** [wanglin2/mind-map#1018]
您好，有个问题还挺重要的，我自定义了几个节点，是vue3组件，代码如下：
`import SkillNode from "@/components/nodeTemplate/SkillNode.vue"
import CiyuanNode from "@/components/nodeTemplate/CiyuanNode.vue"
import DateNode from "@/components/nodeTemplate/DateNode.vue"
isUseCustomNodeContent: true,
      customCreateNodeContent: (node) => {
        const nodedata = node.nodeData.data;
        if (nodedata.category == 'Slider') {
          。。。
        } else if (nodedata.category == 'Ciyuan') {
         。。。
        } else if (nodedata.category == 'Date') {
          const el = document.createElement('div')
          const app = createApp(DateNode, {// props **这里根据category字段判断加载哪一个vue组件**
            ndata: node.nodeData.data,
            mask: false
          })
          app.mount(el)
          return el
        }

      },`
默认default主题的时候，组件加载正常，比如Date组件，如下
![Snip20241122_3](https://github.com/user-attachments/assets/832dc6e5-7909-4214-8cd7-f0854f98ee7a)
但是当我切换了主题，组件按照普通文字组件加载了，没有使用我的vue组件，效果如下
![Snip20241122_1](https://github.com/user-attachments/assets/0b2f5564-05a6-48a1-b4c4-d93fcb37d235)
我查看了一下数据变化，发现节点数据被修改了，category和其他自定义属性都没有了，可能是这个原因导致的节点没有加载自定义组件
![Snip20241122_2](https://github.com/user-attachments/assets/79fc4df5-3f7d-4c71-ae84-6f852317a99d)
我的版本是**"simple-mind-map": "^0.12.1", "simple-mind-map-plugin-themes": "^1.0.0",**
修改主题的代码如下：
`window.simpleMindMap.setTheme(mindmapStore.gTheme.value); //修改后主题的名字如：classic15
  window.simpleMindMap.setThemeConfig(mindmapStore.gTheme.theme);//修改后主题的theme对象` 
我的期望是数据不被覆盖，切换主题之后可以正常加载自定义组件

**Comment by xinnai** [comment]
经过排查我发现是`  mindmap.execCommand("REMOVE_ALL_NODE_CUSTOM_STYLES");`这句代码造成的，为了解决[#988](https://github.com/wanglin2/mind-map/issues/988)这个问题加了这行代码。
请问怎么能在调用`REMOVE_ALL_NODE_CUSTOM_STYLES`的时候，不覆盖自定义数据中含义category='Date'的节点，有快速排除节点的方法吗？
虽然文档写了`appointNodes`可以传想要覆盖的节点，但是如何得到自定义节点以外的所有节点？

**Comment by wanglin2** [comment]
![image](https://github.com/user-attachments/assets/b3f4de22-e257-4720-a2b7-16a5e3231547)

**Comment by xinnai** [comment]
感谢快速回复
