### ISSUE TITLE
现在layout为logicalStructure时默认是顶级节点居中，这样会导致整体偏右，是否可以加个参数让整个导图居中

### ISSUE THREAD

**Issue by White-Give** [wanglin2/mind-map#1021]

**Comment by wanglin2** [comment]
可以试试initRootNodePosition或fit实例化选项。

**Comment by White-Give** [comment]
> 可以试试initRootNodePosition或fit实例化选项。

![WeChat1dcdcabb1e20cecf3221e3dc7caa156d](https://github.com/user-attachments/assets/37a95afb-d1ac-4967-9ca0-f69691eaa26e)
我明白大佬的意思，我的意思是如果节点很深，这样的话initRootNodePosition就会很难去计算偏移度，我的想法是否可以加个选项来决定顶级节点居中还是整体居中等

**Comment by wanglin2** [comment]
目前只有这个两个选项，和view.fit方法，其他没啥办法。

**Comment by White-Give** [comment]
好的，了解
