### ISSUE TITLE
关于Ctrl+C和Ctrl+V快捷键的问题

### ISSUE THREAD

**Issue by szx654038096** [wanglin2/mind-map#1022]
大佬您好，我想请问一下Ctrl+C和Ctrl+V快捷键在项目本地启动的时候能正常使用，但是打包发布到测试环境和正式环境后就没反应了，但是Ctrl+X快捷能用，控制台既没有输出也没有报错，请问一下是否跟版本相关？

**Comment by wanglin2** [comment]
localhost和https协议下可用。

**Comment by szx654038096** [comment]
谢谢大佬回答，再请教下，是否可以在http协议下使用呢？
