### ISSUE TITLE
自定义节点滑动条和节点拖拽事件冲突问题

### ISSUE THREAD

**Issue by xinnai** [wanglin2/mind-map#1023]
您好，我自定义了一个节点使用了vue3，el-slider组件，当拖动slider的时候，节点也被拖走了，有什么好办法可以阻止节点的拖动吗？或者有指定按住某个元素才拖动节点的方法吗？
![Snip20241127_1](https://github.com/user-attachments/assets/9a1a7be5-436c-4154-9d60-8c747fd50cb9)

`isUseCustomNodeContent: true,
      customCreateNodeContent: (node) => {
        const nodedata = node.nodeData.data;
        if (nodedata._category == 'Slider') {
          const el = document.createElement('div')
          const app = createApp(自定义节点, {// props
            ndata: node.nodeData.data,
          })
          app.mount(el)
          return el
        }`

**Comment by wanglin2** [comment]
阻止一下元素鼠标相关事件的冒泡。
