### ISSUE TITLE
是否有节点输入框回车事件的监听

### ISSUE THREAD

**Issue by xinnai** [wanglin2/mind-map#1024]
您好，想监测到节点文字输入框回车事件，为了拿到最终修改的文本，我原本监听了`hide_text_edit`事件，发现修改文字大小、字体、文字颜色等都会触发这个事件。有没有单独的文本变化的事件？不是输入过程中，而是最终回车确定后的那个事件。
`mindMap.on('hide_text_edit', (textEditNode, activeNodeList, node) => {
      console.log("修改节点中的文字"); //修改文字大小、字体、文字颜色都会触发
    })`

**Comment by wanglin2** [comment]
v0.12.2+版本后修改文字大小等不会触发hide_text_edit事件。
