### ISSUE TITLE
shift + 回车换行时，光标已经换行，但节点高度没有变化：问题原因是getEditText()函数

### ISSUE THREAD

**Issue by xiaobu474** [wanglin2/mind-map#1026]
### 问题描述
shift + 回车换行时，光标已经换行，但节点高度没有变化，如图所示
![image](https://github.com/user-attachments/assets/ca727a17-3aba-499e-8de2-899b512da19f)
### 问题原因
- `simple-mind-map\src\plugins\RichText.js`文件的`getEditText()`函数会将编辑框内的`/<p><br><\/p>$/`替换为空，故shift + 回车换行后，这个函数会把最后的换行替换为空
- 我把node_text_edit_change事件的text内容换一下，shift + 回车换行成功保留了
![image](https://github.com/user-attachments/assets/3e5375bd-ba37-4a15-83b4-cff78d9604e6)
- `getEditText()`函数为什么要把`/<p><br><\/p>$/`替换为空呢？我测试了下好像进行上图替换后不会带来问题

**Comment by wanglin2** [comment]
已删除该逻辑，v0.12.2+生效。
