### ISSUE TITLE
如何在插入节点成功后，不激活节点

### ISSUE THREAD

**Issue by xinnai** [wanglin2/mind-map#1027]
作者大大，我现在使用`mindMap.execCommand('INSERT_CHILD_NODE', false, [node])`，在非激活节点下插入节点，虽然成功插入，但成功之后，自动选中新节点了，如何才能不激活，保留原来选择的节点呢？

**Comment by wanglin2** [comment]
this.mindMap.updateConfig({
          createNewNodeBehavior: 'notActive'
        })
        this.mindMap.execCommand('INSERT_CHILD_NODE', false, [node])
        const onRenderEnd = () => {
          this.mindMap.off('node_tree_render_end', onRenderEnd)
          this.mindMap.updateConfig({
            createNewNodeBehavior: 'default'
          })
        }
        this.mindMap.on('node_tree_render_end', onRenderEnd)
