### ISSUE TITLE
自定义节点导出图片样式错乱

### ISSUE THREAD

**Issue by xinnai** [wanglin2/mind-map#1028]
您好，我使用vue3自定义的组件，导出样式是错乱的，请看代码
`const mindMap = window.$simpleMindMap;
  mindMap.doExport.png().then((exportData) => {
    const blob = dataURLtoBlob(exportData);
    myCallback(blob);
  });`
![Snip20241202_3](https://github.com/user-attachments/assets/edaba6d3-2cd1-4846-ab0c-4dcc6b63bafa)
![3003](https://github.com/user-attachments/assets/3a57627a-b47f-46c6-ac89-fc16a7616d80)

**Comment by wanglin2** [comment]
需要使用mindMap.appendCss方法传入自定义内容的样式。
