### ISSUE TITLE
富文本修改文字相关属性报错

### ISSUE THREAD

**Issue by xinnai** [wanglin2/mind-map#1029]
作者大大，有两个问题我觉得跟套在iframe里有关，现在页面在iframe里才有这个问题。
1、虽然选中了节点，但是直接按tab不能加节点，被浏览器的tab事件拦截了，请问有没有画布聚焦的方法？
2、富文本模式下，只要双击文字进入编辑状态就报这个错：
![Snip20241202_6](https://github.com/user-attachments/assets/9d766853-e697-47f9-83c9-6df61978ffa1)

设置文字大小，字体等也会抛出同样的错误，版本0.12.1
代码：`node.setStyles({fontSize: 20});`
![Snip20241202_5](https://github.com/user-attachments/assets/52e13c8b-2538-46e1-9900-4631f9516e0f)
![Snip20241202_4](https://github.com/user-attachments/assets/5fd82899-3c4b-47cb-8501-a1265b8d8088)

**Comment by wanglin2** [comment]
问题无法复现。
