### ISSUE TITLE
[需求] 希望添加节点固定宽度配置

### ISSUE THREAD

**Issue by zhnoah** [wanglin2/mind-map#1031]
在思维导图等模式下，固定节点（二级及以下）宽度（内容自动换行）将使得节点上下对齐，提升美观度。

**Comment by wanglin2** [comment]
富文本模式下，可以给节点数据带上customTextWidth字段指定宽度，比如：{  data: { text: 'xxx',  customTextWidth: 200 } }，非富文本模式下暂不支持。
