### ISSUE TITLE
bug: keyMap.js文件中 “/”的code错误

### ISSUE THREAD

**Issue by BeanWhite** [wanglin2/mind-map#1039]
"/"的code应该是111，该错误导致快捷键“/”失效

**Comment by BeanWhite** [comment]
能否将数字键盘这边的“/”也加入进去

**Comment by wanglin2** [comment]
新增了一个扩展键值对的方法，v0.12.2+版本生效。到时可以参考下面代码自行扩展：
this.mindMap.keyCommand.extendKeyMap('/2', 111)
      this.mindMap.keyCommand.addShortcut(
        '/2',
        this.mindMap.renderer.toggleActiveExpand
      )
