### ISSUE TITLE
setData没有生效

### ISSUE THREAD

**Issue by rainsubtime** [wanglin2/mind-map#1040]
使用nextjs，先初始化了MindMap
```
    useEffect(() => {
        mindMapRef.current = new MindMap({
            el: document.getElementById('mindMapContainer'),
            data: {
                "data": {
                    "text": "根节点"
                },
                "children": []
            }
        });
    }, [])
```
然后设置了更新，并且检查了节点数据
```
    useEffect(() => {
        if (mindMapRef.current && jsonInfo) {
            debugger
            mindMapRef.current.setData({ data: { text: "test1" } });
            let temp = mindMapRef.current.getData()
            console.log("检查数据", temp)
            // });
        } else {
            console.log("mindMapRef.current is null");
        }
    }, [jsonInfo])
```
发现检查数据里面数据其实改变了，但是页面并没有重新被渲染。
是我用法错了吗

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the Edit.vue component to properly handle data changes and trigger a re-render of the mind map. Added a new method to update the mind map data and render, and modified the setData method to use this new method.

You can review changes in this commit: https://github.com/mnmnk43434/wanglin2-mind-map-1040/commit/ecb7816d4ffbd02085aef9661416cf8dbd2e089d.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by rainsubtime** [comment]
我用的是不依赖框架的版本，也就是simple-mind-map，并且用的是react

**Comment by rainsubtime** [comment]
sry，my bad coding  qaq
