### ISSUE TITLE
只读模式下，连续输入不同文字搜索，上一个搜索到的高亮节点没有清除

### ISSUE THREAD

**Issue by LeP-Ton** [wanglin2/mind-map#1047]
![WechatIMG2953](https://github.com/user-attachments/assets/87e87e5f-7713-4f6e-bb60-fd225b304f5e)
如图，这里第一次搜索分支主题，然后立即又搜索二级节点，分支主题高亮没有清除

**Comment by wanglin2** [comment]
已修复，v0.13.0+生效。
