### ISSUE TITLE
非富文本模式下，粘贴带小于号和字母的文本会失败，比如“<A”

### ISSUE THREAD

**Issue by LeP-Ton** [wanglin2/mind-map#1048]
非富文本模式中，
1.粘贴“<A”文本到节点中，显示空白；
2.粘贴“<A”生成节点，显示“&amp;lt;A”
![image](https://github.com/user-attachments/assets/f8de24c2-5ba3-4fb0-8616-b9fbfbf0f81d)

**Comment by wanglin2** [comment]
已修改，v0.13.0+生效。
