### ISSUE TITLE
当多选节点编辑节点时双击其他节点会将双击的节点内容变空白

### ISSUE THREAD

**Issue by Testing-Superman** [wanglin2/mind-map#1056]
当openRealtimeRenderOnNodeTextEdit为true，多选节点编辑节点时双击其他节点会将双击的节点内容变空白。如果设置成false，它会直接把当前编辑节点的内容添加到被双击的节点
![lz_2024-12-20_16-56-19](https://github.com/user-attachments/assets/ea3a0b87-6d8c-44c5-baca-fc7753130106)

**Comment by wanglin2** [comment]
已修复，v0.13.0+生效
