### ISSUE TITLE
连续复制两次,会导致思维导图混乱

### ISSUE THREAD

**Issue by huang-yf3160** [wanglin2/mind-map#1063]
1.选择一个有多个子节点的复制
2.随便选择一个节点,连续粘贴两次,页面混乱

看现象是复制后,自动选中多个节点,再次复制导致节点位置计算错误

https://wanglin2.github.io/mind-map/#/ 在线事例即可复现

**Comment by wanglin2** [comment]
已修复，v0.13.0+生效
