### ISSUE TITLE
富文本编辑状态下无法失焦问题，官网可以复现

### ISSUE THREAD

**Issue by xinnai** [wanglin2/mind-map#1069]
1、富文本模式输入很多行文字
![Snip20241227_1](https://github.com/user-attachments/assets/869956d2-efed-4371-9ac1-886ec7aa9071)

2、删除一部分行数，节点高度减少
3、此时点击原先有文字的区域，无法失去焦点，节点编辑区域还是原来的大小。
![Snip20241227_2](https://github.com/user-attachments/assets/bdfc2914-21d6-4b7d-9766-3a740976d81e)

**Comment by wanglin2** [comment]
已修复，v0.13.0+生效
