### ISSUE TITLE
bug：折叠所有节点导出瞬间展开所有节点，导出图片的显示问题【十万火急，大佬救命】

### ISSUE THREAD

**Issue by sssxxx** [wanglin2/mind-map#1070]
vue3项目默认全部节点全部折叠，在导出的时候需为了看到所有的节点需要手动调用指令全部展开 然后再执行导出操作，但是导出的图片节点后面有的位置展示出来了节点的数量标识，手动展开节点再导出 就不会有这种现象； 这里设置了定时 但是还没生效，效果和代码如下：求解决方案。
![微信图片_20241228112151](https://github.com/user-attachments/assets/422ceb7e-f18c-4e20-b7c5-b9dafbb2f018)
![Snipaste_2024-12-28_11-23-27](https://github.com/user-attachments/assets/1517fc65-f282-4d80-a5eb-dcab07639f9c)

**Comment by wanglin2** [comment]
渲染是异步的，可以监听一下渲染结束事件再导出，类似这样：
this.mindMap.on('node_tree_render_end', async () => {
          this.mindMap.export(...args)
        })
        this.mindMap.execCommand('EXPAND_ALL')
