### ISSUE TITLE
远期优化：小地图内的示意图改成使用canvas绘制

### ISSUE THREAD

**Issue by wanglin2** [wanglin2/mind-map#112]
目前是clone节点，所以节点数量非常多会存在性能问题

**Comment by wanglin2** [comment]
或者通过导出为图片的方式

**Comment by tetap** [comment]
其实没必要这么麻烦，可以使用svg use标签进行引入。

**Comment by wanglin2** [comment]
> 其实没必要这么麻烦，可以使用svg use标签进行引入。

感谢提醒，我去了解一下这个标签

**Comment by wanglin2** [comment]
目前做法：小地图克隆的svg中，把节点的内容删除
