### ISSUE TITLE
要是有个概括就更完美了

### ISSUE THREAD

**Issue by liwuming** [wanglin2/mind-map#12]
就是同一级的连续多个兄弟节点，可以有个大括号

**Comment by wanglin2** [comment]
不是很明白，可以画个图示意一下~

**Comment by liwuming** [comment]
类似这样的，这是在xmind中的一个截图
![image](https://user-images.githubusercontent.com/49707505/181381082-34d95848-f5e1-463a-bcc4-3c4daa9ac3aa.png)

**Comment by wanglin2** [comment]
新增了概括功能，不过不是很完善，建议概括内容不要太多
