### ISSUE TITLE
getSvgData 实例方法默认需要传递两个参数

### ISSUE THREAD

**Issue by web-mzz** [wanglin2/mind-map#128]
![image](https://user-images.githubusercontent.com/106501849/234232203-9020ec06-6194-40d1-8347-ef8521e4c8ea.png)
index.js文件中 371行 中用的es6的结构方法,文档中并没有说明需要提供参数
应该是取消结构,给与函数默认值
解决方法：
getSvgData(paddingX = 0, paddingY = 0 )

**Comment by wanglin2** [comment]
![image](https://user-images.githubusercontent.com/17272433/234234101-60f3eb0e-2b56-4578-821e-a92217f5b18f.png)
新版本修复了这个问题，文档稍后更新~
