### ISSUE TITLE
Is it possible to keep nods in the user defiend position?

### ISSUE THREAD

**Issue by mcrpl** [wanglin2/mind-map#14]
I came across your project. it's very cool.. but when I try to include more than 20 nodes in the root node the mind map cannot fit into the page. I am trying to export it as png and include it in the PowerPoint presentation but it is difficult to do it with auto position.. is it possible to mode nodes freely to rearrange the nodes so that I could use this code in my project?

**Comment by mcrpl** [comment]
我遇到了你的项目。这很酷.. 但是当我尝试在根节点中包含超过 20 个节点时，思维导图无法适应页面。我正在尝试将其导出为 png 并将其包含在 PowerPoint 演示文稿中，但使用自动位置很难做到这一点。是否可以自由模式节点以重新排列节点，以便我可以在我的项目中使用此代码？

**Comment by wanglin2** [comment]
Good suggestion, but it may take some time to support it

**Comment by mcrpl** [comment]
Hi @wanglin2 sir, I have added the question in [Stackoverflow](https://stackoverflow.com/questions/73169377/why-cant-i-keep-svg-node-in-the-user-defined-position) regarding this enhancement

**Comment by wanglin2** [comment]
Added the free drag and drop function of nodes. Now you can drag the nodes to the position you want

**Comment by mcrpl** [comment]
Hi @wanglin2 sir, it's working perfectly sir thank you... but if we change the structure after dragging and dropping the nodes it's not working properly [node keep its old position (drag and drop position)]

**Comment by wanglin2** [comment]
![image](https://user-images.githubusercontent.com/17272433/183402649-5da378f6-f076-4aec-a47d-1726f142ad92.png)
You can use the organize function in the contextmenu, or use the shortcut key shift + L to restore the default position
