### ISSUE TITLE
怎么让内容fit到画布内部，不要超出边界，resize好像不起作用？

### ISSUE THREAD

**Issue by ssikyou** [wanglin2/mind-map#144]

**Comment by wanglin2** [comment]
resize只是调整画布的大小，不会改变思维导图的位置，可以调用mindMap.view.reset()方法重置视图

**Comment by wanglin2** [comment]
resize只是调整画布的大小，不会改变思维导图的位置，可以调用mindMap.view.reset()方法重置视图

**Comment by ssikyou** [comment]
刚刚试了下mindMap.view.reset()，只是重置了，并没有把内容放到画布内部。我原始数据一加载内容就是超出当前画布边界的，我想要的是怎么自动缩放到适应画布大小。

**Comment by wanglin2** [comment]
暂时没有这个功能，可以等待后续更新

**Comment by wanglin2** [comment]
加了一个fit方法，可以升级到0.6.0试试，https://wanglin2.github.io/mind-map/#/doc/zh/view
