### ISSUE TITLE
提点意见

### ISSUE THREAD

**Issue by star755** [wanglin2/mind-map#153]
之前都用百度脑图离线版，刚试用了一下。感觉比百度脑图好。
但有些地方用不惯。

1、离线单机版启动很慢，能不能换下浏览器框架，让单机版程序启动加快。
2、鼠标左右键功能能不能换下。现在左键按压移动，右键按压框选。调换下可以不。

**Comment by wanglin2** [comment]
第二个问题可以通过这里切换
![image](https://github.com/wanglin2/mind-map/assets/17272433/9fd4f733-20af-42d1-8f89-2f2a39648d4c)

**Comment by wanglin2** [comment]
第一个问题，客户端是用electron构建的，electron用的应该就是chrome内核，这个可能改不了

**Comment by star755** [comment]
666



在 2023-06-27 11:21:24，"街角小林" ***@***.***> 写道：

第二个问题可以通过这里切换

**Comment by star755** [comment]
我现在用的https://github.com/NaoTu/DesktopNaotu，它这个在初次启动很快，但重复开第二个进程较慢。



在 2023-06-27 11:22:55，"街角小林" ***@***.***> 写道：

第一个问题，客户端是用electron构建的，electron用的应该就是chrome内核，这个可能改不了

**Comment by star755** [comment]
刚才看了下https://github.com/NaoTu/DesktopNaotu的版本记录，它还是用的chrome，是某个精简版本。
“基于 miniblink 的提供的 chrome 精简版内核”



在 2023-06-27 11:22:55，"街角小林" ***@***.***> 写道：

第一个问题，客户端是用electron构建的，electron用的应该就是chrome内核，这个可能改不了

**Comment by wanglin2** [comment]
了解，后续会尝试一下~
