### ISSUE TITLE
赞一个。 顺道提个意见。

### ISSUE THREAD

**Issue by goldli** [wanglin2/mind-map#154]
非常不错。 我网上找了好多脑图软件。你这个真的非常好。

提个意见：
1. 鼠标滚动。向下 缩小， 向上放大。或者自定义 缩放的方向。 或者加一个锁定功能。
因为 我习惯向会向下滚动鼠标滚轮。

插入同级节点
插入子级节点

2. 以上2个操作，其实是一个操作， 插入子级节点， 直接使用 Tab 键操作就行。

3.图插入后，能够允许 调整图片大小/ 同时要有一个默认大小(当图像太大时)。 这个很重要。 不然，一个2000 * 2000 的图，页面都不一定装得下

**Comment by wanglin2** [comment]
如果不习惯鼠标滚动缩放，可以设置成鼠标滚动移动画布![image](https://github.com/wanglin2/mind-map/assets/17272433/bb5cfee5-7b77-4e43-b48f-7157053f66d1)

插入同级节点和插入子节点，都可以用快捷键，Enter和Tab

目前图片是有默认最大显示大小的，但是还不支持单个调整，后续会考虑增加

**Comment by goldli** [comment]
可能我没有说明白
1。鼠标滚动缩放这个功能是很好的。 
2。插入同级节点
这2个操作，在xmid中
  ctrl + 向上 是放大， ctrl+向下是缩小
  插入同级节点就是选中父级追加一个子节点。 这个操作是不需要的。 因为很简单的一个道理： 在某种情况下你插入同级节点，可能最后发现插入到错误的节点下了。 我的意思是 父级 选错了。
所以， 不如只在当前节点下追加子节点。 这样节点关系就很明确。

**Comment by wanglin2** [comment]
这个怎么说呢，各有各的需求把

**Comment by goldli** [comment]
OK

**Comment by wanglin2** [comment]
鼠标滚轮缩放方向和图片大小调整最近会更新，可以关注更新日志，或者进群也可以哈

**Comment by wanglin2** [comment]
鼠标滚轮缩放方向现在可以通过这里调整了：
![image](https://github.com/wanglin2/mind-map/assets/17272433/4e649cd7-0b29-4273-969a-4b8cbdecf954)

**Comment by wanglin2** [comment]
图片大小调整也支持了：
![image](https://github.com/wanglin2/mind-map/assets/17272433/420981e2-fe15-420d-86ed-5aa8b1165c66)
