### ISSUE TITLE
BUG：当编辑节点为某些英文单词的时候，退出编辑后该节点会展示不完全

### ISSUE THREAD

**Issue by suka233333** [wanglin2/mind-map#157]
如下图：
![smmbug](https://github.com/wanglin2/mind-map/assets/115850846/ac57dd36-d873-474e-ba49-b5d53cba6e4b)

**Comment by suka233333** [comment]
> 在线demo里有这个问题么

这个就是在在线demo里面复现的，主题使用的是默认主题

**Comment by wanglin2** [comment]
看了一下，是因为这个文本实际宽度是小数，但是getBoundingClientRect方法获取到的值是整数，导致宽度小了一点文本换行了
![image](https://github.com/wanglin2/mind-map/assets/17272433/230760c5-2a6e-4858-9717-6cc7b499f43b)

**Comment by wanglin2** [comment]
已修复~
