### ISSUE TITLE
移动端的展示，节点内容会缺失。

### ISSUE THREAD

**Issue by kuaileforever** [wanglin2/mind-map#160]
配置的内容如图：
![image](https://github.com/wanglin2/mind-map/assets/26483419/b041b231-2629-4df7-a05c-4f59cb83a5d3)
有的手机上展示会丢失最后一个文字：
![企业微信截图_16880884833288](https://github.com/wanglin2/mind-map/assets/26483419/c6d69061-a464-4493-889d-38322c2bb827)

**Comment by kuaileforever** [comment]
使用了view.js的 fit一屏内展示

**Comment by wanglin2** [comment]
用的什么版本

**Comment by kuaileforever** [comment]
使用的0.5.11版本，更新了0.6.0的fit函数

**Comment by wanglin2** [comment]
你是自己改的源码么

**Comment by kuaileforever** [comment]
fit函数没有更改，和0.6.0的是一致的。刚才还有反馈图片加载丢失的情况
后台预览是正常的
![image](https://github.com/wanglin2/mind-map/assets/26483419/116e6637-34ea-4f8c-981d-dc86002e3678)
用户反馈的异常
![image](https://github.com/wanglin2/mind-map/assets/26483419/7ac481fe-7dcd-4b00-8a73-c12b3264a705)

**Comment by wanglin2** [comment]
你看能不能更新到最新版本，如果是自己改源码的，那么参考这里改一下试试
![image](https://github.com/wanglin2/mind-map/assets/17272433/ca57960f-84a9-4461-aca8-ca16c2d62335)

**Comment by wanglin2** [comment]
你看能不能更新到最新版本，如果是自己改源码的，那么参考这里改一下试试
![image](https://github.com/wanglin2/mind-map/assets/17272433/ca57960f-84a9-4461-aca8-ca16c2d62335)


> 

这看着不是丢失，是宽度有问题吧

**Comment by wanglin2** [comment]
> fit函数没有更改，和0.6.0的是一致的。刚才还有反馈图片加载丢失的情况 后台预览是正常的 ![image](https://user-images.githubusercontent.com/26483419/249974740-116e6637-34ea-4f8c-981d-dc86002e3678.png) 用户反馈的异常 ![image](https://user-images.githubusercontent.com/26483419/249974637-7ac481fe-7dcd-4b00-8a73-c12b3264a705.png)

这看着不是丢失，是宽度有问题吧

**Comment by kuaileforever** [comment]
文字确实

> 你看能不能更新到最新版本，如果是自己改源码的，那么参考这里改一下试试 ![image](https://user-images.githubusercontent.com/17272433/249975079-ca57960f-84a9-4461-aca8-ca16c2d62335.png)

这个修复了最后一个文字可能丢失的问题。

图片宽度异常，这个可能是什么导致的呢~~~

**Comment by wanglin2** [comment]
> 

这个问题没有遇到过，按理说只要图片的宽高传的是正确的不会出现这种情况

**Comment by wanglin2** [comment]
浏览器上调试一下，或者你看一下能不能在这里复现一下https://wanglin2.github.io/code-run/#/?data=eNqlU01v00AQ/Sur5dAWpUkAUSHTVkApAtSIihQu3R5W3o29zXrW2o%2B0IfKlRyQkuHPgzD/ogZ/Tws9g1k5S6sAJX5KdefP2zXv2jKYGRiqjSfwn5FEuC0kT%2Bgbkc27Hh9bQDi151jSGU0j3blDeBtmhppTwVBcqy/10z4AzGlsjrh32ePDmbYDlWfOpCR75hRzxoD2Sj6UsD62cKBPcgcncgjaqeWHAD9UH5Lu3VXWoVz5y0%2Buv36%2B%2B/Lj6/AnHIyyKf3k0OIi/mkMWUC/Ccl/oGgFeQrx0W6gJUWKH0UKBGPAS5XquQFpGd7d72N1FvJXOBJtKVHJ8grfuDYct4tS5W7wM7rQJyYwBIWdK%2BDwhj/r98vxxLOQy2pSQh/NKxeBvw3eb8YLbTEFC%2BvVsyYVQkDXHiiwfBi3RMwq8DtGpotRyM9JvFrxEWLC6NsaXLun1ApTjrJuaotdCPul3t7oP0BDn561BI7ErXdGN61fRmddtY075hLvUqjIG%2B6c/yGGsJ3MWMrKmIKytj1FcjAHOOU/mnpAdAvJsMbhe2yJ1QoRJQ4Hs3Uz6fY1vI/hn01difa3t5dpGJ84I7nnSuIqO0XhkdFloil6e%2B1hk9Prb5a%2BPFz8vLhlqj82qJomgNFdaWAkReHwSq5hhtVEntHj%2BlccyALSvQxtPUGvt0FJaU3Yr6lbMikL/M8lTvGa%2BYP0u3qyAS2DA79/ttxKeBHn/VrYrH0xV/QZxOHIX
