### ISSUE TITLE
bug：光标在画布外进行放大缩小，会导致画布移出视区

### ISSUE THREAD

**Issue by WangHui0306** [wanglin2/mind-map#166]
点击右下角的放大按钮也有这个问题

**Comment by WangHui0306** [comment]
点击右下角的放大按钮也有这个问题

**Comment by wanglin2** [comment]
![image](https://github.com/wanglin2/mind-map/assets/17272433/b251cff3-933d-4a9e-9419-addc5e33ccd8)

**Comment by wanglin2** [comment]
![image](https://github.com/wanglin2/mind-map/assets/17272433/b251cff3-933d-4a9e-9419-addc5e33ccd8)

**Comment by WangHui0306** [comment]
如
1、光标在导图里
2、直接点击放大
<img width="750" alt="image" src="https://github.com/wanglin2/mind-map/assets/9211321/b9323182-383b-4550-ab7d-5cef4fe3a96d">

**Comment by wanglin2** [comment]
鼠标在画布里缩放是以鼠标所在位置为中心点进行缩放的

**Comment by WangHui0306** [comment]
> 鼠标在画布里缩放是以鼠标所在位置为中心点进行缩放的

所以容易导致画布移出视区，且偏离很远，
我看processon，会先调整transform的位置，然后再进行缩放，保证画布不会移出视区
