### ISSUE TITLE
功能建议：根据唯一id跳转到指定节点（并自动展开到该节点的层级）

### ISSUE THREAD

**Issue by suka233333** [wanglin2/mind-map#175]
### 功能描述：
想要这么一个功能，能从外部拿到目标节点的唯一id，然后调用相应api，导图就能跳转到目标节点，如果目标节点的祖先节点是收缩的，就自动展开到目标节点

### 场景描述：
这个功能对于和外部系统的联动意义重大，比如说，可以通过webhook的方式，或者其他任何方式，URL Scheme等等，导图app接收到了外部传入的这个id，就能根据这个id自动定位到目标节点并展开到目标节点

### 使用描述：
例如，可能的调用方式:      _导图实例_.execCommand('GO_TARGET_NODE', nodeid, callbackFn)

### 其他：
如果要完成这个功能，那就需要给getFullData方法导出的导图数据的每一个节点都加上唯一id，可能会增大导出的数据，但是我认为这是值得的

**Comment by wanglin2** [comment]
已支持~

**Comment by suka233333** [comment]
> 已支持~

大佬强!!!
