### ISSUE TITLE
客户端：增加自动保存

### ISSUE THREAD

**Issue by wanglin2** [wanglin2/mind-map#182]

**Comment by hengxing666** [comment]
请问更新版本在哪里下载呢？
![uTools_1689733002040](https://github.com/wanglin2/mind-map/assets/139885890/878ca539-eef8-4650-a3fb-87a480aeed50)

**Comment by wanglin2** [comment]
就在下面啊

**Comment by hengxing666** [comment]
呃……这个版本不是老的那个吗？
![uTools_1689733181807](https://github.com/wanglin2/mind-map/assets/139885890/d55b5e17-532d-48c1-aa5c-263010266a73)

**Comment by wanglin2** [comment]
是啊，如果更新了也是在这个页面下载，现在还没更新，issue没关就代表没改呢

**Comment by hengxing666** [comment]
噢，好的谢谢啦

**Comment by wanglin2** [comment]
已支持五秒未操作自动保存
