### ISSUE TITLE
是否开启节点富文本编辑按钮有bug

### ISSUE THREAD

**Issue by myloveht88** [wanglin2/mind-map#188]
选择节点，开启富文本，再点击关闭富文本，会出现这个场景
![2380cd7e-c664-404d-a448-69e31e3c514c](https://github.com/wanglin2/mind-map/assets/86819778/fee02d50-df7e-4aec-986d-93271c009c12)
![6abc7c80-531b-4b90-b1bf-1fb70b024c9f](https://github.com/wanglin2/mind-map/assets/86819778/89e1dbf9-740a-4088-a89f-74dc1b33af4f)

**Comment by wanglin2** [comment]
已修复~
