### ISSUE TITLE
渲染react组件节点

### ISSUE THREAD

**Issue by h5chenhang** [wanglin2/mind-map#192]
const el = document.createElement('div');
el.style.width = '227px';
el.style.height = '60px';
const currentNode = node.nodeData.data;
const root = createRoot(el);
root.render(<CustomRootNode>{currentNode.text}</CustomRootNode>);
return el;

**Comment by wanglin2** [comment]
感谢，已添加到文档~

**Comment by DerrickTel** [comment]
> const el = document.createElement('div'); el.style.width = '227px'; el.style.height = '60px'; const currentNode = node.nodeData.data; const root = createRoot(el); root.render({currentNode.text}); return el;

root.render({currentNode.text});

这一行有问题，对象没有key
