### ISSUE TITLE
使用自定义的节点，首次渲染正常，但是项目路由跳转后再返回，就只渲染线条，不渲染节点了。刷新浏览器后又正常了

### ISSUE THREAD

**Issue by shuiche-it** [wanglin2/mind-map#202]
首次渲染：

![image](https://github.com/wanglin2/mind-map/assets/10776422/625c731e-f60b-45a6-b010-a618f1a79542)

切换路由后再返回：
![image](https://github.com/wanglin2/mind-map/assets/10776422/fcbfb7e3-f878-4f09-b28c-cbca62601dba)

**Comment by shuiche-it** [comment]
和vue3组件没关系，用html代码也是一样，只有首次才会渲染，切换路由再返回，就不渲染了。

**Comment by shuiche-it** [comment]
目前定位到的原因是：节点的宽高获取的都是0，但是不知道怎么解决
![image](https://github.com/wanglin2/mind-map/assets/10776422/61e8d1fb-5687-4b21-9861-9c291f9d4f11)

**Comment by shuiche-it** [comment]
我自定义的节点内容是这样的：已经给了节点宽高了，依然是首次正常，切换路由后就不正常了
```
let div = document.createElement('div')
            div.className = 'my-box'
            div.style.width='100px'
            div.style.height='100px'
            div.innerHTML = `
            <h1>我是自定义节点</h1>
            ${ node.nodeData.data.text }`
            return div
```

**Comment by shuiche-it** [comment]
我还尝试了在渲染完成后，再次调用 reRender 函数重新渲染，依然解决不了问题

**Comment by wanglin2** [comment]
原因是会创建一个div来获取自定义元素的宽高，这个div会添加到容器元素内，这个div会缓存，所以容器元素被删了，缓存没有清空，所以div脱离了文档后就获取不到正常的宽高了，
![image](https://github.com/wanglin2/mind-map/assets/17272433/c6316479-f1cf-4806-a5f5-520e389adff2)
临时解决方案是每次都重新创建这个元素，下次更新会解决这个问题

**Comment by shuiche-it** [comment]
在measureCustomNodeContentSize函数中，增加  `warpEl = null` 就可以了。
<img width="1415" alt="image" src="https://github.com/wanglin2/mind-map/assets/10776422/0afcb7a8-7348-4a5e-bde8-0470f7128e03">

**Comment by wanglin2** [comment]
已修复
