### ISSUE TITLE
概要问题

### ISSUE THREAD

**Issue by Toseethebiggerworld** [wanglin2/mind-map#207]
我选中多个分支想要建立一个概要，但每个分支都建立了一个概要。官方示例中却可以多个分支建立一个概要。
![image](https://github.com/wanglin2/mind-map/assets/50401008/a356d6d8-933b-4c53-aaae-6d5f43a2c9e5)

**Comment by Toseethebiggerworld** [comment]
上图中第一个二级节点中的概要是官方自带的，第二个二级节点的概要是我自己建立的

**Comment by Toseethebiggerworld** [comment]
我的问题是，如何像官方示例那样将多个分支/节点建立一个概要

**Comment by Toseethebiggerworld** [comment]
另外有一个建议：概要能否像普通节点那种能够建立同级节点和下级节点。在实际过程中，节点之间的联系可能会进一步衍生出多个问题，即节点的概要通常不止一个，因此多个同级概要且其子节点是有必要的。

**Comment by wanglin2** [comment]
概要是属于某一个节点的，所以你给多个节点的共同父节点设置概要，就会达到图一的效果

**Comment by wanglin2** [comment]
受限于设计原因，概要后面无法再继续添加节点

**Comment by Toseethebiggerworld** [comment]
谢谢

**Comment by Smithcaige** [comment]
你这个关联是怎么处理的呢
