### ISSUE TITLE
dist版本能否方便打包成  xxx.min.js

### ISSUE THREAD

**Issue by kalcaddle** [wanglin2/mind-map#209]
文件不大的情况下, 
单个文件或很少文件,能较少网络请求次数

**Comment by wanglin2** [comment]
<img width="313" alt="image" src="https://github.com/wanglin2/mind-map/assets/17272433/19504456-dbc7-4c95-bcff-6452ca772c35">

增加了esm.min.js

**Comment by kalcaddle** [comment]
可能我表述有点不太清楚. 希望是mind-map/main/dist/chunkxx.js 打包成少量的js;
我们希望是将"Web 思维导图"作为模块使用. 同时这一块希望加入一些配置.

**Comment by wanglin2** [comment]
还是没太懂，建议可以先自行尝试修改一下打包配置~

**Comment by kalcaddle** [comment]
<img width="934" alt="image" src="https://github.com/wanglin2/mind-map/assets/3761968/bc400c3b-4175-42cb-932e-b683432a496b">
意思是"Web 思维导图" 的dist的js打包也是min版(https://wanglin2.github.io/mind-map/# 就是这个站点, 加载了很多比较小文件的chunk,希望打包成一个或少量几个)


另外希望将初始化对象,和" js 思维导图库"一样放在html页面中, 类似于kityminder ,这样支持一些配置[如静态资源引用路径,主题等].也方便自定义扩展功能,比如打开url传入的文件,保存等). 

直接引用web项目和引用js库的用户数应该不相上下.
