### ISSUE TITLE
关联线选中后无法删除

### ISSUE THREAD

**Issue by MarconiLewis2023** [wanglin2/mind-map#215]
创建关联线后，再次选中关联线就无法删除，删除快捷键也用不了。

**Comment by wanglin2** [comment]
![1](https://github.com/wanglin2/mind-map/assets/17272433/3551b143-a728-4dde-b1c5-444f65e963ba)
可以删啊

**Comment by MarconiLewis2023** [comment]
可能是我卡了吧，狂按快捷键但是没反应
