### ISSUE TITLE
一些问题与建议反馈

### ISSUE THREAD

**Issue by kalcaddle** [wanglin2/mind-map#216]
首先,感谢作者的优秀产品.下面反馈一些问题及建议

1. "一个 Web 思维导图" 希望更完善一点(dist的js打包, 将初始化对象,和" js 思维导图库"一样放在html页面中, 类似于kityminder ,这样支持一些配置[如静态资源引用路径,主题等].也方便自定义扩展功能,比如打开url传入的文件,保存等). 直接引用项目和引用js库的用户数应该不相上下.
2. ui界面元素希望尽量多加入元素的class,方便自定义样式(插入图片,超链接等对话框,有class后方便移动端适配大小,目前对话框在移动端上显示宽度太窄;   其他如弹出对话框,右键菜单item,顶部工具栏按钮,右侧工具栏按钮,底部工具栏按钮等,能加个class更好; 也方便使用者隐藏或调整界面样式)
3. 部分问题: 大纲点击文字有时候编辑状态会失去焦点(参考zhixi); 大纲样式可以不使用节点样式(一级节点在部分主题下为白色,右侧大纲白色文字就看不见)
4. 细节优化建议: 双击节点选中文字更好;双击节点输入时,输入框样式边框覆盖到完整节点的话体验会更好; 节点鼠标hover有一个样式体验会更好.鼠标中键按住拖拽画布支持(左键拖拽可能误操作在节点上,右键框选, 中键拖拽画布就很完善了); 节点拖拽时拖拽到其他节点时连接线也跟着更新会更好(参考zhixi)

#### 其他功能建议
1. 格式刷功能(设置好节点样式后,能快速将样式应用到其他节点,目前操作比较麻烦,得一个个设置)
2. 大纲体验优化建议(参考zhixi): 能支持拖拽调整顺序,能大纲模式编辑(全屏编辑, enter添加子节点并自动焦点,tab插入子节点并焦点);这一块做好就完全替代幕布产品了.
3. 搜索建议: 建议直接搜索大纲文字,这样有结果展示,方便快速选择切换.

**Comment by wanglin2** [comment]
[mind-map.zip](https://github.com/wanglin2/mind-map/files/12214773/mind-map.zip)

针对第一点，做了一些修改，在html页面里增加一行window.takeOverApp = true配置后应用默认不会进行初始化，可以执行暴露出的方法进行初始化，保存和获取思维导图的相关方法需要定义到一个全局变量上，详细可以参考压缩包内的示例

**Comment by wanglin2** [comment]
> [mind-map.zip](https://github.com/wanglin2/mind-map/files/12214773/mind-map.zip)
> 
> 针对第一点，做了一些修改，在html页面里增加一行window.takeOverApp = true配置后应用默认不会进行初始化，可以执行暴露出的方法进行初始化，保存和获取思维导图的相关方法需要定义到一个全局变量上，详细可以参考压缩包内的示例

详细信息已更新到文档：https://wanglin2.github.io/mind-map/#/doc/zh/deploy/%E5%AF%B9%E6%8E%A5%E8%87%AA%E5%B7%B1%E7%9A%84%E5%AD%98%E5%82%A8%E6%9C%8D%E5%8A%A1

**Comment by wanglin2** [comment]
> > [mind-map.zip](https://github.com/wanglin2/mind-map/files/12214773/mind-map.zip)
> > 针对第一点，做了一些修改，在html页面里增加一行window.takeOverApp = true配置后应用默认不会进行初始化，可以执行暴露出的方法进行初始化，保存和获取思维导图的相关方法需要定义到一个全局变量上，详细可以参考压缩包内的示例
> 
> 详细信息已更新到文档：https://wanglin2.github.io/mind-map/#/doc/zh/deploy/%E5%AF%B9%E6%8E%A5%E8%87%AA%E5%B7%B1%E7%9A%84%E5%AD%98%E5%82%A8%E6%9C%8D%E5%8A%A1

只能做到这种程度了：https://wanglin2.github.io/mind-map/#/doc/zh/deploy/%E4%BF%AE%E6%94%B9%E9%9D%99%E6%80%81%E8%B5%84%E6%BA%90%E8%B7%AF%E5%BE%84

**Comment by kalcaddle** [comment]
辛苦了.  这样就足够了.

**Comment by kalcaddle** [comment]
ok
