### ISSUE TITLE
需求建议：支持自定义普通节点的icon按钮功能

### ISSUE THREAD

**Issue by suka233333** [wanglin2/mind-map#219]
### 需求预览：
这是目前的节点（图一）：
![image](https://github.com/wanglin2/mind-map/assets/115850846/5ce4e4c9-1331-4d8c-af54-81ecd3cffd73)
这是添加了一个自定义按钮的节点（图二）：
![image](https://github.com/wanglin2/mind-map/assets/115850846/3b060483-624a-44d8-bacf-56df979b8f08)
### 需求描述：
想要能给普通节点拓展一些独特的功能，自定义按钮感觉是一个很好的方向，如果能给普通节点添加自定义按钮的话，感觉可以更好的拓展功能和覆写原生的功能，比如说，如果想要自定义导图自带的超链接或者备注的icon，以适应不同的导图风格，就可以使用自定义按钮的功能，按钮样式设置为想要的icon图标，点击事件可以自定义为弹出备注框或者打开超链接，甚至还能拓展hover事件，做一些额外的事情。这样就很轻松的完成了对原生功能的覆写。
### 其它：
1.当设置自定义按钮的时候，应该能够自定义该按钮的位置，比如传入 -1 ,则默认将该自定义按钮置于节点的最后面，例如上面的图二；
2.设置自定义按钮的时候，自定义的数据保存在该节点中即可，这样可以在自定义事件的时候拿到。

**Comment by wanglin2** [comment]
这个功能暂时不考虑，有需求只能二次开发了
