### ISSUE TITLE
多个子节点选中其中几个进行概要包裹 如ximind

### ISSUE THREAD

**Issue by pengzhuo9808** [wanglin2/mind-map#220]
<img width="871" alt="image" src="https://github.com/wanglin2/mind-map/assets/49629749/6c4f6866-4464-4c3c-87bd-eaf1d81111f9">
目前插件显示是一个子节点一个概要 或者一个子节点下全选  不能进行特定的部分选中

**Comment by wanglin2** [comment]
因为底层设计原因，这个需求暂时无法实现
