### ISSUE TITLE
节点鼠标hover有一个样式体验会更好

### ISSUE THREAD

**Issue by wanglin2** [wanglin2/mind-map#227]

**Comment by kalcaddle** [comment]
节点相关体验优化:

hover样式, 和选中时边框一样,颜色稍浅
选中边框建议都在节点边框外一层;设置边框颜色样式等能更直观看到变化(目前会被挡住)
双击节点输入时,输入框样式边框覆盖到完整节点的话会更好(目前左右有个边距)
节点风格设置: 边框样式/线宽/形状;线条样式/线宽; 下拉选择建议加个图标,使用时会更直观(如zhixi)

**Comment by wanglin2** [comment]
节点鼠标hover和激活样式已修改，等待下次更新
