### ISSUE TITLE
Cannot add Capital Letters

### ISSUE THREAD

**Issue by diwakaran1dan** [wanglin2/mind-map#23]
Hi there, i tried this code.. it's really good.. 👍
But is there some limitations i faced such as using capital letters by using SHIFT and keys,  trying to add different colours for each connections, and user defined connection style (like straight line, curved line, boxed line...)

Is there any way to do it?

**Comment by wanglin2** [comment]
Cannot input capital letters bug have been fixed，but custom line cannot be supported at present.

**Comment by diwakaran1dan** [comment]
cool, its working fine sir, and I would like to add one more suggestion to this project, a way to **change the node shape** (such as Nonagon, Octagon, Heptagon, Hexagon, Triangle, Scalene triangle, Right triangle, Parallelogram, Rhombus, Square, Pentagon, Circle, Oval, Heart, Cross, Arrow, Cube, Cylinder, Star, Crescent) and way to enter **user-defined SVG icons** in the nodes. and **flow chart style**

this might help in the time of doing flow charts/mind map style

**Comment by wanglin2** [comment]
Good suggestion. Nodes support more shapes and will support them in the near future

**Comment by wanglin2** [comment]
hello, now can change the node shape, you can have a try
