### ISSUE TITLE
这个好像不支持vue3版本

### ISSUE THREAD

**Issue by huangyuanyin** [wanglin2/mind-map#24]
这个好像不支持vue3版本

**Comment by wanglin2** [comment]
核心库simplie-mind-map是框架无关的，只是按钮侧边栏弹窗之类的需要自己开发，所以你可以参照vue2的demo自己开发vue3版本的。

**Comment by huangyuanyin** [comment]
支持vue3，已成功升级为vue3

**Comment by wanglin2** [comment]
有仓库地址的话可以发一下~
