### ISSUE TITLE
bug: 快速拖动节点几次后，会报错，然后拖动节点调整功能失效

### ISSUE THREAD

**Issue by suka233333** [wanglin2/mind-map#243]
## 复现步骤：
快速拖动除了根节点的其它任意节点至画布空白处，重复几次，就有较大几率复现，具体操作如下：
## 官方示例可以复现：
![mindBug](https://github.com/wanglin2/mind-map/assets/115850846/e7ecb0b1-528c-4322-8757-8017aa968bed)
## 报错截图：
![image](https://github.com/wanglin2/mind-map/assets/115850846/cc72f06f-2f0f-450d-8ef9-6d437ef00e60)
![image](https://github.com/wanglin2/mind-map/assets/115850846/0632346d-7c81-48b1-85e0-c954626bb8d0)
![image](https://github.com/wanglin2/mind-map/assets/115850846/f378d4ee-2658-470e-8d88-4abce582fe12)
## 出现该bug后，导出的导图文件（github默认不能上传json后缀的文件，将以下文件的zip后缀手动改为json即可）：
[bug.zip](https://github.com/wanglin2/mind-map/files/12288075/bug.zip)

**Comment by wanglin2** [comment]
已修改，等待版本更新~
