### ISSUE TITLE
性能：手势缩放卡顿明显

### ISSUE THREAD

**Issue by Xbs233** [wanglin2/mind-map#245]

**Comment by Xbs233** [comment]
![image](https://github.com/wanglin2/mind-map/assets/32960078/26f9f10d-0343-40b6-af43-584993135a79)
缩放过程中，有触发重排。  理论上只改变了transform的值，应该不会重排，待排查。

**Comment by Xbs233** [comment]
<img width="839" alt="image" src="https://github.com/wanglin2/mind-map/assets/32960078/b8316815-4350-4949-beac-4f89f1415674">
对比PC的滚轮，只是触发了repaint

**Comment by wanglin2** [comment]
更新了一个版本，再试一试？
