### ISSUE TITLE
切换主题后，边框颜色消失且不再支持修改

### ISSUE THREAD

**Issue by huangyuanyin** [wanglin2/mind-map#25]
![image](https://user-images.githubusercontent.com/42410679/187698613-b4889f1b-3cb3-48ed-ae0d-7d0178ff46a6.png)

**Comment by wanglin2** [comment]
试了一下没问题，你可以把复现步骤详细描述一下。

**Comment by huangyuanyin** [comment]
步骤：进入页面后，点击主题，切换任一主题后，分支主题节点的边框颜色消失且点击该节点后，选择任一边框颜色都没有效果。
![image](https://user-images.githubusercontent.com/42410679/188254795-0dc6fec3-afb5-4660-aee2-86685ce3ba57.png)
![image](https://user-images.githubusercontent.com/42410679/188255162-7764802f-125a-4d7b-a3ce-695b27f16844.png)

**Comment by huangyuanyin** [comment]
哦！我知道了，我设置边框颜色后，还需给边框设置宽度~~~
![image](https://user-images.githubusercontent.com/42410679/188255297-3298063e-bd23-4d75-a596-7fae290b07db.png)

**Comment by wanglin2** [comment]
是的，有的主题宽度是0，需要自己设置
