### ISSUE TITLE
第三方软件如何集成？

### ISSUE THREAD

**Issue by altair-albert** [wanglin2/mind-map#251]
体验了一下，效果比百度的要好。有没有计划做成类似drawio那样，让第三方程序更容易集成？

**Comment by wanglin2** [comment]
https://wanglin2.github.io/mind-map/#/doc/zh/deploy/%E5%AF%B9%E6%8E%A5%E8%87%AA%E5%B7%B1%E7%9A%84%E5%AD%98%E5%82%A8%E6%9C%8D%E5%8A%A1

**Comment by wanglin2** [comment]
可以参考这个文档集成

**Comment by kalcaddle** [comment]
可参考可道云集成 思绪思维导图

体验地址: http://demo.kodcloud.com/#minder
插件代码: https://demo.kodcloud.com/#s/9irL26nw&editor=1

**Comment by SeptSkyTime** [comment]
> 可参考可道云集成 思绪思维导图
> 
> 体验地址: http://demo.kodcloud.com/#minder 插件代码: https://demo.kodcloud.com/#s/9irL26nw&editor=1

我学习学习，感谢支持！
