### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by zaizaidaxia** [wanglin2/mind-map#256]
诉求：
1. 提供可配置的属性能够支持渲染动画的关闭开启、目的还是希望减少渲染动画来提升大数据量的性能。
2. 优化性能，目前在大数据量的情况下（1000～5000个节点）、进行新增节点、插入节点、编辑节点时不流畅。

希望大佬能优化优化！🙏💗

**Comment by wanglin2** [comment]
目前没有啥动画效果啊
