### ISSUE TITLE
部分浏览器富文本模式下导出图片是空的

### ISSUE THREAD

**Issue by wanglin2** [wanglin2/mind-map#263]

**Comment by wanglin2** [comment]
node-to-image-more库的问题

**Comment by IvonSnow** [comment]
dom-to-image-more 3.1.6版本在firfox上导出的时候只有空白图，版本换成2.16.0可以了，可以试试

**Comment by wanglin2** [comment]
已解决，不使用dom-to-image-more库，直接将svg转换成图片就行了
