### ISSUE TITLE
今天看到这个项目的介绍，试了一下很喜欢，请问有没有办法整合到Blazor页面中？

### ISSUE THREAD

**Issue by SeptSkyTime** [wanglin2/mind-map#266]
我将dist文件夹拷贝到blazor项目的wwwroot文件夹下，然后在wwwroot/libs/js/test.js文件中写入下面的代码：

`import MindMap from "../../dist/js/app";

window.createMindMap = function () {
    const mindMap = new MindMap({
        el: document.getElementById('mindMapContainer'),
        data: {
            "data": {
                "text": "根节点"
            },
            "children": []
        }
    });
};`

在Index.razor页面中写入以下代码：
`@page "/"
@inject IJSRuntime JsRuntime
@using amaSoTask.Shared
@attribute [TabItemOption(Text = "测试", Closable = false)]
<PageTitle>测试</PageTitle>

<div id="mindMapContainer"></div>

@code {
    private IJSObjectReference module;
    private string result;

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            module = await JsRuntime.InvokeAsync<IJSObjectReference>("import", "./libs/js/test.js");
            await module.InvokeVoidAsync("createMindMap");
        }
    }
}`
运行后会报下面的错误：
:5200/dist/js/app:1  Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

请问有没有在Blazor下嵌入该项目经验的友友？

**Comment by wanglin2** [comment]
dist目录是demo项目的文件，只要把dist目录和index.html文件扔到一个静态文件服务器上，访问index.html就可以

**Comment by wanglin2** [comment]
new MindMap是js库的用法，得通过npm安装，是不带界面的，界面是要自己开发

**Comment by wanglin2** [comment]
可以看看文档【部署】章节

**Comment by SeptSkyTime** [comment]
> dist目录是demo项目的文件，只要把dist目录和index.html文件扔到一个静态文件服务器上，访问index.html就可以

我的想法是：通过Blazor页面的操作逻辑从后台读取数据，然后将数据通过JS交互代码传递给simple-mind-map，由simple-mind-map来显示数据。如果单独开一个静态服务访问index.html，还要使用webapi的方式获取后台数据，这样用起来比较麻烦。

**Comment by wanglin2** [comment]
可以试试这种方式：https://github.com/wanglin2/mind-map/issues/251
