### ISSUE TITLE
二级节点后无子节点，展开所有/收起所有操作后的报错信息

### ISSUE THREAD

**Issue by huangyuanyin** [wanglin2/mind-map#27]
simple-mind-map库中,src/Node.js文件中需添加判断条件。

![S3J%QR1T0MJFL{HD3S62G9](https://user-images.githubusercontent.com/42410679/187819652-42746248-18c3-4d84-8ad4-510ac209c20f.png)

**Comment by huangyuanyin** [comment]
simple-mind-map库中,src/Node.js文件中需添加判断条件。
![image](https://user-images.githubusercontent.com/42410679/187819962-084db92e-9f3b-4e5c-a818-6a0dc576f869.png)

**Comment by wanglin2** [comment]
已合并~
