### ISSUE TITLE
请问是否支持通过配置方式与用户的权限进行绑定？

### ISSUE THREAD

**Issue by SeptSkyTime** [wanglin2/mind-map#270]
例如，普通用户只能浏览思维导图（屏蔽编辑工具栏的显示，屏蔽导入导出工具栏的显示等等），而管理员用户则支持完整功能。如果没有计划支持，可否大致指点一下这些工具栏的显示逻辑或流程，我可以自己看看能否增加该功能。

**Comment by wanglin2** [comment]
最简单的方式直接用样式覆盖，把工具栏那些元素都隐藏掉

**Comment by SeptSkyTime** [comment]
> 最简单的方式直接用样式覆盖，把工具栏那些元素都隐藏掉

早上刚刚尝试了修改源码：
在Edit.vue中，注释了NavigatorToolbar、Contextmenu、SidebarTrigger组件
在Edit/Index.vue中，注释了Toolbar组件
可以满足普通用户的浏览需求。
我的思路是，将网站编译为两个版本，分别对应普通用户和管理员用户。
你说的思路我试试，应该更简单。
谢谢支持！

**Comment by wanglin2** [comment]
也不用编译成两个版本，在store里面加个状态，控制这些的显示隐藏，然后只要根据后端返回的数据设置这个状态就行了

**Comment by wanglin2** [comment]
可以参考里面的禅模式

**Comment by SeptSkyTime** [comment]
> 也不用编译成两个版本，在store里面加个状态，控制这些的显示隐藏，然后只要根据后端返回的数据设置这个状态就行了

对的，因为不熟悉vue，所以没有反应过来，禅模式就是一个非常合适的参考样本，谢谢！
