### ISSUE TITLE
本地化打开时右上角的提示

### ISSUE THREAD

**Issue by NHYAYN** [wanglin2/mind-map#271]
hi，首先谢谢你开源分享，非常好用。
问题：
        在本地打开文件时右上角会提示打开本地文件，但是没有关闭或者隐藏提示的选项。
问题出现的场景：
       一般使用的是专用格式，但是有时候想要转换成其他格式如markdown或者图片导出。
这时只能通过F12关闭提示栏才能看到导出按钮。

**Comment by NHYAYN** [comment]
![2023-08-14_224545](https://github.com/wanglin2/mind-map/assets/31437122/0456a48b-bb00-4c31-813d-f516c2339b08)

**Comment by wanglin2** [comment]
已修改~
