### ISSUE TITLE
feat: 更老版本的xmind文件导入兼容

### ISSUE THREAD

**Issue by Xbs233** [wanglin2/mind-map#273]
例如：https://github.com/ckjbug/XMind-Learning/blob/master/ABP%E6%A1%86%E6%9E%B6%E7%9A%84%E5%AD%A6%E4%B9%A0%E8%B7%AF%E7%BA%BF%E5%9B%BE-%E7%BE%A4%E5%8F%8B%E7%89%88.xmind

**Comment by wanglin2** [comment]
这个不是支持的么

**Comment by Xbs233** [comment]
> 这个不是支持的么

举例举得有问题  ： https://github.com/ckjbug/XMind-Learning/blob/master/%E9%98%BF%E9%87%8C%E4%BA%91%E7%9B%BE.xmind

**Comment by wanglin2** [comment]
这个也可以啊，你在demo试过吗
