### ISSUE TITLE
功能需求：增加ts和angular支持

### ISSUE THREAD

**Issue by hyfree** [wanglin2/mind-map#275]
1、增加d.ts 声明文件
2、增加angular的集成示例

**Comment by hyfree** [comment]
也许这样写？
``` typescript
declare module 'mindmap' {
  interface MindMapOptions {
    el: HTMLElement;
    // 其他选项...
  }

  interface MindMapPlugin {
    instanceName: string;
    pluginOpt?: any;
    new (options: { mindMap: MindMap; pluginOpt?: any }): any;
  }

  class MindMap {
    constructor(opt?: MindMapOptions);
    // 方法和属性的声明
    // 例如：render(callback: () => void, source?: string): void;
  }

  namespace MindMap {
    let pluginList: MindMapPlugin[];
    function usePlugin(plugin: MindMapPlugin, opt?: any): void;
    function hasPlugin(plugin: MindMapPlugin): number;
    function defineTheme(name: string, config?: any): void;
  }

  export default MindMap;
}

```

**Comment by wanghao1993** [comment]
这个不限制框架的，用自己写UI就可以。

**Comment by wanghao1993** [comment]
> 也许这样写？
> 
> ```ts
> declare module 'mindmap' {
>   interface MindMapOptions {
>     el: HTMLElement;
>     // 其他选项...
>   }
> 
>   interface MindMapPlugin {
>     instanceName: string;
>     pluginOpt?: any;
>     new (options: { mindMap: MindMap; pluginOpt?: any }): any;
>   }
> 
>   class MindMap {
>     constructor(opt?: MindMapOptions);
>     // 方法和属性的声明
>     // 例如：render(callback: () => void, source?: string): void;
>   }
> 
>   namespace MindMap {
>     let pluginList: MindMapPlugin[];
>     function usePlugin(plugin: MindMapPlugin, opt?: any): void;
>     function hasPlugin(plugin: MindMapPlugin): number;
>     function defineTheme(name: string, config?: any): void;
>   }
> 
>   export default MindMap;
> }
> ```
这个不限制框架的，用自己写UI就可以。

**Comment by wanglin2** [comment]
已添加类型定义

**Comment by xmengweb** [comment]
导入包之后怎么在ts中使用呢? 比如定义某个Node的类型
