### ISSUE TITLE
BUG：当前版本使用的导出方案，当节点内容存在gif动图的时候，无法导出为图片

### ISSUE THREAD

**Issue by suka233333** [wanglin2/mind-map#279]
smm库版本：0.6.16
环境：chrome最新版，官方示例
导图源文件：[思维导图 (9).zip](https://github.com/wanglin2/mind-map/files/12406275/9.zip)
### 复现步骤：
官方示例中，导入上述导图文档，选择导出为图片，控制台出现如下报错
![image](https://github.com/wanglin2/mind-map/assets/115850846/b6e02b4d-d0a5-4402-9569-d325dbbde6cb)

### 另外的一个bug：
当导入的文档中，节点里面有直接粘贴的图片的时候，需要双击一下那个节点才能展示出来图片，如下：
![mindbug1](https://github.com/wanglin2/mind-map/assets/115850846/36d1f4de-89a1-4c6b-bb91-a3e3037d43c9)

**Comment by wanglin2** [comment]
你这个是图片直接粘到了富文本中，实际上是不允许的

**Comment by wanglin2** [comment]
已经拦截了这个操作，可以等待下次更新
