### ISSUE TITLE
实例化失败 是怎么回事

### ISSUE THREAD

**Issue by xssj28** [wanglin2/mind-map#28]
![Snipaste_2022-09-07_11-52-21](https://user-images.githubusercontent.com/98073863/188785119-5ed0e8aa-c0b5-4ff9-949a-8701b1dd304e.png)
![Snipaste_2022-09-07_11-53-33](https://user-images.githubusercontent.com/98073863/188785184-fdfc37b7-c5aa-4826-8f13-5edb1a4166a5.png)

**Comment by wanglin2** [comment]
把rootData改成：
`{
data: {
text: '根节点'
},
children:[]
}`
试试
