### ISSUE TITLE
功能建议：建议增加文件共享功能

### ISSUE THREAD

**Issue by wu529778790** [wanglin2/mind-map#283]
如果这个不在作者的计划呢，可以在连接上接一个文件的url，这样可相当于变相的共享了

xxx.com?fileURl=a.xmind

然后别人打开这个可以看见就行，不一定要实时协作，刷新之后能看见变化就行

**Comment by wanglin2** [comment]
主要是你文件存在哪里呢

**Comment by wanglin2** [comment]
不过好像可以不用考虑存在哪里的问题，这是用这个功能该考虑的，那可以支持

**Comment by wanglin2** [comment]
已支持?fileURl=，等待版本更新~
