### ISSUE TITLE
抽离出来的独立web文件夹下如何进行打包操作~~~

### ISSUE THREAD

**Issue by huangyuanyin** [wanglin2/mind-map#29]

**Comment by wanglin2** [comment]
打包啥，打包web项目？
![image](https://user-images.githubusercontent.com/17272433/189008524-5a2d1e49-61c1-47d8-a7de-882e4c203432.png)

**Comment by huangyuanyin** [comment]
我想把index.html移动到dist目录下该如何操作~~~~

**Comment by wanglin2** [comment]
![image](https://user-images.githubusercontent.com/17272433/189042085-906d800e-c703-4e84-8d55-f26a6669a519.png)
![image](https://user-images.githubusercontent.com/17272433/189042271-bfe7cb63-edab-4350-ae19-c30c360177f0.png)

**Comment by huangyuanyin** [comment]
已成功打包，非常感谢~~~~
