### ISSUE TITLE
客户端显示比例问题：建议工具栏及侧边栏大小可调，或自适应屏幕分辨率以防止重叠遮挡

### ISSUE THREAD

**Issue by hengxing666** [wanglin2/mind-map#290]

**Comment by hengxing666** [comment]
｡:.ﾟヽ(｡◕‿◕｡)ﾉﾟ.:｡+ﾟ

**Comment by wanglin2** [comment]
可以截个图看看

**Comment by hengxing666** [comment]
![1697289349787](https://github.com/wanglin2/mind-map/assets/139885890/dc9d95e1-32c2-457f-b55b-d2e36dcf3288)
这是0.7版本，菜单栏“保存键”被遮挡

**Comment by wanglin2** [comment]
已修改，等待下次更新
