### ISSUE TITLE
搜索框输入获取焦点有问题

### ISSUE THREAD

**Issue by zxr3680166** [wanglin2/mind-map#293]
现在搜索替换的时候，搜索到东西，然后填写替换内容的时候会跑到搜索到的那个节点上去，不知道和 enableAutoEnterTextEditWhenKeydown 设置有没关系

**Comment by wanglin2** [comment]
这个大佬有啥好办法吗，demo里我是直接当鼠标移出搜索替换区域时让输入框失去焦点的
