### ISSUE TITLE
可否支持“根节点”拖拽或者按住“空格键”时推拽，而非默认情况下的全画布拖拽，交互会更加顺畅。

### ISSUE THREAD

**Issue by zhangXiaoMin007** [wanglin2/mind-map#296]

**Comment by wanglin2** [comment]
这个有啥区别呢

**Comment by zhangXiaoMin007** [comment]
> 这个有啥区别呢

这样可能稳定性会更好，否则画面会经常抖动，降低用户误操作的概率。或者两者都支持，让用户去选择。

**Comment by wanglin2** [comment]
目前有两种模式，一是左键多选，右键拖动，二是左键拖动，右键多选，你指的是哪种情况呢

**Comment by zhangXiaoMin007** [comment]
> 目前有两种模式，一是左键多选，右键拖动，二是左键拖动，右键多选，你指的是哪种情况呢

无论是左键还是右键拖动，是否可以支持选择拖动方式：
- 全画布
- 根节点+按下空格键时全画布拖动

**Comment by wanglin2** [comment]
你是思维导图使用者还是开发者呢

**Comment by zhangXiaoMin007** [comment]
> 你是思维导图使用者还是开发者呢

开发者

**Comment by wanglin2** [comment]
那可能会提供这个配置，可以关注后续更新~

**Comment by zhangXiaoMin007** [comment]
> 那可能会提供这个配置，可以关注后续更新~

好！

**Comment by wanglin2** [comment]
尝试了一下，这个功能和现有逻辑冲突比较大，暂时不考虑了，实在有需求可以考虑二次开发

**Comment by zhangXiaoMin007** [comment]
> 尝试了一下，这个功能和现有逻辑冲突比较大，暂时不考虑了，实在有需求可以考虑二次开发

好的
