### ISSUE TITLE
鼠标事件性能损耗 bug

### ISSUE THREAD

**Issue by zxr3680166** [wanglin2/mind-map#299]
<img width="691" alt="image" src="https://github.com/wanglin2/mind-map/assets/4338858/787e0aec-6e1b-423e-be0b-d9ed1b81c654">
<img width="502" alt="image" src="https://github.com/wanglin2/mind-map/assets/4338858/9870dc48-33d3-4a35-a171-7b4650fc5179">

现在鼠标点击思维导图空白区域的时候，也会触发 node_active 事件，好像是没必要的性能浪费，似乎还会引起 error.ts:14 ElementPlusError: [ElOnlyChild] no valid child node found 的警告。我就鼠标放在画布上点击，就会触发。

<img width="587" alt="image" src="https://github.com/wanglin2/mind-map/assets/4338858/8211feca-c4ca-4060-8914-57507b08628b">

加一个限制应该就行了

**Comment by wanglin2** [comment]
已修改，当激活节点没有变化时不触发事件

**Comment by zxr3680166** [comment]
<img width="1539" alt="image" src="https://github.com/wanglin2/mind-map/assets/4338858/f2c2a957-2f9d-451d-b7b9-3e24fef80e58">

加了这个判断，在有激活节点到没激活节点的切换的时候，还是会多发送一次信号
