### ISSUE TITLE
Hi sir, is there any way to change color of the each brach?

### ISSUE THREAD

**Issue by mcrpl** [wanglin2/mind-map#30]
Hi @wanglin2 sir, is there an option to change each branch color separately as shown in the image?

嗨@wanglin2 先生，是否可以选择单独更改每个分支颜色，如图所示？

![image](https://user-images.githubusercontent.com/110148926/189856017-3e7a1fd5-33d7-499a-b850-7c9b36cf819d.png)

**Comment by wanglin2** [comment]
Thank you for your suggestions. These features will be supported in the near future

**Comment by wanglin2** [comment]
Now can change each branch color and export svg will add title tag，you can have a try
