### ISSUE TITLE
导出xmind在xmind8中无法打开

### ISSUE THREAD

**Issue by liunian-123** [wanglin2/mind-map#301]
导出的xmind文件在xmind8中无法打开在新版xmind中会弹出修复弹窗。

**Comment by wanglin2** [comment]
导出文件不支持xmind8，在新版xmind中会弹出修复弹窗的问题已经修复，等待版本更新

**Comment by YGragon** [comment]
xmind 版本 24.01.13311，打开导出的xmind文件还是提示修复

**Comment by wanglin2** [comment]
> xmind 版本 24.01.13311，打开导出的xmind文件还是提示修复

我试了一下没问题啊，你是在线版，还是客户端导出的

**Comment by liunian-123** [comment]
在线版导出的xmind文件，我这边目前也可以使用XMind8导出了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月6日(周三) 中午11:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wanglin2/mind-map] 导出xmind在xmind8中无法打开 (Issue #301)




  
xmind 版本 24.01.13311，打开导出的xmind文件还是提示修复
  
我试了一下没问题啊，你是在线版，还是客户端导出的
