### ISSUE TITLE
关于视图更新时的动画效果

### ISSUE THREAD

**Issue by vimerio-mu** [wanglin2/mind-map#303]
作者您好，和[issue #256 ](https://github.com/wanglin2/mind-map/issues/256)一样，我遇到了渲染动画相关的问题：

在公司一项目中使用mindmap（版本为 0.6.17）时，当数据量变多，动画出现节点和连线不匹配的情况（如下gif）
![GIF 2023-9-5 10-04-55](https://github.com/wanglin2/mind-map/assets/63034397/b0f9cf5e-be55-4fa7-8747-b2f8e8ab5f00)
比较奇怪的是，在我其他的项目中使用同样的数据，却没有出现同样的动画效果（所以也有可能是公司项目中有什么其他部分导致了这一动画）
我尝试梳理了点击展开时的行为：最后的add来自于svg.js
![image](https://github.com/wanglin2/mind-map/assets/63034397/6e549bd8-ef91-400a-85d6-519f58c1a0eb)

我想请问您：
1. 上面的展开行为的归纳是否有误，如果有请您给我一些提示我再思考；
2. mindmap是否有默认的动画更新效果，如果有请问您是否有修改的考虑，或者我可以尝试进行修改；

> 实际上，我是一名新入职的前端开发，我的转正课题就是进行思维导图库的设计，目前我所在的公司使用的就是您的项目 : ) 希望未来我能与您合作让mind-map项目变得更好

3. 如果不是mindmap导致的动画更新效果，是否可能是svg.js导致的呢，您是否能给我提供一些排查的思路呢，谢谢！

**Comment by wanglin2** [comment]
现在的版本已经没有节点动画效果了，可以在在线示例里尝试一下

**Comment by vimerio-mu** [comment]
不好意思，确实是项目依赖出了问题，没有用新的版本，谢谢您！
