### ISSUE TITLE
关于节点比对的优化

### ISSUE THREAD

**Issue by zxr3680166** [wanglin2/mind-map#306]
<img width="570" alt="image" src="https://github.com/wanglin2/mind-map/assets/4338858/0d8aeea9-2db6-4190-9a24-8cf3b3c5ad91">

如图，在 vue3 中由于响应式的加入，有一些传输到后端的节点产生了变化 Proxy，即使代表相同的节点但也不再是单纯的 === 就能判断，个人实测使用 item.uid === node.uid 能更好的兼容多场景，比对的速度没有测试过，理应单属性比对更快

**Comment by wanglin2** [comment]
内部全部改为通过uid判断

**Comment by zxr3680166** [comment]
<img width="973" alt="image" src="https://github.com/wanglin2/mind-map/assets/4338858/da543c51-2e34-47e2-b17a-d7d2f16bf7d9">

这里漏了

**Comment by zxr3680166** [comment]
<img width="543" alt="image" src="https://github.com/wanglin2/mind-map/assets/4338858/40846259-bd41-4a56-babe-3aadd442d808">
