### ISSUE TITLE
希望增加Docker-compose部署方式

### ISSUE THREAD

**Issue by itscolor** [wanglin2/mind-map#309]
RT，想用此方式部署在服务器上面,统一管理Docker项目，望答复，谢谢~

**Comment by xfchu1988** [comment]
@itscolor 我不懂，模仿着简单编辑一下，可以Docker-compose部署方式，你试试
version: '3.7'
services:
  map:
    image: shuiche/mind-map:latest
    container_name: map
    restart: always
    tty: true
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8081:8080"

**Comment by itscolor** [comment]
> @itscolor I don't understand, Imitate a simple edit, You can Docker-compose deployment, You try version: '3.7' services: map: image: shuiche/mind-map:latest container_name: map restart: always tty: true environment: - TZ=Asia/Shanghai ports: - "8081:8080"

Thank you, it's settled.
version: "3.2"
services:
   mind-map:
       image: shuiche/mind-map:latest
       container_name: mind-map
       restart: on-failure:3
       ports:
           - "8081:8080"

**Comment by birdxs** [comment]
B站有up主提供了docker安装方式，我就按照方法安装成功了。
【Docker-搭建一个在线版的思维导图工具-哔哩哔哩】 https://b23.tv/N2clOW5

**Comment by mffan0922** [comment]
还是希望开发者可以维护一个官方的 @wanglin2 不知道大佬是否有考虑

**Comment by Brzjomo** [comment]
### MindMap服务器Docker构建

克隆项目：

```
git clone https://github.com/wanglin2/mind-map
```

进入目录

```
cd mind-map
```

创建`docker-compose.yaml`文件：

```
echo 'version: "3.8"
services:
  mindmap:
    build: .
    container_name: mindmap
    ports:
      - "自定义外部端口:80"' > docker-compose.yaml
```

创建并运行容器：

```
sudo docker-compose up -d
```

#### 注意：

目录和新建等功能需要页面为HTTPS时，才能正常工作。
