### ISSUE TITLE
多选节点时鼠标移动到边缘时的画布移动偏移  没有根据画布位置做适配

### ISSUE THREAD

**Issue by HongFei1998** [wanglin2/mind-map#316]
多选节点时鼠标移动到边缘时的画布移动偏移  没有根据画布位置做适配

**Comment by HongFei1998** [comment]
![image](https://github.com/wanglin2/mind-map/assets/32254020/c2c22ac7-03c3-482c-975f-ad2b62bab9f6)

**Comment by HongFei1998** [comment]
如图，本应该鼠标移动到左边才开始移动画布，但是实际情况是到了第二条箭头位置就开始偏移

**Comment by wanglin2** [comment]
已修复，等待下次更新
