### ISSUE TITLE
导入xmind异常，如果xmind里有title是空的，就会异常

### ISSUE THREAD

**Issue by liangfenging** [wanglin2/mind-map#317]
Uncaught TypeError: Cannot read properties of undefined (reading"split')

**Comment by liangfenging** [comment]
function createTextNode() {
  if (this.nodeData.data.richText) {
    return this.createRichTextNode()
  }
  let g = new G()
  let fontSize = this.getStyle('fontSize', false)
  let lineHeight = this.getStyle('lineHeight', false)
  // 文本超长自动换行
  let textStyle = this.style.getTextFontStyle()
  let textArr = this.nodeData.data.text.split(/\n/gim)



this.nodeData.data.text  undefind

**Comment by wanglin2** [comment]
已修复，等待下次更新
