### ISSUE TITLE
开启富文本模式，使用MindMap.addPlugin(RichText, opt?)函数自定义字体列表，自定义字体选中后不生效。

### ISSUE THREAD

**Issue by zhangXiaoMin007** [wanglin2/mind-map#323]

**Comment by wanglin2** [comment]
![image](https://github.com/wanglin2/mind-map/assets/17272433/7372e367-fbec-4d24-b000-00f923262113)
![image](https://github.com/wanglin2/mind-map/assets/17272433/8a239aa3-2ca4-4515-8564-e97f2eb38e03)

我把插件里的这个字体删了，然后通过选项传进入，设置是生效的，所以你可以先确认一下步骤是否都是正确的，以及你的电脑里是否支持你要设置的字体。

**Comment by zhangXiaoMin007** [comment]
> ![image](https://user-images.githubusercontent.com/17272433/267619134-7372e367-fbec-4d24-b000-00f923262113.png) ![image](https://user-images.githubusercontent.com/17272433/267619181-8a239aa3-2ca4-4515-8564-e97f2eb38e03.png)
> 
> 我把插件里的这个字体删了，然后通过选项传进入，设置是生效的，所以你可以先确认一下步骤是否都是正确的，以及你的电脑里是否支持你要设置的字体。

大概明白问题在哪里了，这里是不是只能支持系统本地的字体，如果使用来自服务端的动态字体（字体源文件来自于COS）就无法生效了。

**Comment by wanglin2** [comment]
那你得自己加载一下相关的字体文件

**Comment by zhangXiaoMin007** [comment]
> 那你得自己加载一下相关的字体文件

加载了，使用<style></style>标签对将动态字体列表挂载到DOM文档流中，仅设置节点的基础样式（或者选中节点的样式），动态字体是可以生效的，但是采用富文本的方式设置节点的内联文本样式时，动态字体点击之后无任何反应。

**Comment by wanglin2** [comment]
![image](https://github.com/wanglin2/mind-map/assets/17272433/968e296b-c742-40bd-92b6-c7b3a965db6c)
![image](https://github.com/wanglin2/mind-map/assets/17272433/f893f70f-d4de-4bc4-b202-feacbc5a8685)
![image](https://github.com/wanglin2/mind-map/assets/17272433/ee20dc44-7838-42ed-a0c5-ac56206b299f)
![image](https://github.com/wanglin2/mind-map/assets/17272433/77dec1d9-c1d6-41eb-90e9-135e9ac59383)

我试了一下也可以啊

**Comment by zhangXiaoMin007** [comment]
> ![image](https://user-images.githubusercontent.com/17272433/267625423-968e296b-c742-40bd-92b6-c7b3a965db6c.png) ![image](https://user-images.githubusercontent.com/17272433/267625488-f893f70f-d4de-4bc4-b202-feacbc5a8685.png) ![image](https://user-images.githubusercontent.com/17272433/267625578-ee20dc44-7838-42ed-a0c5-ac56206b299f.png) ![image](https://user-images.githubusercontent.com/17272433/267625609-77dec1d9-c1d6-41eb-90e9-135e9ac59383.png)
> 
> 我试了一下也可以啊

好的，感谢作者，我研究一下，应该是我哪里用法不对。
