### ISSUE TITLE
将画布的背景图设置为网络图片且和编辑器不同源，导出时抛出异常“Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported”。

### ISSUE THREAD

**Issue by zhangXiaoMin007** [wanglin2/mind-map#332]
![lQLPJx6IC5P8DnDNAajNCNWwDn8vjDA4AV4E9oLu9UCkAA_2261_424](https://github.com/wanglin2/mind-map/assets/28802707/0538e712-610b-4be2-8c85-ab9d46b399c4)
![lQLPJyJMHDnEC_BEzQXcsATU4GijkQkpBPaC_qTApAA_1500_68](https://github.com/wanglin2/mind-map/assets/28802707/ba629445-4e48-41de-b79c-50d3771371b1)

**Comment by wanglin2** [comment]
这个没啥办法

**Comment by zhangXiaoMin007** [comment]
> 这个没啥办法

这个插件支持二次开发吗？

**Comment by zhangXiaoMin007** [comment]
> 你二次开发也没用啊，浏览器的限制

 @好的，明白了，那只能暂时将网络图片转成Base64传入，感谢作者。🎊
