### ISSUE TITLE
Microsoft Edge浏览器右键的手势是否可以取消？

### ISSUE THREAD

**Issue by heihei180** [wanglin2/mind-map#333]
如标题所述，因为感觉谷歌手势功能是用来方便浏览网页的，如果编辑的过程中不小心误触了，可能会发生异常。所以请问是否可以取消哪个手势操作？

Microsoft Edge
版本 116.0.1938.76 (正式版本) (64 位)

**Comment by wanglin2** [comment]
手势是浏览器的功能，你可以自行在浏览器设置里关掉
