### ISSUE TITLE
数据多了导出pdf报错Uncaught RangeError: Invalid string length

### ISSUE THREAD

**Issue by liuwei012** [wanglin2/mind-map#337]

**Comment by liuwei012** [comment]
[思维导图json.docx](https://github.com/wanglin2/mind-map/files/12654575/json.docx)

**Comment by wanglin2** [comment]
看着是jspdf库的问题，https://github.com/parallax/jsPDF/pull/3625

**Comment by wanglin2** [comment]
已修复，等待下次更新
