### ISSUE TITLE
Export插件中的"getSvgData()"函数存在问题

### ISSUE THREAD

**Issue by zhangXiaoMin007** [wanglin2/mind-map#339]
Export插件中的"getSvgData()"函数存在问题
![getSvgData](https://github.com/wanglin2/mind-map/assets/28802707/ad7ba4d8-568b-4658-aa84-b860cb87a72e)
导致getSvgData()函数异常的思维导图源数据
[导致getSvgData异常的数据.txt](https://github.com/wanglin2/mind-map/files/12657531/getSvgData.txt)

**Comment by wanglin2** [comment]
已修改

**Comment by zhangXiaoMin007** [comment]
> 已修改

🎈
