### ISSUE TITLE
RichText插件中的handleSetData(data)函数存在逻辑缺陷。

### ISSUE THREAD

**Issue by zhangXiaoMin007** [wanglin2/mind-map#344]
导入.json文件后，关闭/开启“节点富文本”，抛出以下异常，偶现。
![lQLPJwK2s7WBT2TNAffNCAOwBqbswa5mOoQE_vtBIUAMAA_2051_503](https://github.com/wanglin2/mind-map/assets/28802707/d83ffb1a-2f7a-4856-8f6d-49e562ea6bc0)
在应用层重写RichText插件中的handleSetData(data)函数后，定位到问题原因
![lQLPJwsG6235muTNA6nNBYCwlzxe5VK9Fi8E_vvfCoBPAA_1408_937](https://github.com/wanglin2/mind-map/assets/28802707/024f8b81-7193-4db8-a986-b56f4e8702ea)
导入的.json文件为
[有水印.txt](https://github.com/wanglin2/mind-map/files/12679291/default.txt)

**Comment by wanglin2** [comment]
已修改

**Comment by zhangXiaoMin007** [comment]
> 已修改
🎈
