### ISSUE TITLE
[问题反馈]保存文件的时候一直显示"正在创建文件"

### ISSUE THREAD

**Issue by birdxs** [wanglin2/mind-map#349]
我参考教程使用docker方式安装的mind-map【Docker-搭建一个在线版的思维导图工具-哔哩哔哩】 https://b23.tv/N2clOW5
但是在使用过程保存文件的时候一直提示正在创建文件，无法保存成功
浏览器是360极速浏览器13.5.2044.0

**Comment by birdxs** [comment]
![Uploading 1695534696423.jpg…]()

**Comment by wanglin2** [comment]
你部署的访问地址能否发一下
