### ISSUE TITLE
您好，能否提供一个下拉选项或操作按钮，来控制展开节点的层级数量（当多个节点层级很深时，可一键展开到指定节点层级）例如下图

### ISSUE THREAD

**Issue by huangyuanyin** [wanglin2/mind-map#35]
![image](https://user-images.githubusercontent.com/42410679/191906355-777914fb-1b2f-4198-979c-53efaff517c0.png)

**Comment by wanglin2** [comment]
你好，现在支持展开到指定层级了，在画布空白处点击右键即可选择展开到某个层级
