### ISSUE TITLE
谢谢您的项目，我将此导图做成了obsidian插件，希望可以推广给更多人

### ISSUE THREAD

**Issue by lithStudy** [wanglin2/mind-map#350]
非常棒的项目，使用体验非常好。文档也非常完善作为一个后端也能轻松上手。我将您的项目集成到了obsidian插件中，希望可以推广给更多的人。由于我对前端不太擅长，目前这个插件仅仅是可以使用简单功能，期待大神更进一步完善。https://github.com/lithStudy/obsidian-simple-mindmap

**Comment by wanglin2** [comment]
必须要点个赞，但是短期我可能没有时间一起维护这个插件

**Comment by songxianpeng** [comment]
辛苦问下这个有后续进展么，期望可以集成到插件市场
