### ISSUE TITLE
数学公式显示异常

### ISSUE THREAD

**Issue by fcwys** [wanglin2/mind-map#352]
数学公式显示异常，如图：
![image](https://github.com/wanglin2/mind-map/assets/28641034/a35624fa-ab74-4512-8d0f-c0482cce104e)

![image](https://github.com/wanglin2/mind-map/assets/28641034/07c56503-62eb-4992-a0cd-966a8c21c314)

**Comment by wanglin2** [comment]
哪个浏览器呢

**Comment by fcwys** [comment]
360极速浏览器

**Comment by lovememo** [comment]
我也出现这个问题了，edge 浏览器，chromium 版本是 101.0.1210.53
我自己 内网 nginx 部署的，数学公式显示异常

**Comment by wanglin2** [comment]
浏览器兼容性问题统一汇总到：https://github.com/wanglin2/mind-map/issues/503
