### ISSUE TITLE
新建一个节点时，文本框内的文字会出现所有样式丢失只显示默认样式的Bug

### ISSUE THREAD

**Issue by ImagineNight** [wanglin2/mind-map#366]
• 环境：win版客户端
• 描述：触发方式未知，太难稳定复现这个BUG，解决方案是在后面随便跟一个中文符号就瞬间好了，目测是什么GBK的问题，不是大问题，但是对强迫症极其不友好（）
• 图示：
[![-2023-10-14-102352.png](https://s1.imagehub.cc/images/2023/10/14/-2023-10-14-102352.png)](https://www.imagehub.cc/image/11JWpZ)
[![-2023-10-14-102405.png](https://s1.imagehub.cc/images/2023/10/14/-2023-10-14-102405.png)](https://www.imagehub.cc/image/11Jxbs)

**Comment by wanglin2** [comment]
插入新节点、在全选状态下输入中文，然后再全部删除，再输入中文，大概率能复现。

已修复，等待下个版本更新。
