### ISSUE TITLE
npm升级至0.2.10时，切换结构为思维导图结构时，报错（我是在vue3情况下，具体报错如下），降至0.2.9版本正常使用。

### ISSUE THREAD

**Issue by huangyuanyin** [wanglin2/mind-map#37]
![image](https://user-images.githubusercontent.com/42410679/194791867-cdc04ff7-6336-483a-8b14-e45a0e9f23d0.png)
![image](https://user-images.githubusercontent.com/42410679/194791945-8af3a4f4-e23b-4680-85be-ce914aeea39d.png)

**Comment by huangyuanyin** [comment]
这个报错是因为什么呀，切换其他结构时正常运行，只有切换结构为思维导图结构时报错，且只有在0.2.10版本下报错。

**Comment by wanglin2** [comment]
![image](https://user-images.githubusercontent.com/17272433/194792163-8e8a6d8b-15d7-4a99-8b07-77d00d6e1221.png)
bug，path重复定义了，删掉一个应该就没问题了

**Comment by wanglin2** [comment]
已修复~
