### ISSUE TITLE
可以浏览器导入吗

### ISSUE THREAD

**Issue by wintsa123** [wanglin2/mind-map#372]
公司的一个oa系统，没有前端底层代码，只有ecode，前端的代码编辑器(不能安装npm包)

**Comment by Abir2230** [comment]
I love GitHub

**Comment by wanglin2** [comment]
没懂，如果是要能直接浏览器引入的文件，那么是有的，在https://github.com/wanglin2/mind-map/tree/main/simple-mind-map/dist
