### ISSUE TITLE
我在准备恢复数据时 思维导图在input框焦点上退格键用不了 其他快捷键是正常的

### ISSUE THREAD

**Issue by QinCongH** [wanglin2/mind-map#374]
我在准备恢复数据时 思维导图在input框焦点上退格键用不了 其他快捷键是正常的，希望作者解决
![image](https://github.com/wanglin2/mind-map/assets/79250644/3efeb909-fff9-442b-bcea-c0c5498f4e4f)

**Comment by wanglin2** [comment]
问题描述的不够清楚，我这边并不能复现
