### ISSUE TITLE
理想文档

### ISSUE THREAD

**Issue by kankanai** [wanglin2/mind-map#376]
![image](https://github.com/wanglin2/mind-map/assets/142068366/c61baacd-238e-4396-8340-3dae7e7211ca)
在您的github主页介绍里的网站看到有个理想文档，请问这个有计划开源吗？ 想把思维导图加个文件夹和列表展示，刚好发现理想文档有

**Comment by wanglin2** [comment]
这个暂时没有计划

**Comment by kankanai** [comment]
哦哦，好的，谢谢

**Comment by kankanai** [comment]
> 这个暂时没有计划


哦哦，好的，谢谢
