### ISSUE TITLE
Mac端放大时候，根节点未做中心锚定，会导致体验不佳

### ISSUE THREAD

**Issue by Expl4it** [wanglin2/mind-map#377]
Mac 端，版本0.70，通过触控板放大，或者右下角按钮放大的时候。如果根节点如果不在屏幕可是范围内的话，此时放大，很可能根节点和相关子节点就找不到位置了。

所以能否增加一个功能，在放大的时候，给根节点做一个屏幕中心锚定，防止不知道节点跑哪里去了。

**Comment by wanglin2** [comment]
这个没办法，建议这种情况使用鼠标放大，或者使用小地图，回到根节点等功能
