### ISSUE TITLE
导出图片时一直提示是否被浏览器拦截，但是新建文件后直接导出就没问题

### ISSUE THREAD

**Issue by feelingsa** [wanglin2/mind-map#382]
导出为背景透明图片提示是否被浏览器拦截，没有窗口弹出，但是新建文件后直接导出就没问题。

**Comment by wanglin2** [comment]
可能是你的数据有问题，方便的话可以把数据发一下

**Comment by feelingsa** [comment]
[Demon.zip](https://github.com/wanglin2/mind-map/files/13213917/Demon.zip)
选择保存为透明背景图片出错

**Comment by feelingsa** [comment]
[Demon.zip](https://github.com/wanglin2/mind-map/files/13213917/Demon.zip)
选择保存为透明背景图片出错

**Comment by wanglin2** [comment]
已修复，等待版本更新
