### ISSUE TITLE
节点数超过100时，在一个父节点下添加多个子节点时卡顿非常明显

### ISSUE THREAD

**Issue by girlinsouth** [wanglin2/mind-map#385]
节点数超过100时，在一个父节点下添加多个子节点时卡顿非常明显

**Comment by wanglin2** [comment]
麻烦提供一下demo，或者关键部分的代码截图

**Comment by girlinsouth** [comment]
this.mindMap = new MindMap({
        el: this.$refs.mindMapContainer,
        data: root,
        fit: false,
        enableShortcutOnlyWhenMouseInSvg: true,
        layout: layout,
        theme: theme.template,
        themeConfig: theme.config,
        viewData: view,
        nodeTextEditZIndex: 1000,
        textAutoWrapWidth: 300,
        nodeNoteTooltipZIndex: 1000,

        customHandleMousewheel: (e) => {
          that.mindMap.view.translateX(-e.deltaX)
          that.mindMap.view.translateY(-e.deltaY)
        },
        isUseCustomNodeContent: true,
        customCreateNodeContent: (node) => {
          // return你的自定义DOM节点
          const nodeData = node.nodeData.data;
          if (nodeData._docInfo) {
            let el = document.createElement('div')
            let Comp = Vue.extend(DocsNodeShow)
            let comp = new Comp({
              // props
              propsData: {
                nodeData: node.nodeData.data,
                mindMap: this.mindMap
              }
            });
            comp.$mount(el);
            return comp.$el;
          }
        },
        mousewheelMoveStep: 100,
        customNoteContentShow: {
          show: (content, left, top) => {
            this.$bus.$emit('showNoteContent', content, left, top)
          },
          hide: () => {
            // this.$bus.$emit('hideNoteContent')
          }
        },
        ...(config || {}),
        iconList: icon,
        useLeftKeySelectionRightKeyDrag: this.useLeftKeySelectionRightKeyDrag,
        customInnerElsAppendTo: null,
        enableAutoEnterTextEditWhenKeydown: false,
        customHandleClipboardText: handleClipboardText,
      })
