### ISSUE TITLE
鼠标不在画布上可以操作map吗

### ISSUE THREAD

**Issue by lithStudy** [wanglin2/mind-map#388]
请问在鼠标不在画布的情况，可以继续使用画布吗？比如鼠标移动到了浏览器的title上。这对于一些需要切换多个应用的场景，并通过快捷键快速激活思维导图画布的情况非常有用。

**Comment by wanglin2** [comment]
就是鼠标不在画布内，也想要快捷键是生效的？

**Comment by lithStudy** [comment]
> 就是鼠标不在画布内，也想要快捷键是生效的？

哦，是的，不过我刚刚已经找到了这个配置（enableShortcutOnlyWhenMouseInSvg）可以做到这个效果，感谢
