### ISSUE TITLE
当某父节点下的子节点为收起状态时，将该父节点移动到其他节点下时，只有父节点被移动过来，其子节点全部被删除（具体操作如下图）

### ISSUE THREAD

**Issue by huangyuanyin** [wanglin2/mind-map#39]
![image](https://user-images.githubusercontent.com/42410679/194795985-70d4c211-5c8f-4317-a5d2-f7e0174ec87e.png)
![image](https://user-images.githubusercontent.com/42410679/194796046-23b20340-1b1b-4010-8505-5a4571669caf.png)
![image](https://user-images.githubusercontent.com/42410679/194796120-a1fc6223-26ad-415f-9ce1-622b2f694ef2.png)

**Comment by huangyuanyin** [comment]
什么时候更新npm版本呀~~

**Comment by wanglin2** [comment]
已更新~

**Comment by huangyuanyin** [comment]
![image](https://user-images.githubusercontent.com/42410679/194979582-d701b47f-addc-4f78-9587-c7919f3f9a3a.png)

**Comment by wanglin2** [comment]
又更新了一个版本0.2.12，再安装试试

**Comment by wanglin2** [comment]
稍等有点问题， 我再发一个

**Comment by wanglin2** [comment]
0.2.13，试试看

**Comment by huangyuanyin** [comment]
![image](https://user-images.githubusercontent.com/42410679/194990051-1b69943d-e070-4e76-9827-6f1558c69092.png)

**Comment by wanglin2** [comment]
你是啥npm源，我试了官方的和淘宝的都安装成功了

**Comment by huangyuanyin** [comment]
![image](https://user-images.githubusercontent.com/42410679/194991236-4d3e99a6-3b94-4f67-8639-2ab60eb231cf.png)

**Comment by wanglin2** [comment]
官方源是这个吧https://registry.npmjs.org/
