### ISSUE TITLE
在safari浏览器中运行时，页面空白且控制台抛出异常：SyntaxError: Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by zhangXiaoMin007** [wanglin2/mind-map#391]
![iwEcAqNwbmcDAQTRCZYF0QUiBrBUn1GYgm-WXAU6uH6YwK0AB9IctvCSCAAJomltCgAL0gAFbgk png_720x720q90](https://github.com/wanglin2/mind-map/assets/28802707/5e996396-4dc9-47db-863e-6794780e87ff)

做了如下临时处理，可做参考：

![a3f5d7b6a12a63225e168b72da23fa9c91659060a14944da50304517e2473be8QzpcVXNlcnNcenhtaHpcQXBwRGF0YVxSb2FtaW5nXERpbmdUYWxrXDE2NTY4NzIxOV92MlxJbWFnZUZpbGVzXDE2OTkyNzEzNjA5ODZfOTlCNkFDRTEtRjEwMy00ZDExLUI1NzAtQjU1RUU0RUE3Q0IwLnBuZw==](https://github.com/wanglin2/mind-map/assets/28802707/50ffa40a-419d-47f8-87f5-7cce319f96f0)

**Comment by wanglin2** [comment]
已修改
