### ISSUE TITLE
使用最新的Chrome仍无法保存

### ISSUE THREAD

**Issue by gxandys** [wanglin2/mind-map#393]
部署的0.7版本，Chrome已更新为最新版本119.0.6045.106仍无法保存，提示：你的浏览器可能不支持，建议使用最新版本的Chrome浏览器。

**Comment by wanglin2** [comment]
需要https协议

**Comment by gxandys** [comment]
> 需要https协议

用了https直接打不开了，浏览器提示：此网站无法提供安全连接

**Comment by wanglin2** [comment]
那就是你的部署问题了

**Comment by gxandys** [comment]
![图片](https://github.com/wanglin2/mind-map/assets/52304029/8b69d197-0cfe-48eb-87b1-36fce5cf786e)
按照您开发文档中的部署一节的步骤操作，出这个错误

**Comment by wanglin2** [comment]
electron依赖没安装，自己安装一下好了

**Comment by gxandys** [comment]
装electron瞬间就报超时连接。运行serve又报新的错误。。。
放弃了，还是谢谢。
