### ISSUE TITLE
希望可以修改下双击事件，修改为可配置的，因为有些时候可能不需要双击的时候进行编辑

### ISSUE THREAD

**Issue by maPengFeier** [wanglin2/mind-map#395]

**Comment by wanglin2** [comment]
![image](https://github.com/wanglin2/mind-map/assets/17272433/443d580a-be48-46c0-9ace-54f0096fce15)

可以通过这个配置来禁止节点进入编辑

**Comment by maPengFeier** [comment]
我应该怎么设置呢？

**Comment by maPengFeier** [comment]
<template>
  <div class="mindMapDemo">
    <div :id="elId" class="mindMapContainer"></div>
  </div>
</template>

<script setup>
// 导入插件
import MindMap from "simple-mind-map";
import { nextTick, onMounted } from "vue";
const props = defineProps({
  // 元素id
  elId: {
    type: String,
    default: "mindMapContainer",
  },
  /**
   * 初始根节点的位置，可传一个数组，默认为['center', 'center'],代表根节点处于画布中心位置
   * 除了center，关键词还可以设置left、top、right、bottom
   * 数组的每项还可以传递一个数字，代表具体的像素，可以传递一个百分比字符串，比如['40%', '60%']
   * 代表水平位置在画布宽度的40%的位置，垂直位置在画布高度的60%的位置
   */
  initRootNodePosition: {
    type: Array,
    default: ["left", "center"],
  },
  /*
   * 是否只读 若改为只读，所有的操作事件都会失效
   */
  readonly: {
    type: Boolean,
    default: false,
  },
  /**
   * 开启鼠标双击复位思维导图位置及缩放
   */
  enableDblclickReset: {
    type: Boolean,
    default: true,
  },
  /**
   *布局类型，可选列表：
   logicalStructure（逻辑结构图）
   mindMap（思维导图）
   catalogOrganization（目录组织图）
   organizationStructure（组织结构图）
   timeline（v0.5.4+，时间轴）、
   timeline2（v0.5.4+，上下交替型时间轴）
   fishbone（v0.5.4+，鱼骨图）
   */
  layout: {
    type: String,
    default: "logicalStructure",
  },
  // 脑图数据
  mindData: {
    type: Object,
    default: () => {},
  },
  // 配置脑图的样式
  mindMapConfig: {
    type: Object,
    default: () => {},
  },
});
// 初始化脑图
let mindMap = null;
const emits = defineEmits([
  "mindMapNodeClick",
  "mindMapDrawClick",
  "mindMapScale",
]);
const initMindMap = () => {
  nextTick(() => {
    const el = document.getElementById(props.elId);
    mindMap = new MindMap({
      el,
      data: props.mindData,
      readonly: props.readonly,
      layout: props.layout,
      disableMouseWheelZoom: true,
      beforeTextEdit:null,
      initRootNodePosition: props.initRootNodePosition,
    });
    mindMap.setThemeConfig(props.mindMapConfig);
    // 节点的单击事件
    mindMap.on("node_click", (node) => {
      emits("mindMapNodeClick", node);
    });
    // 画布的单击事件
    mindMap.on("draw_click", (e) => {
      emits("mindMapDrawClick", e);
    });
    // 缩放事件
    mindMap.on("scale", () => {
      emits("mindMapScale");
    });
  });
};

onMounted(() => {
  initMindMap();
});
</script>

<style scoped lang="scss">
.mindMapDemo {
  width: 100%;
  height: 100%;
  position: relative;
  .mindMapContainer {
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100vh;
  }
}
</style>

**Comment by maPengFeier** [comment]
可以的，我设置好了

**Comment by Shasha6666** [comment]
更新，单独设置 beforeTextEdit:null不生效，写为函数的方式生效， beforeTextEdit: () => {
      return null
    },
