### ISSUE TITLE
是否可以添加配置禁用缩放

### ISSUE THREAD

**Issue by maPengFeier** [wanglin2/mind-map#396]

**Comment by wanglin2** [comment]
![image](https://github.com/wanglin2/mind-map/assets/17272433/13be57d4-d60d-4b1e-a278-afb6c27dc3b5)

**Comment by maPengFeier** [comment]
我使用手指缩放还是可以的，我没有用鼠标操作

**Comment by wanglin2** [comment]
那应该是漏了，后面会加上

**Comment by maPengFeier** [comment]
好的，感谢，期待更新

**Comment by wanglin2** [comment]
已支持，等待版本更新
