### ISSUE TITLE
根目录字数长的话，怎么换行展示，另外，根目录的线条可以该短吗？

### ISSUE THREAD

**Issue by maPengFeier** [wanglin2/mind-map#398]

**Comment by wanglin2** [comment]
文本自己换行就行了，xx\nxxx

**Comment by wanglin2** [comment]
![image](https://github.com/wanglin2/mind-map/assets/17272433/ab91ffb8-cab1-4eac-8f4f-ade34bace296)
可以试试修改主题的这个字段

**Comment by wanglin2** [comment]
https://github.com/wanglin2/mind-map/blob/main/simple-mind-map/src/themes/default.js#L78
