### ISSUE TITLE
添加同级目录的时候要求更改我新添加的目录名称而不是默认的名称，应该怎么操作

### ISSUE THREAD

**Issue by maPengFeier** [wanglin2/mind-map#401]

**Comment by wanglin2** [comment]
插入节点的命令有参数的，可以多尝试尝试

**Comment by maPengFeier** [comment]
/**
 * 插入兄弟节点
 * 完成后更新insertSiblingNode状态保证下次监听的值是初始值
 * 在父组件使用v-model:insertSiblingNode="insertSiblingNode"去更新
 */
const insertSiblingNode = () => {
  mindMap.execCommand("INSERT_NODE", {
    appointData: { text: "测试" },
  });
  emits("update:insertSiblingNode", false);
};   是这么设置的呀，但是没起作用
