### ISSUE TITLE
是否有办法能区分节点的新增、修改、删除事件呢？

### ISSUE THREAD

**Issue by girlinsouth** [wanglin2/mind-map#405]

**Comment by maPengFeier** [comment]
可以通过子组件的emits发射出去，然后去做判断
const insertSiblingNode = ({ data }) => {
  mindMap.execCommand("INSERT_NODE", false, [], { text: data.text });
  emits("handlerInsertSiblingNode");
};

**Comment by wanglin2** [comment]
要么像楼上说的，要么只能自己对比新旧两棵树
