### ISSUE TITLE
小地图关闭时，报错

### ISSUE THREAD

**Issue by huangyuanyin** [wanglin2/mind-map#41]
![image](https://user-images.githubusercontent.com/42410679/195035148-d1d41b69-f7d0-49a9-8424-267c15c062ec.png)
![image](https://user-images.githubusercontent.com/42410679/195036583-8d45d2f0-b739-4828-b2e2-e81ecf2e4c66.png)

**Comment by huangyuanyin** [comment]
如何默认打开小地图~

**Comment by wanglin2** [comment]
> 如何默认打开小地图~

在NavigatorToolbar.vue组件里把openMiniMap默认改成true就可以

**Comment by wanglin2** [comment]
> 如何默认打开小地图~

![image](https://user-images.githubusercontent.com/17272433/195068164-6f7d8f10-ae6d-45c4-9984-558f6b317d32.png)
