### ISSUE TITLE
node_active 事件 重复触发问题

### ISSUE THREAD

**Issue by zaizaidaxia** [wanglin2/mind-map#410]
在进行收起所有节点操作【UNEXPAND_ALL】时、node_active 事件 会被触发，触发次数与当前节点数一致。

在进行展开所有节点 【EXPAND_ALL 】时，node_active 事件 会被触发一次。

带来的问题：
当前激活节点数据不正确或为空。

**Comment by wanglin2** [comment]
已修改，等待下次更新，https://github.com/wanglin2/mind-map/commit/6fddfb5a855224547f1d02e2e53d4eb6d8caf022
