### ISSUE TITLE
溢出画布问题，我想从左上角开始但是溢出画布。可不可以变成滚动条

### ISSUE THREAD

**Issue by ytlwork** [wanglin2/mind-map#411]
![WechatIMG13274](https://github.com/wanglin2/mind-map/assets/151844049/49bb1abc-bfaf-4fbb-aa39-44d5a31fc054)

**Comment by ytlwork** [comment]
禁止拖拽禁止放大缩小，然后里面加个滚动条，应该就可以解决这个问题，这样的效果可以实现吗

**Comment by wanglin2** [comment]
有个滚动条插件，可以试试

**Comment by wanglin2** [comment]
文档翻翻
