### ISSUE TITLE
节点的宽度是否可以设置？

### ISSUE THREAD

**Issue by maPengFeier** [wanglin2/mind-map#414]

**Comment by wanglin2** [comment]
![image](https://github.com/wanglin2/mind-map/assets/17272433/35ce985f-9520-4654-8cfd-148391ab2673)

只有这个配置

**Comment by maPengFeier** [comment]
可以增加下控制节点宽高的配置吗？

**Comment by wanglin2** [comment]
那下个版本我看看

**Comment by maPengFeier** [comment]
好的，因为有些特殊情况还是会遇到这种的需求的，可以加到setThemeConfig方法里面去进行配置

**Comment by wanglin2** [comment]
这个功能实现太复杂了，短期应该不会考虑了
