### ISSUE TITLE
看我下面的图片，1、我设置了mousedown事件没起作用2、我在点击滚动条的时候很容易就选中了画布里面的字

### ISSUE THREAD

**Issue by maPengFeier** [wanglin2/mind-map#419]
![Uploading WechatIMG44932.png…]()
![Uploading WechatIMG44933.png…]()

**Comment by maPengFeier** [comment]
<img width="802" alt="WechatIMG44932" src="https://github.com/wanglin2/mind-map/assets/69794137/a1fb5279-00f5-4599-b7d1-9a97c2aa6289">
<img width="1067" alt="WechatIMG44933" src="https://github.com/wanglin2/mind-map/assets/69794137/3bd0c164-2424-434d-897d-2c424f850a2c">

**Comment by wanglin2** [comment]
这种问题你得自己想办法解决，不能指望我来帮你
