### ISSUE TITLE
一个严重的bug，极其影响操作

### ISSUE THREAD

**Issue by zhangzhonglin528** [wanglin2/mind-map#423]
按住ctrl时，缩放和不按是反的，这样子就经常导致误操作把导图放的很大或者很小，up主可以改改这个问题吗？因为目前其他的所有的思维导图的操作都跟你的思维导图是相反的，这样子来操作这个的时候就感觉不符合基本操作

**Comment by zengfanfan** [comment]
现在上滚缩小下滚放大，反直觉啊，不好用，建议改成上滚放大

**Comment by maPengFeier** [comment]
附议

**Comment by wanglin2** [comment]
> 现在上滚缩小下滚放大，反直觉啊，不好用，建议改成上滚放大

这个可以设置

![image](https://github.com/wanglin2/mind-map/assets/17272433/834b09cd-31db-4c18-a0cc-a03ee41789fd)

**Comment by wanglin2** [comment]
已修改，等待版本更新
