### ISSUE TITLE
How can I drag node without tree root? 

### ISSUE THREAD

**Issue by quyphuc2111** [wanglin2/mind-map#426]
Preview Image:
![Screenshot 2023-11-27 101844](https://github.com/wanglin2/mind-map/assets/58882661/71c60452-ce64-452d-b4fa-b9ad17844b24)

Thank you, sir!

**Comment by wanglin2** [comment]
I don't quite understand what you mean. Currently, the node cannot detach from the root node

**Comment by quyphuc2111** [comment]
@wanglin2 Can I do that ? Can you give me some ideas ? Thank you!!

**Comment by wanglin2** [comment]
Sorry, this library currently does not support free nodes
