### ISSUE TITLE
在鼠标滚动缩放画布后，快捷键失效

### ISSUE THREAD

**Issue by d3wolf** [wanglin2/mind-map#430]
这个问题提的人不多，与浏览器版本有关系吗
chrome 119.0.6045.161

**Comment by wanglin2** [comment]
在线demo上能复现吗，具体的操作步骤是怎样的

**Comment by d3wolf** [comment]
![demo](https://github.com/wanglin2/mind-map/assets/12440562/5cb47c91-9556-4da4-94cb-1c0a55461692)
