### ISSUE TITLE
按tab键或enter键等快捷键不进入编辑模式而任意无限插入节点

### ISSUE THREAD

**Issue by chansiyan** [wanglin2/mind-map#436]
在按tab插入下降节点或enter插入同级节点时（目的是想一次性插入多个节点来搭建思维导图框架）,要多按一次快捷键退出编辑模式，之后才能创建下一个节点，能否参考mindmaster或者xmind，按tab键或enter键不进入编辑模式而任意无限插入节点

**Comment by wanglin2** [comment]
增加了一个配置
![image](https://github.com/wanglin2/mind-map/assets/17272433/c21a4e95-46af-44d9-b344-e6da00bdbe4a)


等待下个版本更新

**Comment by chansiyan** [comment]
非常感谢，反应非常迅速，为作者大大点赞！！
虽然已经接近了mindmaster和xmind了，但是还有一点差别，
就是在编辑模式下能否一步实现  退出编辑模式并创建  同级、下级、上级节点。
SimpleMindMap好像是在编辑时默认tab和enter是退出编辑模式，然后才可以创建节点！
但是mindmaster在编辑模式按tab也能创建下级节点，不知道这个功能实现的难度大不大；
这样相当于一步实现退出编辑并创建下级节点，提高了使用效率，而不用按tab或enter键退出编辑模式，再按tab键创建下一级节点

同理，想不退出编辑模式情况下创建同级节点的貌似不好实现，但是mindmater有快捷键可以实现类似的功能
既： “复制当前激活节点到同级节点上一个（下一个）”共两套快捷键 ，这个快捷键复制当前 激活和编辑状态 的节点到同级节点上一个（下一个）。
一步实现 退出编辑模式并创建  上级节点的快捷键暂时没在mindmaster中找到
假如能实现这个功能真是杀手级的存在，绝对秒杀市面上的一众思维导图应用！！！

**Comment by wanglin2** [comment]
目前先这样把，我觉得多按一次按键效率应该也不会差挺多
