### ISSUE TITLE
建议：仓库体积过大问题

### ISSUE THREAD

**Issue by qisuwan** [wanglin2/mind-map#443]
我在拉去仓库时，拉去有点困难，很缓慢，最终看了下大小，400M
![image](https://github.com/wanglin2/mind-map/assets/39648761/48cf911f-043a-4c9e-ac76-5765b78c61cf)

应该是之前有推送过大文件，应该是build后的产物，之前自己有遇到过，分析看了下最大的前20个文件，确实是，建议大佬有时间的时候整理下，一般build的产物就不要上传的仓库了，不然仓库就会越来越大，难以拉取
![image](https://github.com/wanglin2/mind-map/assets/39648761/f220323f-38b2-42d0-85d4-4102671af789)

**Comment by wanglin2** [comment]
大佬你出现的太晚了，现在我自己都拉不下来了，
![image](https://github.com/wanglin2/mind-map/assets/17272433/36fb239b-da2d-4efb-93cb-4dc04160f422)
报这个错，试了修改配置，git config --global http.postBuffer 524288000，也不行，大佬知道如何解决吗

**Comment by wanglin2** [comment]
已删除历史文件中的exe文件记录

**Comment by wanglin2** [comment]
1.统计大小

git count-objects -v

2.显示当前最大的10个文件

git verify-pack -v .git/objects/pack/pack-*.idx | sort -k 3 -g | tail -10

3.根据ID 反查文件名

git rev-list --objects --all |grep  【id】

4.根据文件名在历史记录中批量删除

指定某个文件

git filter-branch --force --index-filter 'git rm --cached --ignore-unmatch 【文件名】’ --prune-empty --tag-name-filter cat -- --all

通配符

git filter-branch --force --index-filter 'git rm --cached --ignore-unmatch */*/*.exe' --prune-empty --tag-name-filter cat -- --all

文件名带空格

git filter-branch --force --index-filter  "git rm --cached --ignore-unmatch ‘【文件名】’”  --prune-empty --tag-name-filter cat -- --all

5.更新本地Git仓库

rm -rf .git/refs/original/;git reflog expire --expire=now --all;git gc --prune=now;git gc --aggressive --prune=now

6.更新到远程服务器

git push origin --force --all
git push origin --force --tags

**Comment by qisuwan** [comment]
^V^，我拉的时候也遇到了，是因为仓库太大，在连接github的时候如果网络不好就会中断，多拉几次可以拉下来的，网上有很多解决方案，我可以搜索一下，找适合你自己的

**Comment by qisuwan** [comment]
这是我参考的：https://help.gitee.com/repository/base/%E4%BB%93%E5%BA%93%E4%BD%93%E7%A7%AF%E8%BF%87%E5%A4%A7%EF%BC%8C%E5%A6%82%E4%BD%95%E5%87%8F%E5%B0%8F
