### ISSUE TITLE
配置水印、自定义节点内容失败

### ISSUE THREAD

**Issue by MoJingYan** [wanglin2/mind-map#448]
1. 配置水印失败
     ![image](https://github.com/wanglin2/mind-map/assets/61170204/caee2568-44f7-480e-a67b-19f85575f541)
     代码如上。
     效果如图
     ![image](https://github.com/wanglin2/mind-map/assets/61170204/5b307f19-24bb-492c-ac58-b478cc4df876)
     确实看不到水印

2. 自定义节点失败：
    当 customCreateNodeContent : null 正常， 但 ()=> { return null } 就会报错 ，文档说返回null可以。
    错误如图
    ![image](https://github.com/wanglin2/mind-map/assets/61170204/6822e8b6-c892-4b16-99de-daa323fd1b23)

**Comment by wanglin2** [comment]
水印请先确认是否注册了水印插件

**Comment by MoJingYan** [comment]
> 水印请先确认是否注册了水印插件
抱歉抱歉，文档阅读疏忽！ 感谢！

**Comment by wanglin2** [comment]
自定义节点失败：

这个是bug，下个版本会修复

**Comment by wanglin2** [comment]
> 自定义节点失败：
> 
> 这个是bug，下个版本会修复

已修复，可以更新到0.9.1-fix.1版本
