### ISSUE TITLE
如何修改快捷键，比如我想把上移节点的快捷键修改为ALT + ↑

### ISSUE THREAD

**Issue by huangyuanyin** [wanglin2/mind-map#45]
![image](https://user-images.githubusercontent.com/42410679/196152052-0da30949-0ddd-4666-8f6f-d1cbfd2469b6.png)

**Comment by wanglin2** [comment]
可以参考这个文件：https://github.com/wanglin2/mind-map/blob/main/web/src/pages/Edit/components/Contextmenu.vue#L141
注册一个新的快捷键，键名可以参考这里：https://github.com/wanglin2/mind-map/blob/main/simple-mind-map/src/utils/keyMap.js，命令函数可以在这里找：https://github.com/wanglin2/mind-map/blob/main/simple-mind-map/src/Render.js#L230
示例：
this.mindMap.keyCommand.addShortcut('Alt+Up', () => {
this.mindMap.execCommand('UP_NODE')
});
