### ISSUE TITLE
能自定义快捷键吗

### ISSUE THREAD

**Issue by ssegsadd** [wanglin2/mind-map#454]
在编辑内容时想删除几个字，结果把这个节点删了

**Comment by wanglin2** [comment]
问题描述的不够清楚，什么情况下会删除文字把节点删了呢，自定义快捷键具体是要自定义什么快捷键呢，另外你是开发者还是使用者

**Comment by ssegsadd** [comment]
我是使用者。刚开始使用的时候遇到了长按删除键时，将框内文字删完后把这个节点删了。不过现在新建一个文件没再触发这个现象
