### ISSUE TITLE
error when customCreateNodeContent return null

### ISSUE THREAD

**Issue by redgrandfa** [wanglin2/mind-map#456]
In dist directory,
when I write below config
```
isUseCustomNodeContent: true,
customCreateNodeContent: (node) => {
      return null;
},
```
it  follows the guide in doc :

> customCreateNodeContent方法需要返回DOM节点，如果某个节点你不想自定义，那么可以返回null，那么还是会走内置的节点渲染逻辑。

Then I have an error in a chunk js file , 

`createNodeData(){ 
     ...
     this._customNodeContent.setAttribute("xmlns","http://www.w3.org/1999/xhtml"))
     ...
} `

this._customNodeContent will be null , 
Error : Cannot read properties of null.

**Comment by wanglin2** [comment]
Fixed and can be updated to version 0.9.1 fix. 1
