### ISSUE TITLE
有人能给我一个人Nginx配置文件么，现在他说不支持保存

### ISSUE THREAD

**Issue by MilkTeaNo7** [wanglin2/mind-map#457]
我的需求很简单，配置再内网，访问IP+8080可以出现页面正常使用
下面是我的配置
```
server {
        listen 8080;
        server_name  https://localhost;

        location / {
        root   /SimpleMindMap/;
        index  index.html index.htm;
        }
}
```
但是他提示我保存的时候浏览器不支持，或者非http协议？

我晕

**Comment by wanglin2** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/API/File_System_API#%E6%A6%82%E5%BF%B5%E4%B8%8E%E7%94%A8%E6%B3%95

用的是这个特性，浏览器能支持，且是https协议应该就可以
