### ISSUE TITLE
导入功能覆盖当前思维导图无法恢复

### ISSUE THREAD

**Issue by 021gink** [wanglin2/mind-map#462]
版本：0.9.0
问题：首先创建了一个新的思维导图并命名，以smm格式保存。
之后在当前思维导图状态下，导入过去的导图，能够显示过去导图内容，未点击保存，结果当前导图被完全覆盖，变成过去导图内容。。。

**Comment by wanglin2** [comment]
客户端？

**Comment by 021gink** [comment]
> 客户端？
![screenshot20231214](https://github.com/wanglin2/mind-map/assets/134119039/795b3545-9085-4caf-990f-0254cee7374f)
就是这个。

**Comment by wanglin2** [comment]
这个功能就是这样的，导入会覆盖且回不到之前
