### ISSUE TITLE
is it possible to inport content from excel file?

### ISSUE THREAD

**Issue by diwakaran1dan** [wanglin2/mind-map#47]
Hi @wanglin2 sir, is it possible to import the mindmap data using an excel file?
it will be useful to edit data in the user-preferred method (most users will use excel files to collect mindmap data). so if there is an option to import data using an excel file it will be useful for most users

![image](https://user-images.githubusercontent.com/42892061/196604050-4e1896ab-92f1-4198-864e-822742feb0b3.png)

**Comment by diwakaran1dan** [comment]
The output
![image](https://user-images.githubusercontent.com/42892061/197335338-1348b31c-905b-4c45-8ef5-6ee31e17a43e.png)

**Comment by diwakaran1dan** [comment]
And one small suggestion: sidebar container appear behind the toolbar container; it is hard to see the sidebar container in a smaller display 

![image](https://user-images.githubusercontent.com/42892061/197335485-b67a918f-89f9-46b2-b5b0-91859f55c044.png)

**Comment by wanglin2** [comment]
hello，now you can import from excel，and also fit small screen

**Comment by diwakaran1dan** [comment]
@wanglin2  works perfectly sir
