### ISSUE TITLE
mac上图标错位

### ISSUE THREAD

**Issue by ijry** [wanglin2/mind-map#475]
<img width="690" alt="image" src="https://github.com/wanglin2/mind-map/assets/3102798/6178dcd6-bfc4-44e0-b288-0208847d9ce0">

**Comment by wanglin2** [comment]
这是怎么出现的，在线demo里能复现？

**Comment by ijry** [comment]
> 这是怎么出现的，在线demo里能复现？

demo就是这样

**Comment by wanglin2** [comment]
safari浏览器，版本17.2

**Comment by wanglin2** [comment]
浏览器兼容性问题统一汇总到：https://github.com/wanglin2/mind-map/issues/503
