### ISSUE TITLE
在选中的节点粘贴图片是否支持上传服务器

### ISSUE THREAD

**Issue by yangda666** [wanglin2/mind-map#483]
在选中的节点粘贴图片是否支持上传服务器或者有什么吗解决方法

**Comment by wanglin2** [comment]
添加了handleNodePasteImg实例化选项来处理粘贴的图片，等待下个版本更新，https://github.com/wanglin2/mind-map/commit/bac174c8dfbea3dd08f9b1fdfce584480e363be3
