### ISSUE TITLE
[优化建议]进入编辑框后光标容易误移出编辑框导致编辑态消失

### ISSUE THREAD

**Issue by HongFei1998** [wanglin2/mind-map#488]
如题，当双击节点进入文本编辑时候，去选中文本，比较经常的会误移动光标到编辑框范围之外，这个时候就会退出编辑态，是否可以优化在文本编辑态下鼠标选中文字移出编辑框外也不退出编辑仍保持文本选中？

**Comment by wanglin2** [comment]
已修复，等待版本更新，https://github.com/wanglin2/mind-map/commit/9db988e3ec3cf8a48d0d1774790e7655a236d583
