### ISSUE TITLE
建议：浮动节点，翻译优化

### ISSUE THREAD

**Issue by GothLab** [wanglin2/mind-map#49]
对不起，我正在使用翻译器可能造成的误解。

非常感谢您提供如此丰富而复杂的免费工具，喜欢它。

作为可能的实现要建议浮动节点。能够将它们从树中分离出来，这使得开发思维导图非常有用。

此外，正在努力翻译它。如果 div 中的所有文本都在标签中而不是空的，那将非常有帮助。< span >  或者也许将所有单词包装到单独的字典中。如果您打算使其翻译友好。

非常感谢。

**Comment by GothLab** [comment]
抱歉，刚刚意识到线宽 0 基本上是浮动节点。

作为建议，可能可以在右键菜单中。

**Comment by wanglin2** [comment]
真正的自由节点在设计之初其实没有打算支持，但是你说的线宽为0就相当于自由节点的想法非常棒，后续会在右键菜单添加一个按钮，另外后续也会增加多语言的支持~

**Comment by GothLab** [comment]
你好！
感谢您的更新，尝试翻译是一种解脱，您已完成。
https://gothlab.github.io/Obsidian-Mindmap-Canvas/
我正在尝试根据您的工作制作一个黑曜石思维导图插件。

进行了几处更改，主要是视觉上的。也许你会发现它们对 master 分支很有用。
![2022-11-10 18_51_37-A simple web mind map implementation](https://user-images.githubusercontent.com/53623054/201149110-9c1fcd75-f96a-4d7d-9db3-8d584e94b307.png)
![2022-11-10 18_51_49-](https://user-images.githubusercontent.com/53623054/201149191-a052e745-4115-4cc8-8646-26941e4d06ff.png)

1) 暗模式 css
2）试图缩小用户界面。
2.1) 工具栏文本到标题属性。悬停时显示。 （也许工具提示会更好）
3) Note 选项卡是一个带有滚动条的容器。边距 -20 + 悬停时可见。
4) 如果你在 href ?mapname=x 之后输入
 其中 x 是任何名称。它将在 LocalStorage 中创建一个新实例，并在您下次访问时加载它。

我的 Multi-map 实现和 CSS 可能很糟糕而且很脏，但仍然如此。
我想再次说声谢谢。出色的工作。

想建议：
1) 使用键盘箭头导航。所以我不使用鼠标回到master分支。
2）添加触发器以禁用自动样式侧边栏打开器。

干杯！

**Comment by wanglin2** [comment]
感谢你提供了这么多非常棒的建议！
