### ISSUE TITLE
[优化建议]当前默认maxHistoryCount: 1000，可能占用大量内存

### ISSUE THREAD

**Issue by HongFei1998** [wanglin2/mind-map#490]
// 最大历史记录数
  maxHistoryCount: 1000,
当前历史记录默认 1000，如果页面内容有图片或者怎么样，会占用大量内存，建议把默认值调小

**Comment by wanglin2** [comment]
已调整为500，等待版本更新，https://github.com/wanglin2/mind-map/commit/06ad8cfbf65830f9ac64726cae22bfa0cce3055f
