### ISSUE TITLE
公式功能无法使用

### ISSUE THREAD

**Issue by sumruler** [wanglin2/mind-map#492]
![截图_20231224150810](https://github.com/wanglin2/mind-map/assets/56953545/cab4e046-bb34-4e88-8f83-f5b80b1a521d)
输入公式的时候出现这样的错误，请问如何解决呢？

**Comment by wanglin2** [comment]
已修复，等待版本更新，https://github.com/wanglin2/mind-map/commit/69a97d44bc7293a1bb17d61487babb9f804a65f5
