### ISSUE TITLE
使用动态引入依赖

### ISSUE THREAD

**Issue by ijry** [wanglin2/mind-map#496]
jsPDF/ketex等插件使用import()动态导入增快首屏加载速度。

**Comment by wanglin2** [comment]
插件化就是为了按需引入减小打包体积，某个插件不需要不要引入就行了，如果是用了打包后的文件，那对文件大小敏感的可以自己构建，可以参考这个：http://localhost:8080/#/doc/zh/start/%E5%BC%80%E5%8F%91。
如果想异步加载和注册插件可以这么做：
import('simple-mind-map/src/plugins/Export.js').then(res => {
        mindMap.addPlugin(res.default)
})
