### ISSUE TITLE
如果在ToolBar 上面有一些文章列表， 想拖拽一段文字 插入到一个节点上， 要如何实现， 希望给些提示

### ISSUE THREAD

**Issue by alex9968** [wanglin2/mind-map#5]

**Comment by wanglin2** [comment]
给文章列表元素绑定h5拖拽事件，在拖拽结束事件dragend里计算是否拖拽到了某个节点之上，是的话就调用该节点的setText(text)方法来将节点的文本设置为文章的标题，遍历元素及位置判断可以参考代码：https://github.com/wanglin2/mind-map/blob/main/simple-mind-map/src/Select.js#L150
