### ISSUE TITLE
Is it possible to Move connectors Lines in user preferred manner?

### ISSUE THREAD

**Issue by diwakaran1dan** [wanglin2/mind-map#50]
Hi, @wanglin2 is it possible to add a menu item while editing the nodes as mentioned in the first image? [it will be handy for the users to use or edit URLs/image/text styling in the nodes]
![image](https://user-images.githubusercontent.com/42892061/198881668-6974356a-f81e-4215-9ec1-b15e2a37c05b.png)
![image](https://user-images.githubusercontent.com/42892061/198882254-80e0ff04-0813-4601-b9c4-b53401c8174f.png)
-------------
Suggestion: moving the connector lines for the nodes in user preferred location, [this will improve the users to adjust the look/style of the mind map]
![image](https://user-images.githubusercontent.com/42892061/198881694-c8c46fe7-fee9-4da1-b734-046604f72da4.png)
-------------
URLs in the nodes not accessible in pdf export 
![image](https://user-images.githubusercontent.com/42892061/198881978-8d59d9d8-1141-472a-b3ec-0fa4161efce8.png)
-------------
Suggestion: Adding sub-nodes at the top and bottom of the root nodes [this will helps the user to build the mind map more compactly]
![image](https://user-images.githubusercontent.com/42892061/198882184-0cc93b91-3be9-4c45-aad0-e2108a8eab93.png)
-------------
Suggestion: Adding node editing option in 大纲 section
![image](https://user-images.githubusercontent.com/42892061/198882382-864196bc-7a41-4683-b929-0edf84bbc250.png)
-------------

**Comment by wanglin2** [comment]
Hello, suggestions 1 and 4 have been implemented, others are not considered or cannot be implemented
