### ISSUE TITLE
请求可以增加节点操作相关事件

### ISSUE THREAD

**Issue by lointain** [wanglin2/mind-map#505]
例如
1. 节点删除
2. 节点添加
3. 节点移动

**Comment by wanglin2** [comment]
这个不太好加，不过新增了节点数据更新的明细事件，可以获取更新、删除、添加的节点数据，下个版本更新了可以试试。https://github.com/wanglin2/mind-map/commit/541606b2eb891a031231c8ddc0cb926c0878910d
