### ISSUE TITLE
适配微前端框架

### ISSUE THREAD

**Issue by HappyYang233** [wanglin2/mind-map#507]
目前很多的微前端框架比如qiankun、wujie等都使用了沙箱的模式，即在加载子应用时代理window对象，mind-map在new MouseEvent对象时，构造参数view的值为window,但在子应用中取得的window为proxy对象，导致构造失败，目前echarts也出现过了类似的问题，但echarts将view的值修改为了document.defaultView，所以作者是否考虑兼容一下qiankun等微前端框架
<img width="352" alt="image" src="https://github.com/wanglin2/mind-map/assets/31692772/b8f71a5c-4951-4aae-a6c7-ac84582b4224">

**Comment by wanglin2** [comment]
已修改，等待版本更新

**Comment by HappyYang233** [comment]
> 已修改，等待版本更新

预计多久发版呢，项目组在等待使用。

**Comment by wanglin2** [comment]
这个不确定，可能得下周，急的话你可以先自己修改一下TouchEvent插件，本身插件就是一个类，也不一定非要引入库内置的，你项目里创建一个文件也可以注册的
