### ISSUE TITLE
结构问题

### ISSUE THREAD

**Issue by ytlwork** [wanglin2/mind-map#509]
逻辑结构图，添加三个子节点默认是上下居中的，可不可以做到图片这种效果
![Uploading WechatIMG17568.jpeg…]()

**Comment by ytlwork** [comment]
![WechatIMG17568](https://github.com/wanglin2/mind-map/assets/151844049/1739461b-22b7-4373-8f7b-40e62a2af6a9)

**Comment by wanglin2** [comment]
默认肯定是不行的，如果你自己修改布局算法，那可能可以
