### ISSUE TITLE
节点中带有公式的时候，大纲中公式文本会出现两次

### ISSUE THREAD

**Issue by sumruler** [wanglin2/mind-map#516]
不知道是bug还是特性，如图所示，大纲视图中节点文本中的公式会以不同的形式出现两次：
![Clip_2024-01-10_16-25-45](https://github.com/wanglin2/mind-map/assets/56953545/55fbc4ac-2333-4172-a117-a3ff1d509bb8)

**Comment by wanglin2** [comment]
大纲里去掉了公式的显示，等待下个版本更新等待下个版本更新
