### ISSUE TITLE
mac 在useLeftKeySelectionRightKeyDrag为true 时无法多选节点

### ISSUE THREAD

**Issue by yangda666** [wanglin2/mind-map#517]

**Comment by wanglin2** [comment]
鼠标还是键盘

**Comment by yangda666** [comment]
测试发现mac 电脑点击节点后 会触发clearActiveNodeListOnDrawClick这个函数this.clearActiveNodeListOnDrawClick(e, 'contextmenu')

**Comment by yangda666** [comment]
老板这是不是很棘手

**Comment by wanglin2** [comment]
还没看呢

**Comment by yangda666** [comment]
![Uploading image.png…]()

**Comment by yangda666** [comment]
//  鼠标右键菜单事件
  onContextmenu(e) {
    e.preventDefault()
    // 适配mac ctrl + 鼠标右键 不做反应
    if (e.ctrlKey) {
      return
    }
    this.emit('contextmenu', e)
  } 我这样改应该没啥问题吧

**Comment by wanglin2** [comment]
没问题，你改的是对的，下个版本会修复
