### ISSUE TITLE
直线类型的线条能否增加圆角配置呢？

### ISSUE THREAD

**Issue by ldongrui** [wanglin2/mind-map#518]
![微信图片_20240111135029](https://github.com/wanglin2/mind-map/assets/108853892/e1ec4269-5cd2-4c58-bd65-124b20a9d002)
线条选择直线的情况下，节点之间的线条能否增加圆角的效果呢？类似css的border-radius属性

**Comment by wanglin2** [comment]
主题中增加了lineRadius属性控制圆角大小，等待0.9.4版本更新
