### ISSUE TITLE
关于更换线性后主题就会被重置的bug

### ISSUE THREAD

**Issue by sumruler** [wanglin2/mind-map#519]
我又发现了一个bug，你应用一个主题后，然后更换线性，主题就被重置了，如图
![更换线形主题就会重置的bug](https://github.com/wanglin2/mind-map/assets/56953545/cc6ff94d-df61-4a8a-bf0b-2fa9a9970331)

**Comment by wanglin2** [comment]
在线demo能复现么，可以的话具体的操作步骤可以描述一下

**Comment by sumruler** [comment]
> 在线demo能复现么，可以的话具体的操作步骤可以描述一下
现在好像没有这个bug了，我刚刚试用以前的步骤复现，发现现在已经不存在这个问题了
