### ISSUE TITLE
关于节点设置概要的BUG

### ISSUE THREAD

**Issue by xiaoyiv** [wanglin2/mind-map#520]
当选择部分节点设置概要，可以设置，但是当收拢节点，再次展开，概要就消失失效了，给一个节点整体设置概要，则没有这个问题。具体见视频。

![动画](https://github.com/wanglin2/mind-map/assets/33823367/4959e209-ec86-4e40-88e4-d6ed8cf8a383)

**Comment by yi-ge** [comment]
亲测，此问题确实存在。除此之外，部分节点收起的情况下添加概要，会导致出现多级概要。

**Comment by wanglin2** [comment]
> 亲测，此问题确实存在。除此之外，部分节点收起的情况下添加概要，会导致出现多级概要。

这个问题具体怎么复现呢

**Comment by wanglin2** [comment]
> 当选择部分节点设置概要，可以设置，但是当收拢节点，再次展开，概要就消失失效了，给一个节点整体设置概要，则没有这个问题。具体见视频。
> 
> ![动画](https://private-user-images.githubusercontent.com/33823367/296544948-4959e209-ec86-4e40-88e4-d6ed8cf8a383.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTA3NDUsIm5iZiI6MTcwNTMxMDQ0NSwicGF0aCI6Ii8zMzgyMzM2Ny8yOTY1NDQ5NDgtNDk1OWUyMDktZWM4Ni00ZTQwLTg4ZTQtZDZlZDhjZjhhMzgzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA5MjA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1M2I4MzhlYmE5N2YxMmZjYWIwNGYxZWJhOGZjYThkYTY0ZGJhYzhlM2I5YjRkOTU5MzdjMzMyOTMwZDY3YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mXPghJBW0R30jeqVTwXiME8IUEpcvJZYLA4LoD03_14) [ ![动画](https://private-user-images.githubusercontent.com/33823367/296544948-4959e209-ec86-4e40-88e4-d6ed8cf8a383.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTA3NDUsIm5iZiI6MTcwNTMxMDQ0NSwicGF0aCI6Ii8zMzgyMzM2Ny8yOTY1NDQ5NDgtNDk1OWUyMDktZWM4Ni00ZTQwLTg4ZTQtZDZlZDhjZjhhMzgzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA5MjA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1M2I4MzhlYmE5N2YxMmZjYWIwNGYxZWJhOGZjYThkYTY0ZGJhYzhlM2I5YjRkOTU5MzdjMzMyOTMwZDY3YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mXPghJBW0R30jeqVTwXiME8IUEpcvJZYLA4LoD03_14) ](https://private-user-images.githubusercontent.com/33823367/296544948-4959e209-ec86-4e40-88e4-d6ed8cf8a383.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTA3NDUsIm5iZiI6MTcwNTMxMDQ0NSwicGF0aCI6Ii8zMzgyMzM2Ny8yOTY1NDQ5NDgtNDk1OWUyMDktZWM4Ni00ZTQwLTg4ZTQtZDZlZDhjZjhhMzgzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA5MjA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1M2I4MzhlYmE5N2YxMmZjYWIwNGYxZWJhOGZjYThkYTY0ZGJhYzhlM2I5YjRkOTU5MzdjMzMyOTMwZDY3YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mXPghJBW0R30jeqVTwXiME8IUEpcvJZYLA4LoD03_14) [ ](https://private-user-images.githubusercontent.com/33823367/296544948-4959e209-ec86-4e40-88e4-d6ed8cf8a383.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTA3NDUsIm5iZiI6MTcwNTMxMDQ0NSwicGF0aCI6Ii8zMzgyMzM2Ny8yOTY1NDQ5NDgtNDk1OWUyMDktZWM4Ni00ZTQwLTg4ZTQtZDZlZDhjZjhhMzgzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA5MjA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1M2I4MzhlYmE5N2YxMmZjYWIwNGYxZWJhOGZjYThkYTY0ZGJhYzhlM2I5YjRkOTU5MzdjMzMyOTMwZDY3YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mXPghJBW0R30jeqVTwXiME8IUEpcvJZYLA4LoD03_14)

已修复，等待下个版本更新
