### ISSUE TITLE
手机端浏览器的导出有问题，生成的文件名是一串随机字母英文，而且没有后缀。（除了图片有后缀）

### ISSUE THREAD

**Issue by Menzor-future** [wanglin2/mind-map#521]
开发者你好，手机端浏览器的导出有问题：生成的文件名是一串随机字母英文，而且没有后缀。（除了图片有后缀）

**Comment by Menzor-future** [comment]
而且导出弹窗界面有点大
![385c958bb4ef2a9cb4d07ae4ab4049a](https://github.com/wanglin2/mind-map/assets/54103707/f100d22c-b97b-4c3e-a480-715e5dd1900f)

**Comment by wanglin2** [comment]
浏览器兼容问题统一汇总到：https://github.com/wanglin2/mind-map/issues/503#issuecomment-1893391282

**Comment by wanglin2** [comment]
弹窗可以适配一下，导出为什么不行不一定能改

**Comment by Menzor-future** [comment]
> 弹窗可以适配一下，导出为什么不行不一定能改

导出问题是我这边的问题，只有 via 浏览器不行。
