### ISSUE TITLE
mindmap非常棒，如果可以嵌入Obsidian就更棒了！

### ISSUE THREAD

**Issue by yonghsuan** [wanglin2/mind-map#522]
是否有Obsidian的相关插件，可以直接嵌入smm格式的思维导图，并在obsidian中显示？如果可以做到的话，那就太赞了！非常感谢你们可以开发如此棒的开源软件！

**Comment by yonghsuan** [comment]
其次无法使用大纲模式下进行编辑，然后思维导图自动生成。而是只能点击图形按钮，然后才能在大纲模式下修改，能否支持大纲模式下构建思维导图了？

**Comment by wanglin2** [comment]
有人做了个插件，https://github.com/wanglin2/mind-map/issues/350

**Comment by wanglin2** [comment]
大纲里可以通过enter键创建兄弟节点，tab键创建子节点
