### ISSUE TITLE
节点边框形状，可否增加横线样式

### ISSUE THREAD

**Issue by oran176** [wanglin2/mind-map#53]
![2](https://user-images.githubusercontent.com/8391784/210054303-9dbfa233-a573-49e9-8c9b-d52ec4daf818.png)
如是图所示，最后一个节点层级，想设置为下面的横线样式。
![1](https://user-images.githubusercontent.com/8391784/210054356-4431ec18-94a4-4d06-9182-90457fb43598.png)

**Comment by wanglin2** [comment]
已支持，可以试试
![image](https://user-images.githubusercontent.com/17272433/210734248-c34de999-4c48-43b8-8b5d-52a558b84870.png)
