### ISSUE TITLE
Mac触控板的放大、缩小、移动都有点飘

### ISSUE THREAD

**Issue by keventseng** [wanglin2/mind-map#533]
RT：Mac触控板的放大、缩小、移动都有点飘

**Comment by pang-xf** [comment]
一样的问题 有解决方案吗

**Comment by xyhuangjia** [comment]
感觉是蓝牙鼠标在mac上通病

**Comment by ZhangMingZhao1** [comment]
#829

**Comment by Tarrency** [comment]
看了一下源码，判断是否是触控板的时候，监听了wheel事件的wheelDeltaY属性（Y轴滚动量）来区分鼠标和触控板行为。一般而言鼠标一次滚动130左右，触控板在10以内。但是这个参数在MDN上已经弃用了，wheelDeltaY目前对于鼠标和触控板的一次滚动行为都是130左右，因此无法区分鼠标和触控板行为。目前wheel事件使用deltaY来替代wheelDeltaY属性，用deltaY来区分即可，10以内判断为触控板行为应该就可以了。
![image](https://github.com/user-attachments/assets/117bb18f-cdad-4f38-98ff-f8675454aa91)
<img width="735" alt="image" src="https://github.com/user-attachments/assets/86c57038-16f8-4668-b65d-b0993a6c74c7">
