### ISSUE TITLE
建议添加自由节点的功能

### ISSUE THREAD

**Issue by sumruler** [wanglin2/mind-map#534]
很多思维导图工具都有自由节点的功能，就是一个没有根节点的节点，或者称为浮动主题

![Clip_2024-01-29_11-50-48](https://github.com/wanglin2/mind-map/assets/56953545/03f45f5c-08b5-4711-acae-12bd886e7e4f)

**Comment by wanglin2** [comment]
重复issue：https://github.com/wanglin2/mind-map/issues/203
