### ISSUE TITLE
Cooperate插件初始状态同步问题

### ISSUE THREAD

**Issue by wanglin2** [wanglin2/mind-map#535]
Cooperate的时候，在界面1点击了某个节点。打开第二个界面，这时候不会显示这个节点已被选中。只有当你在第二个节点再次点击某一个节点才显示出来

**Comment by wanglin2** [comment]
![xt](https://github.com/wanglin2/mind-map/assets/17272433/f34abc75-8ee6-4c03-93c7-39d5e5624517)

**Comment by wanglin2** [comment]
看着好像没问题啊

**Comment by LsEmpire** [comment]
我知道问题了，是chrome不行，我用edge是可以的
