### ISSUE TITLE
vite中使用是报错

### ISSUE THREAD

**Issue by mlie-lh** [wanglin2/mind-map#54]
依赖不支持导致,参照下面的issues
不知道有没有什么替代方案
https://github.com/nashwaan/xml-js/issues/54

**Comment by wanglin2** [comment]
试试这样引入：import MindMap from "simple-mind-map/dist/simpleMindMap.umd"

**Comment by mlie-lh** [comment]
谢谢，可以用了
非常感觉您的帮助
