### ISSUE TITLE
KeyCommand.save()、KeyCommand.restore()函数存在逻辑缺陷，某种场景下将导致编辑器快捷键全部失效。

### ISSUE THREAD

**Issue by zhangXiaoMin007** [wanglin2/mind-map#541]
**KeyCommand.save()、KeyCommand.restore()函数存在逻辑缺陷，某种场景下将导致编辑器快捷键全部失效：**
其复现步骤为：
选中某个节点，打开节点标签编辑器弹窗，连续按下Tab键，将焦点切换至编辑器器底部导航栏元素。点击弹窗蒙版关闭弹窗，同时连续按下Tab键盘，此时，函数KeyCommand.save()、KeyCommand.restore()中的逻辑将导致shortcutMap对象被清空。所有快捷键失效。其他类似场景也引发这样的结果。
做了以下更改，作为临时策略规避缺陷，但应该不是最优解，请作者从设计层面入手，修复这个缺陷。
![mind-map快捷键失效](https://github.com/wanglin2/mind-map/assets/28802707/ab0d1e71-af22-4bda-9708-0fe84e112306)

**Comment by wanglin2** [comment]
这个原因是调了startTextEdit方法清空快捷键，但是点击弹窗的遮罩关闭没有调endTextEdit方法恢复快捷键

**Comment by wanglin2** [comment]
我目前是在demo中修复这个问题，库暂时不做修改

**Comment by zhangXiaoMin007** [comment]
> 我目前是在demo中修复这个问题，库暂时不做修改

好的
