### ISSUE TITLE
vue中实例化

### ISSUE THREAD

**Issue by liuyu1863** [wanglin2/mind-map#55]
在vue中使用时实例化时数据报错是咋回事
![image](https://user-images.githubusercontent.com/28972542/210939142-04b860ce-773a-4f93-bab6-cd0fd974cb9b.png)

![image](https://user-images.githubusercontent.com/28972542/210925234-4cbbc72f-a8aa-4cf2-913e-825051ab1dc7.png)

**Comment by wanglin2** [comment]
方便完整的项目压缩一下发我看看吗

**Comment by liuyu1863** [comment]
这个不太方便，项目不是用的vue-cli搭建的，是用的webpack
![image](https://user-images.githubusercontent.com/28972542/211229972-931d9661-cb27-473e-a976-247097ebd47b.png)

**Comment by wanglin2** [comment]
为啥要把这两个加到include里呢

**Comment by liuyu1863** [comment]
不加的话，会报错
![image](https://user-images.githubusercontent.com/28972542/211230279-0055a996-90cf-4b1f-81d6-62b72699d218.png)

**Comment by wanglin2** [comment]
@svgdotjs/svg.js版本太高，安装3.0.16即可。
