### ISSUE TITLE
BUG - Toolbar 

### ISSUE THREAD

**Issue by quyphuc2111** [wanglin2/mind-map#551]
Hello sir,  In toolbar, i using **Sibling Node --> Delete node** . The nearest node is currently being deleted, but the node just created cannot be deleted. How to delete newly created node using SIBLING Mode. Thankss @wanglin2

**Comment by wanglin2** [comment]
This is a bug in the mind map library. You can wait for the 0.9.8 version update, or you can obtain the latest code from the feature branch
