### ISSUE TITLE
节点在编辑状态， 鼠标离开脑图后， 脑图依然响应键盘事件 如复制粘贴事件

### ISSUE THREAD

**Issue by yangda666** [wanglin2/mind-map#559]
节点在编辑状态， 鼠标离开脑图后， 脑图依然响应键盘事件 如复制粘贴事件

**Comment by wanglin2** [comment]
这种应该是正常的，毕竟焦点还在

**Comment by yangda666** [comment]
鼠标聚焦在脑图外也是不行

**Comment by yangda666** [comment]
![Snipaste_2024-03-06_17-10-34](https://github.com/wanglin2/mind-map/assets/70259086/703955c9-b8b1-4878-a04d-a2788a0e914b)

**Comment by yangda666** [comment]
![03](https://github.com/wanglin2/mind-map/assets/70259086/a32e90a8-58d8-4599-a23d-2ba6de8308fb)

**Comment by yangda666** [comment]
这个里面 我改了几行代码 实现了鼠标聚焦不再脑图 脑图不在响应快捷键 不知道改的对不对

**Comment by wanglin2** [comment]
能实现你要的功能就是对的
