### ISSUE TITLE
桌面版本-导入支持格式问题

### ISSUE THREAD

**Issue by fofossy** [wanglin2/mind-map#561]
桌面版本-打开本地文件，下拉选项中只支持(*.smm)格式，但是在编辑界面的导入中，支持的格式有.smm、.json、.xmind、.xlsx、.md文件这么多格式。

**Comment by wanglin2** [comment]
打开和导入是不同的功能，打开会实时修改打开的文件，导入并不会，所以打开只支持私有格式

**Comment by fofossy** [comment]
用其他软件习惯了 **插入下级节点** 的快捷键是**Insert**，如果此快捷键没有被占用的话，希望up主支持一下
