### ISSUE TITLE
双击进入节点文本，能否自动全选当前节点上的全部文本。

### ISSUE THREAD

**Issue by star755** [wanglin2/mind-map#568]
双击进入节点文本，能否自动全选当前节点上的全部文本。

当前为：
1.双击节点进入节点文本，只有焦点在节点文本末端。没有对节点文本全选。在节点上全选操作并不太理想。

期望改进效果：
1.双击节点进入节点文本，可以直接ctrl+c复制节点文本。也可以ctrl+v粘贴覆盖节点文本。

**Comment by star755** [comment]
win客户端版本

**Comment by wanglin2** [comment]
目前的策略是新增节点会自动全选，编辑时不会全选，这个逻辑暂时不做修改
