### ISSUE TITLE
Let's do not use these comments

### ISSUE THREAD

**Issue by emircanerkul** [wanglin2/mind-map#57]
If would you use the right tools (vscode & gitlens (FREE)) you can quickly see who made changes and when.

<img width="661" alt="image" src="https://user-images.githubusercontent.com/11430795/211293320-7228fc3c-c4dd-4e75-8acf-e1857747424e.png">

So you don't need to place the author and date all around. I'm not sure how these descriptions are useful (setMode, as it written, should set the mode. No need to repeat again and again) but it might make sense if you automatically generate documentation.

In this setMode example, there are enum types that are read-only, and `edit` should be in the documentation as its written. BTW this is why **Typescript** is useful.

**Comment by wanglin2** [comment]
This kind of comment is only due to my habit in my work, because many of our code does not use git management. In addition, I will slowly try to switch to TypeScript in the future. At present, because I am not familiar with TS and there is a lot of code, I may write the type definition file first.

**Comment by emircanerkul** [comment]
Oh, Got it. Habits are habits. Yea that would be good btw the TS not so hard but yea in this lots of codes that probably would be time-consuming.

**Comment by wanglin2** [comment]
Thank you for your suggestion. All comments have been converted
