### ISSUE TITLE
[ Open file feature ]

### ISSUE THREAD

**Issue by quyphuc2111** [wanglin2/mind-map#576]
Hello sir, @wanglin2 
When I change the background, and I open another file it seems to be getting the old background again.
How can I fix it? 
Thanks
https://drive.google.com/file/d/1Rg5zsCmhqqGcyebS9G23VN-3PVAx3Gmh/view

**Comment by wanglin2** [comment]
At present, the background is a part of the theme, so switching file backgrounds will also modify it
