### ISSUE TITLE
怎么能只改根节点的paddingY，不影响其余子节点的。现在只能改全部的

### ISSUE THREAD

**Issue by jiangwenqiyu** [wanglin2/mind-map#585]
![image](https://github.com/wanglin2/mind-map/assets/70049060/97129728-d735-440b-ba67-3f3e181118b1)

**Comment by wanglin2** [comment]
![image](https://github.com/wanglin2/mind-map/assets/17272433/551360e6-4fd4-4828-8c41-c18fc17e322b)
