### ISSUE TITLE
请问下，目前导出png时，是否支持增加自定义的内容

### ISSUE THREAD

**Issue by sidepico** [wanglin2/mind-map#587]
<img width="1043" alt="企业微信截图_27991f9e-e8f1-4439-8034-a1680c277c3c" src="https://github.com/wanglin2/mind-map/assets/110678668/71aec4ad-965b-47a9-9c05-c0a2e1426ed8">

**Comment by wanglin2** [comment]
新增了addContentToHeader、 addContentToFooter两个实例化选项用于添加自定义内容，v0.9.9+生效
