### ISSUE TITLE
Demo：右键插入父节点功能异常

### ISSUE THREAD

**Issue by ZMonet** [wanglin2/mind-map#589]
在Demo中选中一个节点，右键选择“插入父节点”，会在当前节点的下一级生成一个新的节点，也就是插入的是子节点并且该节点是透明的，节点里面有文字但是看不见，切换主题后正常显示
![插入父节点](https://github.com/wanglin2/mind-map/assets/34715369/d76def90-f4be-461f-84b2-11d51255eaa5)

**Comment by wanglin2** [comment]
插入父级节点应该是没问题的，是原来的二级节点变成了三级节点，文本颜色没有更新，跟背景同色导致看不见

**Comment by wanglin2** [comment]
样式更新问题已修复，v0.9.9-fix.2+生效
