### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by emircanerkul** [wanglin2/mind-map#59]
I forked your project for my Educational Drupal-related project. I want to Thank you first.

In my project, I only needed the read-only option. Yours aren't enough for me because it still loads lots of things.

To speed up my read-only environment (+7m word and ~2800 node)
- I removed the History mechanism (which causes really great performance issues)
- I removed lots of things hierarchy catalog, select, etc. ([opensource](https://github.com/emircanerkul/drupal-mind-map))

**Bug report:** Meanwhile keyword navigation doesn't work with read-only mode.

BDW I'm still developing my version of the mindmap. In addition, I really liked your project architecture. Thank you!

**Comment by wanglin2** [comment]
Thank you very much for your suggestion. You are right. Now all the functions are loaded at one time, resulting in performance problems and large volume.

I will immediately try to change it to plug-in mode and introduce various functions as needed.
