### ISSUE TITLE
增加需求

### ISSUE THREAD

**Issue by weipiaoyun** [wanglin2/mind-map#591]
桌面版是否可以在节点下面增加附件功能

**Comment by wanglin2** [comment]
没有云存储能力，附件功能暂不考虑

**Comment by weipiaoyun** [comment]
可能我描述的不够清晰，我的意思只是桌面版。添加的附件相当于只是一个链接，就像超链接一样，连接到本地电脑，实际不占资源，点击的时候是通过调用电脑的程序打开的（文件的默认打开方式）。我是看亿图脑图MindMaster有这个功能。但是这种只能桌面版，浏览器权限不够。
