### ISSUE TITLE
可能我描述的不够清晰，我的意思只是桌面版。添加的附件相当于只是一个链接，就像超链接一样，连接到本地电脑，实际不占资源，点击的时候是通过调用电脑的程序打开的（文件的默认打开方式）。我是看亿图脑图MindMaster有这个功能。但是这种只能桌面版，浏览器权限不够。

### ISSUE THREAD

**Issue by weipiaoyun** [wanglin2/mind-map#593]
可能我描述的不够清晰，我的意思只是桌面版。添加的附件相当于只是一个链接，就像超链接一样，连接到本地电脑，实际不占资源，点击的时候是通过调用电脑的程序打开的（文件的默认打开方式）。我是看亿图脑图MindMaster有这个功能。但是这种只能桌面版，浏览器权限不够。

_Originally posted by @weipiaoyun in https://github.com/wanglin2/mind-map/issues/591#issuecomment-2027840698_
![image](https://user-images.githubusercontent.com/44353493/318155757-a09c5a75-fce6-4b6b-8e46-92acf6f93b14.png)

**Comment by weipiaoyun** [comment]
![image](https://github.com/wanglin2/mind-map/assets/44353493/58af4f75-988d-4c23-a33e-c4baca80ca7f)

**Comment by wanglin2** [comment]
已支持，0.9.10+版本生效
