### ISSUE TITLE
有没有大神fork iOS的ipa?

### ISSUE THREAD

**Issue by GamenRoll** [wanglin2/mind-map#596]
求 iPA
万谢

**Comment by xyhuangjia** [comment]
> 求 iPA 万谢

要证书的

**Comment by GamenRoll** [comment]
没关系，有Troll的

**Comment by TonyBlur** [comment]
> 求 iPA 万谢

可以借助[PWABuilder](https://www.pwabuilder.com/)来自己build基于网页的可安装pwa，由于我手头没有Macbook因此没法用XCode来创建ipa文件。但是如果你有mac的话可以自行创建并安装，[我的仓库](https://github.com/TonyBlur/mind-map)有已经部署并简单编写好`manifest.json`的网站，你可以直接拿去用。
