### ISSUE TITLE
更新quill: quill  <=1.3.7 Severity: moderate

### ISSUE THREAD

**Issue by lymlin** [wanglin2/mind-map#601]
大佬，npm quill库更新了，mind-map 怎么换新的quill库呢？ 原来的部署后报错：# npm audit report

quill  <=1.3.7
Severity: moderate
Cross-site Scripting in quill - https://github.com/advisories/GHSA-4943-9vgg-gr5r

更新的quill: https://quilljs.com/docs/quickstart
<script src="https://cdn.jsdelivr.net/npm/quill@2.0.0-rc.4/dist/quill.js"></script>

**Comment by wanglin2** [comment]
需要自己修改RichText插件
