### ISSUE TITLE
[功能建议]customCreateNodeContent是否可以改为async函数

### ISSUE THREAD

**Issue by lointain** [wanglin2/mind-map#602]
建议customCreateNodeContent改为async函数

好处是可以等待节点div绘制完成(比如react,或者vue的teleport render)获得宽高再继续绘制下一个节点, 这样就不需要先手动指定宽高.

我在本地实验, 加了一串await/async后, 理论上是可以的.

因为毕竟现在很少有人用原生js来开发和拼div, 基本上都是要用个vue或react的, 如果能更好的支持现代框架, 对贵软件的推广很有好处.

当然这种场景是否合适, 是否常用, 有没有其他副作用, 还需要讨论的.

**Comment by wanglin2** [comment]
这个改不动
