### ISSUE TITLE
我想在工具栏中加入历史记录浏览功能 但是显示历史记录脑图后 主编辑脑图就不能使用了 我应该怎么修改

### ISSUE THREAD

**Issue by yangda666** [wanglin2/mind-map#604]
https://github.com/wanglin2/mind-map/assets/70259086/d06da165-d358-4d45-9e01-65adc73caf01

**Comment by wanglin2** [comment]
代码截一下，看视频我也不知道为啥

**Comment by yangda666** [comment]
<template>
  <el-dialog class="nodeImportDialog" title="预览" :visible.sync="dialogVisible" width="800px">
    <div id="mindMapContainer1" ref="mindMapContainerRef"></div>
    <span slot="footer" class="dialog-footer">
      <el-button @click="handleClose">{{ $t('dialog.cancel') }}</el-button>
    </span>
  </el-dialog>
</template>

<script>

import { getData } from '@/api';
import MindMap from 'simple-mind-map';

export default {
  name: 'Import',
  data() {
    return {
      dialogVisible: false,
      mindMapData: null,
    }
  },
  watch: {
    dialogVisible(val, oldVal) {
      if (val) {
        setTimeout(() => {
          this.getData()
          this.init()
        }, 100)

      }
    }
  },
  created() {
    this.$bus.$on('showPreview', this.handleShowPreview)
  },
  mounted() {
    this.getData()
  },
  beforeDestroy() {
    this.$bus.$off('showPreview', this.handleShowPreview)
  },
  methods: {
    getData() {
      let storeData = getData()
      this.mindMapData = storeData
    },

    handleClose() {
      this.dialogVisible = false
    },
    handleShowPreview() {
      this.dialogVisible = true
    },
    /**
    * @Author: 王林
    * @Date: 2021-04-10 15:01:01
    * @Desc: 初始化
    */
    init() {
      let { root, layout, theme, view, config } = this.mindMapData
      // 如果url中存在要打开的文件，那么思维导图数据、主题、布局都使用默认的
      this.mindMap = new MindMap({
        el: this.$refs.mindMapContainerRef,
        data: root,
        fit: false,
        layout: layout,
        theme: theme.template,
        themeConfig: theme.config,
        viewData: view,
        nodeTextEditZIndex: 1000,
        nodeNoteTooltipZIndex: 1000,
        ...(config || {}),
        // useLeftKeySelectionRightKeyDrag: this.useLeftKeySelectionRightKeyDrag,
        customInnerElsAppendTo: null,
        enableAutoEnterTextEditWhenKeydown: true,
        defaultNodeImage: require('../../../assets/img/图片加载失败.svg'),
        initRootNodePosition: ['center', 'center'],
      })
    },

  },
}


</script>

<style lang="less" scoped>
.nodeImportDialog {
  #mindMapContainer1 {
    // position: absolute;
    width: 100%;
    height: 600px;
  }
}
</style>

**Comment by wanglin2** [comment]
是个bug，下个版本会修复

**Comment by wanglin2** [comment]
已修复，v0.9.11+生效，也可以拉取feature分支获取最新的代码
