### ISSUE TITLE
REMOVE_NODE命令删除当前激活节点的子节点后当前节点的激活状态无法消失

### ISSUE THREAD

**Issue by 654469021** [wanglin2/mind-map#609]
点击激活一个节点正常删除的话调用mindMap.execCommand('REMOVE_NODE')是可以正常删除的，但是有一个节点我没有点击激活，我又想删除这个节点，我按照API文档里的《REMOVE_NODE》方法，传人要删除的节点，但是没有效果，节点没有删除掉。
![28D26571-106D-4ce4-AC2A-7B192DB9AFC5](https://github.com/wanglin2/mind-map/assets/27802417/7c01e7b7-44b6-46c5-a493-6e359dccbbc7)

**Comment by 654469021** [comment]
我的是vue项目中 npm i simple-mind-map 安装的

**Comment by wanglin2** [comment]
那估计是传的节点有问题，可以打印出来看看

**Comment by 654469021** [comment]
这是我打印出来的node节点数据
![7E8053BB-CF48-4243-A74F-004C52CE92F6](https://github.com/wanglin2/mind-map/assets/27802417/add2647b-ab76-4fce-abf7-35271247f603)
![47A1D6FC-32FB-48e3-8F02-3C1B1A9E8C4E](https://github.com/wanglin2/mind-map/assets/27802417/689334d8-ba8e-4889-99cb-9522b469027e)

**Comment by wanglin2** [comment]
你这个节点是怎么获取的

**Comment by 654469021** [comment]
mindMap.execCommand('REMOVE_NODE', appointNodes) 传的node我开始是用的nodeData中的_node数据。刚才我又用mindMap.renderer.findNodeByUid(uid)方法获取node实例，将node实例传入后删除成功。
但是我删除子节点后，父节点的选中状态无法取消，我在点击画布也不行。

![A3793270-64F8-4e96-B13A-0940D228F34F](https://github.com/wanglin2/mind-map/assets/27802417/a8aa7228-1dd9-4b97-9795-53be4ef3cf82)
![79F122EA-EBC0-4cfa-AE89-1BB3E3CEDED1](https://github.com/wanglin2/mind-map/assets/27802417/af7b5a91-53a8-4571-9565-cec3347bb970)
![9381DB79-1BEF-458c-9978-533452F26975](https://github.com/wanglin2/mind-map/assets/27802417/88d5502f-2408-4d3f-95f9-e5f390fbcc83)

**Comment by 654469021** [comment]
我的项目业务需求是：点击某一个节点，根据该节点关联的问题选项变动，新增或者删除该节点的子节点。
问题：删除该节点的子节点后，该节点始终处于选中状态，无法取消。
![D0C6CF76-8482-4621-8BCA-418C133154B9](https://github.com/wanglin2/mind-map/assets/27802417/5f1eef8e-1c62-45d3-8b94-bd9311d18928)
![A5DAE0E2-0391-4ac7-AD1D-8FD15A8DE1E5](https://github.com/wanglin2/mind-map/assets/27802417/3910bc6c-bb54-4e29-9771-cc52c4107e9d)

**Comment by wanglin2** [comment]
这是个bug，你可以换种方式，直接修改数据，然后重新渲染，就像这样：node.nodeData.children = []
              this.mindMap.render()

**Comment by 654469021** [comment]
大佬，这个bug什么时候可以修复吗？直接全量修改数据，然后重新渲染，性能比较差，如果直接修改当前node的数据，然后this.mindMap.render()好像没有用呢
![EE177BD0-4AB0-41b0-A0C8-365927AE3D7D](https://github.com/wanglin2/mind-map/assets/27802417/c2355fe1-3bb8-4bee-9be6-7e4f099fd1eb)

**Comment by wanglin2** [comment]
已修复，v0.9.11+生效
