### ISSUE TITLE
非常优秀的项目，是否考虑支持用户组和权限设置

### ISSUE THREAD

**Issue by Sincejunly** [wanglin2/mind-map#61]
以及自定背景图片或者背景音乐，使用目前的方式导入背景图片不会随浏览器缩放，希望能在背景上增加更多花样，比如，可以定时更换图片以及支持视频或者GIF？
再次表达感谢非常美观且优秀的项目

**Comment by wanglin2** [comment]
你好，背景图片新增了位置和大小设置，同时优化了导出为图片的功能，导出的图片也支持重复、位置、大小的设置效果。
其他的功能暂时没有计划支持。
