### ISSUE TITLE
思维导图节点数据很多时，操作起来很卡

### ISSUE THREAD

**Issue by chenzechuang** [wanglin2/mind-map#610]
修改一个节点要把svg重新渲染一遍，在性能差一点的电脑上，操作起来很卡很慢，用户体验比较差
大佬有什么解决方法吗

**Comment by wanglin2** [comment]
数据很多是指多少个节点，目前已经尽量的复用节点了

**Comment by NiShuiXingZ** [comment]
> 数据很多是指多少个节点，目前已经尽量的复用节点了

请问一下7000多个节点卡顿属于正常不？

**Comment by wanglin2** [comment]
> > 数据很多是指多少个节点，目前已经尽量的复用节点了
> 
> 请问一下7000多个节点卡顿属于正常不？

理论上1000+节点卡顿就开始明显了，节点都是svg渲染的，页面上DOM节点多了卡顿是难以避免的。

**Comment by NiShuiXingZ** [comment]
> > > 数据很多是指多少个节点，目前已经尽量的复用节点了
> > 
> > 
> > 请问一下7000多个节点卡顿属于正常不？
> 
> 理论上1000+节点卡顿就开始明显了，节点都是svg渲染的，页面上DOM节点多了卡顿是难以避免的。

恩确实，刚才官网试了一下，1600个节点就有点卡了。  我试了百度脑图，建了几千个节点，他们加载拖动都很流畅，请教一下，您知道他们怎么做的吗？

**Comment by wanglin2** [comment]
> > > > 数据很多是指多少个节点，目前已经尽量的复用节点了
> > > 
> > > 
> > > 请问一下7000多个节点卡顿属于正常不？
> > 
> > 
> > 理论上1000+节点卡顿就开始明显了，节点都是svg渲染的，页面上DOM节点多了卡顿是难以避免的。
> 
> 恩确实，刚才官网试了一下，1600个节点就有点卡了。 我试了百度脑图，建了几千个节点，他们加载拖动都很流畅，请教一下，您知道他们怎么做的吗？

百度脑图性能是更好一点，但本质上都是svg，节点多了，创建新节点、展开收起、文本编辑等操作也都变慢了，想要超大数据量，底层还是得用canvas来渲染

**Comment by NiShuiXingZ** [comment]
> > > > > 数据很多是指多少个节点，目前已经尽量的复用节点了
> > > > 
> > > > 
> > > > 请问一下7000多个节点卡顿属于正常不？
> > > 
> > > 
> > > 理论上1000+节点卡顿就开始明显了，节点都是svg渲染的，页面上DOM节点多了卡顿是难以避免的。
> > 
> > 
> > 恩确实，刚才官网试了一下，1600个节点就有点卡了。 我试了百度脑图，建了几千个节点，他们加载拖动都很流畅，请教一下，您知道他们怎么做的吗？
> 
> 百度脑图性能是更好一点，但本质上都是svg，节点多了，创建新节点、展开收起、文本编辑等操作也都变慢了，想要超大数据量，底层还是得用canvas来渲染

明白了，感谢回答！

**Comment by chenzechuang** [comment]
> > > > > 数据很多是指多少个节点，目前已经尽量的复用节点了
> > > > 
> > > > 
> > > > 请问一下7000多个节点卡顿属于正常不？
> > > 
> > > 
> > > 理论上1000+节点卡顿就开始明显了，节点都是svg渲染的，页面上DOM节点多了卡顿是难以避免的。
> > 
> > 
> > 恩确实，刚才官网试了一下，1600个节点就有点卡了。 我试了百度脑图，建了几千个节点，他们加载拖动都很流畅，请教一下，您知道他们怎么做的吗？
> 
> 百度脑图性能是更好一点，但本质上都是svg，节点多了，创建新节点、展开收起、文本编辑等操作也都变慢了，想要超大数据量，底层还是得用canvas来渲染

请问下你知道百度脑图做了什么处理么   我看了你之前处理了只渲染当前视图的优化   这个是已经上线了吗

**Comment by pang-xf** [comment]
@chenzechuang 请问最后是怎么处理的 我们这边节点数也有几千个 卡顿明显😩
