### ISSUE TITLE
演示模式的问题

### ISSUE THREAD

**Issue by wanglin2** [wanglin2/mind-map#616]
1.不支持展示概要
2.因为禁止了鼠标事件，所以节点内的超链接、备注无法点击
3.支持下划线文本的填空模式

**Comment by zzzqgrelax** [comment]
感谢大佬的思维导图  提几个意见看看有没有帮助
1.演示模式打开的话是不是应该直接展开所有节点比较合适
2.演示模式打开的话是不是默认展示整个思维导图比较合适 而不是展示某个层级

**Comment by wanglin2** [comment]
> 感谢大佬的思维导图 提几个意见看看有没有帮助 1.演示模式打开的话是不是应该直接展开所有节点比较合适 2.演示模式打开的话是不是默认展示整个思维导图比较合适 而不是展示某个层级

展示整个思维导图我觉得没啥太大的意义，缩小了以后也看不清

**Comment by wanglin2** [comment]
> 1.不支持展示概要 2.因为禁止了鼠标事件，所以节点内的超链接、备注无法点击 3.支持下划线文本的填空模式

都已支持，v0.9.12+生效
