### ISSUE TITLE
请问这个功能有上线么？

### ISSUE THREAD

**Issue by chenzechuang** [wanglin2/mind-map#623]
连接线最好也不要渲染，否则还是卡

_Originally posted by @wanglin2 in https://github.com/wanglin2/mind-map/issues/262#issuecomment-1678529529_

**Comment by wanglin2** [comment]
这个尝试放弃了，这种方式不太现实，目前你要大数据，又不卡，那就只能把节点收起来

**Comment by chenzechuang** [comment]
> 这个尝试放弃了，这种方式不太现实，目前你要大数据，又不卡，那就只能把节点收起来

我用知犀的测了下，我看都是用svg渲染的，同样都是1000个节点，知犀的渲染速度会快挺多的，请问你知道为什么？
特别是那种调整节点位置，全部渲染的操作，我看知犀的响应会快挺多

**Comment by wanglin2** [comment]
知犀早期估计是基于百度脑图二次开发的，现在倒是没有百度脑图的痕迹了。我显然不知道啊，知道我就优化了，这么跟你说把，节点的布局计算耗时是不多的，每次渲染时，更新一个节点的位置会耗时1毫秒，看着很少是吧，但是1000个节点就1秒了
