### ISSUE TITLE
svg渲染速度问题

### ISSUE THREAD

**Issue by chenzechuang** [wanglin2/mind-map#624]
我用知犀的测了下，我看都是用svg渲染的，同样都是1000个节点，知犀的渲染速度会快挺多的，请问你知道为什么？
调整节点位置，节点下方的数据 位置信息会重新渲染，知犀的响应会快挺多
知犀
![image](https://github.com/wanglin2/mind-map/assets/18185456/27e6604b-f76f-4b10-9344-b3d33645c949)
simple-mind-map
![image](https://github.com/wanglin2/mind-map/assets/18185456/40a4fd2b-dcb3-4d1a-aa27-93f81e0997fc)

**Comment by quanzhongxian** [comment]
@chenzechuang 可能是使用记忆化搜索算法，算法不一样吧

**Comment by wanglin2** [comment]
0.10.4版本优化了一下性能，可以在在线demo里试试，
![image](https://github.com/user-attachments/assets/ef80eeca-a093-4e0a-a915-b57e5615bbe1)
