### ISSUE TITLE
导出问题：xmind导出失败，已经引入了import Export from 'simple-mind-map/src/plugins/Export.js' import ExportXMind from 'simple-mind-map/src/plugins/ExportXMind.js' MindMap.usePlugin(Export) MindMap.usePlugin(ExportXMind)

### ISSUE THREAD

**Issue by quanzhongxian** [wanglin2/mind-map#627]
77.js:315 export_error TypeError: jszip__WEBPACK_IMPORTED_MODULE_6__.default is not a constructor
    at _callee5$ (xmind.js:345:1)
    at tryCatch (regeneratorRuntime.js:45:1)
    at Generator.<anonymous> (regeneratorRuntime.js:133:1)
    at Generator.next (regeneratorRuntime.js:74:1)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:22:1)

**Comment by quanzhongxian** [comment]
![Snipaste_2024-04-25_15-30-29](https://github.com/wanglin2/mind-map/assets/84429231/277d2264-913e-48ad-8547-deaab1961151)

**Comment by wanglin2** [comment]
建议可以百度一下，这个我也不太清楚怎么解决

**Comment by quanzhongxian** [comment]
@wanglin2 为什么 导出的 .xmind 格式跟自己设置的主题格式不一样，比如我设置三级节点已经以下节点都有边框的，可是导出的都没有

**Comment by wanglin2** [comment]
> @wanglin2 为什么 导出的 .xmind 格式跟自己设置的主题格式不一样，比如我设置三级节点已经以下节点都有边框的，可是导出的都没有

导出为xmind不支持携带样式
