### ISSUE TITLE
功能优化请求：请支持拖拽导入附件 文件/ 文件夹 

### ISSUE THREAD

**Issue by WTianZuo** [wanglin2/mind-map#632]
感谢大佬的辛勤付出!在知乎上看到然后下载体验了！超级棒的思维导图软件！
个人最近在做个电脑文件管理脑图的过程中，遇到这个小问题，附件默认只支持到 打开具体文件 ，虽然可以通过 在源码上修改的方式 让它实现 打开对应的文件夹 的功能，
但量多了有些小不方便。然后 再问下怎么 **设置 附件 的 相对路径 **来打开它？
 最后 当然希望像Xmind 那样能直接 **拖拽 文件/文件夹** 来生成 附件节点 是最好的体验了！ 谢谢！

**Comment by wanglin2** [comment]
选择文件夹和相对路径都已支持，v0.11.0+版本可用
拖拽会和已有功能冲突，暂不考虑
