### ISSUE TITLE
当节点内容有图标&&换行符号时候，展开收起节点会导致样式错误

### ISSUE THREAD

**Issue by HongFei1998** [wanglin2/mind-map#636]
如下图，如果一个节点内容带有换行符（shift+enter）且包含图标，此时点击父节点的收起展开按钮，会发现图标与文字内容距离逐渐拉大，甚至超出原有边框

**Comment by HongFei1998** [comment]
![image](https://github.com/wanglin2/mind-map/assets/32254020/62bad151-fd7e-4937-9e84-276c52cb6f86)

**Comment by wanglin2** [comment]
在线demo能复现吗

**Comment by wanglin2** [comment]
复现了，非富文本模式下存在问题

**Comment by wanglin2** [comment]
已修复，v0.9.12+生效
