### ISSUE TITLE
自定义节点问题

### ISSUE THREAD

**Issue by misakichan** [wanglin2/mind-map#644]
如果希望在节点的最左侧和最右侧增加自定义元素，如按钮等。但又不希望完全使用isUseCustomNodeContent（会导致原本的标签，图标等功能失效）。
有没有什么好的方式可以支持改造，如提供插槽之类的方式？

**Comment by wanglin2** [comment]
![image](https://github.com/wanglin2/mind-map/assets/17272433/399566fc-6796-4134-90c0-5d49fbf66d0b)
新增了添加自定义前置和后置内容的实例化选项，v0.9.12+生效

**Comment by misakichan** [comment]
非常非常需要，0.9.12预计什么时候上线呀？

**Comment by wanglin2** [comment]
本周或下周，大概率是下周
