### ISSUE TITLE
当思维导图在渲染过程中，此时重新渲染，可能导致思维导图样式错乱

### ISSUE THREAD

**Issue by huang-yf3160** [wanglin2/mind-map#645]
当思维导图在渲染过程中，此时重新渲染，可能导致思维导图样式错乱

是否有规避方案呢？

**Comment by wanglin2** [comment]
可以贴一下代码和动图

**Comment by huang-yf3160** [comment]
> 可以贴一下代码和动图

代码就是简单的调用render，大概逻辑是ai生成流式内容，然后动态渲染到思维导图上
![动画](https://github.com/wanglin2/mind-map/assets/56285360/8dc3df58-4bcc-473a-ac86-75b25de92d96)

**Comment by huang-yf3160** [comment]
而且在多节点情况下容易复现，当前思维导图有大概2000个节点

**Comment by wanglin2** [comment]
重新渲染部分的代码可以贴一下，代码不方便截图，伪代码也可以写几行，不然我也不知道怎么去复现这个问题

**Comment by huang-yf3160** [comment]
> 重新渲染部分的代码可以贴一下，代码不方便截图，伪代码也可以写几行，不然我也不知道怎么去复现这个问题
调用流式接口,在获取数据内一直调用方法，应该可以用定时器模拟
onData: () => {
  // 该方法为更新/新增目标节点下子节点内容，mindMapData 为 思维导图数据 
  const data = updateNodeContent(mindMapData, uid, node)
  mindMap.renderer.setData(data)
  this.mindMap.render()
}
大概逻辑是这样

**Comment by wanglin2** [comment]
![image](https://github.com/wanglin2/mind-map/assets/17272433/71a5d3a8-3294-4e13-810c-033dad739dfa)

我试了一下1000多个节点，也没有错乱，只要新数据的节点uid没有变化按理说是没问题的

**Comment by huang-yf3160** [comment]
> ![image](https://private-user-images.githubusercontent.com/17272433/329769973-71a5d3a8-3294-4e13-810c-033dad739dfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MTk4NDEsIm5iZiI6MTcxNTQxOTU0MSwicGF0aCI6Ii8xNzI3MjQzMy8zMjk3Njk5NzMtNzFhNWQzYTgtMzI5NC00ZTEzLTgxMGMtMDMzZGFkNzM5ZGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA5MjU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNjBjMWEzZWNlMGMyMWFkZjBlNjIwNzJmZWVlNmI4OWU2ZTNkNzQwODU0NjEwYmUyZWFiM2VlZDFiNWQ4ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jWOLtPoIym4Zwk-xrZnwpvqxJEvNaVdId7Ab1xe6WpY)
> 
> 我试了一下1000多个节点，也没有错乱，只要新数据的节点uid没有变化按理说是没问题的

如果uid发生变化了呢？而且我们会在数据获取完整后，调用一次reRender事件，会出现gif最后几秒的画面，就是完全乱掉；
有没有您觉得可能出现问题的点，我们去排查一下呢，因为我们对您这边思维导图做了很多魔改，有可能在您这边是不复现的

**Comment by wanglin2** [comment]
> > ![image](https://private-user-images.githubusercontent.com/17272433/329769973-71a5d3a8-3294-4e13-810c-033dad739dfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MTk4NDEsIm5iZiI6MTcxNTQxOTU0MSwicGF0aCI6Ii8xNzI3MjQzMy8zMjk3Njk5NzMtNzFhNWQzYTgtMzI5NC00ZTEzLTgxMGMtMDMzZGFkNzM5ZGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA5MjU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNjBjMWEzZWNlMGMyMWFkZjBlNjIwNzJmZWVlNmI4OWU2ZTNkNzQwODU0NjEwYmUyZWFiM2VlZDFiNWQ4ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jWOLtPoIym4Zwk-xrZnwpvqxJEvNaVdId7Ab1xe6WpY)
> > 我试了一下1000多个节点，也没有错乱，只要新数据的节点uid没有变化按理说是没问题的
> 
> 如果uid发生变化了呢？而且我们会在数据获取完整后，调用一次reRender事件，会出现gif最后几秒的画面，就是完全乱掉； 有没有您觉得可能出现问题的点，我们去排查一下呢，因为我们对您这边思维导图做了很多魔改，有可能在您这边是不复现的

reRender很慢，最好uid不要改变，只调render，看想象是因为上一次渲染的节点没有被删除，又创建了新节点，可以看一下调试一下render类的render方法

**Comment by huang-yf3160** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/17272433/329769973-71a5d3a8-3294-4e13-810c-033dad739dfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MTk4NDEsIm5iZiI6MTcxNTQxOTU0MSwicGF0aCI6Ii8xNzI3MjQzMy8zMjk3Njk5NzMtNzFhNWQzYTgtMzI5NC00ZTEzLTgxMGMtMDMzZGFkNzM5ZGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA5MjU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNjBjMWEzZWNlMGMyMWFkZjBlNjIwNzJmZWVlNmI4OWU2ZTNkNzQwODU0NjEwYmUyZWFiM2VlZDFiNWQ4ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jWOLtPoIym4Zwk-xrZnwpvqxJEvNaVdId7Ab1xe6WpY)
> > > 我试了一下1000多个节点，也没有错乱，只要新数据的节点uid没有变化按理说是没问题的
> > 
> > 
> > 如果uid发生变化了呢？而且我们会在数据获取完整后，调用一次reRender事件，会出现gif最后几秒的画面，就是完全乱掉； 有没有您觉得可能出现问题的点，我们去排查一下呢，因为我们对您这边思维导图做了很多魔改，有可能在您这边是不复现的
> 
> reRender很慢，最好uid不要改变，只调render，看想象是因为上一次渲染的节点没有被删除，又创建了新节点，可以看一下调试一下render类的render方法

[https://github.com/wanglin2/mind-map/blob/98f0d5e0fc20958db3978b0918aa1655c9913017/simple-mind-map/src/core/render/Render.js#L431](url)

当前定位到在此处如果有等待的情况下，再次去渲染时，就会同一个节点在图上有两个，就会出现如gif的情况，但不太清楚为啥上一次的节点没被删除

**Comment by zyaber-y** [comment]
> > 可以贴一下代码和动图
> 
> 代码就是简单的调用渲染，大概逻辑是ai生成流式内容，然后动态渲染到思维导图上 ![动画](https://private-user-images.githubusercontent.com/56285360/329512013-8dc3df58-4bcc-473a-ac86-75b25de92d96.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDM2MjUsIm5iZiI6MTcyMzU0MzMyNSwicGF0aCI6Ii81NjI4NTM2MC8zMjk1MTIwMTMtOGRjM2RmNTgtNGJjYy00NzNhLWFjODYtNzViMjVkZTkyZDk2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDEwMDIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYjE0YzRhMjAxMmQzMDk0MDA0MGI3ZDEzNWM2YmUxMGViYzZmODRjMWM5ZTVmMzg4OTdlODhjN2QyNzQyOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9kI02D3n4gOm8oYn4ozfenKl09faCG0Of78XfyvPjTA) [ ![动画](https://private-user-images.githubusercontent.com/56285360/329512013-8dc3df58-4bcc-473a-ac86-75b25de92d96.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDM2MjUsIm5iZiI6MTcyMzU0MzMyNSwicGF0aCI6Ii81NjI4NTM2MC8zMjk1MTIwMTMtOGRjM2RmNTgtNGJjYy00NzNhLWFjODYtNzViMjVkZTkyZDk2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDEwMDIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYjE0YzRhMjAxMmQzMDk0MDA0MGI3ZDEzNWM2YmUxMGViYzZmODRjMWM5ZTVmMzg4OTdlODhjN2QyNzQyOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9kI02D3n4gOm8oYn4ozfenKl09faCG0Of78XfyvPjTA) ](https://private-user-images.githubusercontent.com/56285360/329512013-8dc3df58-4bcc-473a-ac86-75b25de92d96.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDM2MjUsIm5iZiI6MTcyMzU0MzMyNSwicGF0aCI6Ii81NjI4NTM2MC8zMjk1MTIwMTMtOGRjM2RmNTgtNGJjYy00NzNhLWFjODYtNzViMjVkZTkyZDk2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDEwMDIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYjE0YzRhMjAxMmQzMDk0MDA0MGI3ZDEzNWM2YmUxMGViYzZmODRjMWM5ZTVmMzg4OTdlODhjN2QyNzQyOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9kI02D3n4gOm8oYn4ozfenKl09faCG0Of78XfyvPjTA) [ ](https://private-user-images.githubusercontent.com/56285360/329512013-8dc3df58-4bcc-473a-ac86-75b25de92d96.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDM2MjUsIm5iZiI6MTcyMzU0MzMyNSwicGF0aCI6Ii81NjI4NTM2MC8zMjk1MTIwMTMtOGRjM2RmNTgtNGJjYy00NzNhLWFjODYtNzViMjVkZTkyZDk2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDEwMDIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYjE0YzRhMjAxMmQzMDk0MDA0MGI3ZDEzNWM2YmUxMGViYzZmODRjMWM5ZTVmMzg4OTdlODhjN2QyNzQyOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9kI02D3n4gOm8oYn4ozfenKl09faCG0Of78XfyvPjTA)

请教下，动图中的： 用例  是怎么实现的

**Comment by zyaber-y** [comment]
> > 可以贴一下代码和动图
> 
> 代码就是简单的调用渲染，大概逻辑是ai生成流式内容，然后动态渲染到思维导图上 ![动画](https://private-user-images.githubusercontent.com/56285360/329512013-8dc3df58-4bcc-473a-ac86-75b25de92d96.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDM2MjUsIm5iZiI6MTcyMzU0MzMyNSwicGF0aCI6Ii81NjI4NTM2MC8zMjk1MTIwMTMtOGRjM2RmNTgtNGJjYy00NzNhLWFjODYtNzViMjVkZTkyZDk2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDEwMDIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYjE0YzRhMjAxMmQzMDk0MDA0MGI3ZDEzNWM2YmUxMGViYzZmODRjMWM5ZTVmMzg4OTdlODhjN2QyNzQyOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9kI02D3n4gOm8oYn4ozfenKl09faCG0Of78XfyvPjTA) [ ![动画](https://private-user-images.githubusercontent.com/56285360/329512013-8dc3df58-4bcc-473a-ac86-75b25de92d96.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDM2MjUsIm5iZiI6MTcyMzU0MzMyNSwicGF0aCI6Ii81NjI4NTM2MC8zMjk1MTIwMTMtOGRjM2RmNTgtNGJjYy00NzNhLWFjODYtNzViMjVkZTkyZDk2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDEwMDIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYjE0YzRhMjAxMmQzMDk0MDA0MGI3ZDEzNWM2YmUxMGViYzZmODRjMWM5ZTVmMzg4OTdlODhjN2QyNzQyOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9kI02D3n4gOm8oYn4ozfenKl09faCG0Of78XfyvPjTA) ](https://private-user-images.githubusercontent.com/56285360/329512013-8dc3df58-4bcc-473a-ac86-75b25de92d96.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDM2MjUsIm5iZiI6MTcyMzU0MzMyNSwicGF0aCI6Ii81NjI4NTM2MC8zMjk1MTIwMTMtOGRjM2RmNTgtNGJjYy00NzNhLWFjODYtNzViMjVkZTkyZDk2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDEwMDIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYjE0YzRhMjAxMmQzMDk0MDA0MGI3ZDEzNWM2YmUxMGViYzZmODRjMWM5ZTVmMzg4OTdlODhjN2QyNzQyOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9kI02D3n4gOm8oYn4ozfenKl09faCG0Of78XfyvPjTA) [ ](https://private-user-images.githubusercontent.com/56285360/329512013-8dc3df58-4bcc-473a-ac86-75b25de92d96.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDM2MjUsIm5iZiI6MTcyMzU0MzMyNSwicGF0aCI6Ii81NjI4NTM2MC8zMjk1MTIwMTMtOGRjM2RmNTgtNGJjYy00NzNhLWFjODYtNzViMjVkZTkyZDk2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDEwMDIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYjE0YzRhMjAxMmQzMDk0MDA0MGI3ZDEzNWM2YmUxMGViYzZmODRjMWM5ZTVmMzg4OTdlODhjN2QyNzQyOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9kI02D3n4gOm8oYn4ozfenKl09faCG0Of78XfyvPjTA)
请教下，动图中的： 用例，是怎么实现的

**Comment by huang-yf3160** [comment]
> > > 可以贴一下代码和动图
> > 
> > 
> > 代码就是简单的调用渲染，大概逻辑是ai生成流式内容，然后动态渲染到思维导图上 ![动画](https://private-user-images.githubusercontent.com/56285360/329512013-8dc3df58-4bcc-473a-ac86-75b25de92d96.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDM2MjUsIm5iZiI6MTcyMzU0MzMyNSwicGF0aCI6Ii81NjI4NTM2MC8zMjk1MTIwMTMtOGRjM2RmNTgtNGJjYy00NzNhLWFjODYtNzViMjVkZTkyZDk2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDEwMDIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYjE0YzRhMjAxMmQzMDk0MDA0MGI3ZDEzNWM2YmUxMGViYzZmODRjMWM5ZTVmMzg4OTdlODhjN2QyNzQyOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9kI02D3n4gOm8oYn4ozfenKl09faCG0Of78XfyvPjTA)
> >       
> >         [
> >           
> >             ![动画](https://private-user-images.githubusercontent.com/56285360/329512013-8dc3df58-4bcc-473a-ac86-75b25de92d96.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDM2MjUsIm5iZiI6MTcyMzU0MzMyNSwicGF0aCI6Ii81NjI4NTM2MC8zMjk1MTIwMTMtOGRjM2RmNTgtNGJjYy00NzNhLWFjODYtNzViMjVkZTkyZDk2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDEwMDIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYjE0YzRhMjAxMmQzMDk0MDA0MGI3ZDEzNWM2YmUxMGViYzZmODRjMWM5ZTVmMzg4OTdlODhjN2QyNzQyOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9kI02D3n4gOm8oYn4ozfenKl09faCG0Of78XfyvPjTA)
> >           
> >         ](https://private-user-images.githubusercontent.com/56285360/329512013-8dc3df58-4bcc-473a-ac86-75b25de92d96.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDM2MjUsIm5iZiI6MTcyMzU0MzMyNSwicGF0aCI6Ii81NjI4NTM2MC8zMjk1MTIwMTMtOGRjM2RmNTgtNGJjYy00NzNhLWFjODYtNzViMjVkZTkyZDk2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDEwMDIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYjE0YzRhMjAxMmQzMDk0MDA0MGI3ZDEzNWM2YmUxMGViYzZmODRjMWM5ZTVmMzg4OTdlODhjN2QyNzQyOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9kI02D3n4gOm8oYn4ozfenKl09faCG0Of78XfyvPjTA)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/56285360/329512013-8dc3df58-4bcc-473a-ac86-75b25de92d96.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDM2MjUsIm5iZiI6MTcyMzU0MzMyNSwicGF0aCI6Ii81NjI4NTM2MC8zMjk1MTIwMTMtOGRjM2RmNTgtNGJjYy00NzNhLWFjODYtNzViMjVkZTkyZDk2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDEwMDIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYjE0YzRhMjAxMmQzMDk0MDA0MGI3ZDEzNWM2YmUxMGViYzZmODRjMWM5ZTVmMzg4OTdlODhjN2QyNzQyOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9kI02D3n4gOm8oYn4ozfenKl09faCG0Of78XfyvPjTA)
> >         
> >        [ ![动画](https://private-user-images.githubusercontent.com/56285360/329512013-8dc3df58-4bcc-473a-ac86-75b25de92d96.gif?
> > 请教下，动图中的： 用例，是怎么实现的

不太明白是什么意思
