### ISSUE TITLE
技术请教，怎么保证渲染的图形不重叠的

### ISSUE THREAD

**Issue by quanzhongxian** [wanglin2/mind-map#646]
我看是svg渲染的，怎么保证画出的矩形、线条不重叠，而且还有序

**Comment by wanglin2** [comment]
就是计算每个节点的位置，逻辑结构图可以看看这篇文章，https://juejin.cn/post/6987711560521089061#heading-4

对树有兴趣的还可以看看这篇：https://juejin.cn/post/7078563617079197727

**Comment by quanzhongxian** [comment]
@wanglin2 好的，谢谢
