### ISSUE TITLE
【使用体验】与【功能请求】：关于 样式、结构

### ISSUE THREAD

**Issue by 0400H** [wanglin2/mind-map#648]
之前一直在使用 [百度脑图](https://github.com/NaoTu/DesktopNaotu) 桌面版，拖拽类操作，只支持树状数据结构，不支持图数据结构（多个邻接节点）。

最近体验 [mind-map](https://github.com/wanglin2/mind-map) 发现同样是拖拽类操作，且支持图结构，准备转入，但也发现一些问题：

- 样式
  `mind-map`中加入了比拖拽类脑图软件更为丰富的类[drawio](https://github.com/jgraph/drawio) 的样式调节面板。
  但是遗憾的是，在节点样式与基础样式中都没有重置功能。对于专注于内容创作的作者使用时，如果误微调某个Node的样式，可能无法很好地找到并与其它Node的默认样式对齐。
  是否可以为以上两个选项中加入重置按钮？

- 节点与边
  根据目前添加节点的逻辑看起来，只能添加子节点和兄弟节点，是树的逻辑。
  当为同个节点添加多个入边时，一条边为实线，其它边为带箭头的虚线；节点只与父节点对齐。
  能否统一入边的样式，并使得该节点处于多个入边的中心位置？
  能否添加 不带有边的 节点？

- 结构
  在 `mind-map` 支持 节点上下文（基础样式中的使用拖拽） 和 全局 结构。
  对于 节点上下文 结构，同样不支持重置，在 切换 全局结构时会出现节点重合等情况。
  对于 全局 结构，提供了树相关的结构，能否应该添加一些基于图的优化结构？
  例如根据叶节点 智能排布为环状发散结构, 可以参考 [graphviz](https://graphviz.org/docs/layouts/) 的 [neato](https://graphviz.org/docs/layouts/neato/) 与 [circo](https://graphviz.org/docs/layouts/circo/)
  翻看了下Doc，`mind-map` 是一个以树数据结构为基础的图编辑器，后续是否可能将基础数据结构改为图？

**Comment by wanglin2** [comment]
定位只是思维导图，不会支持图相关的功能，至于样式，右键菜单中有垂直的按钮，自由拖拽后右键菜单中也有一键整理布局的按钮
