### ISSUE TITLE
在‘data_change_detail’事件中，如果进行了删除、新增操作，返回的更改数据列表有误

### ISSUE THREAD

**Issue by huang-yf3160** [wanglin2/mind-map#649]
在‘data_change_detail’事件中，如果进行了删除、新增操作，返回的更改数据列表有误

初步定位是因为：进行删除节点操作后，节点的选中状态会变化，例如删除了子节点，选中态会变更到父节点上

导致去判断新旧数据时，父节点也被判断变更了

**Comment by misakichan** [comment]
我感觉是设计如此，父节点虽然本身没变，但是父节点的children变了。如果data_change_detail不给的话，就不好判断是哪个节点下的节点被操作了

**Comment by quanzhongxian** [comment]
我觉得设计就是这样的，当然你可以过滤掉父节点

**Comment by wanglin2** [comment]
设计如此，不是因为选中状态改变了，而是因为子节点数量改变了
