### ISSUE TITLE
[Bug] 编程插入节点，和插入顺序不一致

### ISSUE THREAD

**Issue by pinghe** [wanglin2/mind-map#652]
使用 execCommand INSERT_NODE 插入节点，调用三次，插入三个节点 1，2，3，呈现出来是 3，2，1 顺序不一致

**Comment by wanglin2** [comment]
发一下调用的代码截图看看，我试了一下，如果是对当前激活的节点依次调三次是没问题的，如果你是对同一个节点连续调三次，那顺序确实是反的，因为都是在该节点相邻位置插入新节点，
![image](https://github.com/wanglin2/mind-map/assets/17272433/e4ca0b06-673b-43c9-afe5-c8303a5c11e7)

**Comment by pinghe** [comment]
感谢。明白了

**Comment by pinghe** [comment]
能否支持 .then 方法呢

**Comment by wanglin2** [comment]
> 能否支持 .then 方法呢

什么支持.then方法

**Comment by pinghe** [comment]
promise 模式，确保节点创建完成，再执行下一个创建

**Comment by wanglin2** [comment]
> promise 模式，确保节点创建完成，再执行下一个创建

这个目前实现不了
