### ISSUE TITLE
问题反馈：如果节点的子节点都是同一个节点（id相同），连线排版问题不太好看

### ISSUE THREAD

**Issue by quanzhongxian** [wanglin2/mind-map#653]
![Snipaste_2024-05-17_08-37-01](https://github.com/wanglin2/mind-map/assets/84429231/63253cbc-6825-4df2-9b91-7f5ac29137ab)

**Comment by quanzhongxian** [comment]
![Snipaste_2024-05-17_11-03-12](https://github.com/wanglin2/mind-map/assets/84429231/e82fb541-1c3a-4c7a-8384-2222acbb5884)

**Comment by wanglin2** [comment]
这种方式是不被支持的，思维导图节点只有一个父节点，如果你想当做流程图使用，那么需要自己修改
