### ISSUE TITLE
移动端不能进行画布手势缩放吗

### ISSUE THREAD

**Issue by Yogors** [wanglin2/mind-map#656]
移动端不画布手势缩放时会直接放大整个浏览器，而不是单纯画布内容放大缩小

**Comment by wanglin2** [comment]
可以缩放，有的浏览器可能双指缩放时会进行页面缩放，已修复，v0.9.13+生效

**Comment by wanglin2** [comment]
因为修复这个问题导致出现了更大的问题，所以v0.10.1+会回退，这个问题只能通过修改浏览器配置来禁止手势操作来解决
