### ISSUE TITLE
缺陷反馈：禁用模式下仍可编辑

### ISSUE THREAD

**Issue by misakichan** [wanglin2/mind-map#660]
复现路径：
1、将脑图设置为禁用（只读）模式
2、按住ctrl键后点击节点可以选中节点，此时按tab或者delete均可以生效

<img width="1062" alt="image" src="https://github.com/wanglin2/mind-map/assets/16569274/ce5c4485-409e-4423-adbf-29b6da9638ea">

**Comment by misakichan** [comment]
不改动源码的前提下，临时解决方案
<img width="514" alt="image" src="https://github.com/wanglin2/mind-map/assets/16569274/04356e52-f064-4856-9994-cc90c112dfbf">

**Comment by wanglin2** [comment]
已修复，v0.9.13+生效
