### ISSUE TITLE
图片拖拽时候会把页面上的文字给选中

### ISSUE THREAD

**Issue by HongFei1998** [wanglin2/mind-map#662]
如下图
![image](https://github.com/wanglin2/mind-map/assets/32254020/293e55ba-54ea-4dd4-9008-25855dc7683d)

**Comment by HongFei1998** [comment]
移动画布也会出现这种情况（大幅度动鼠标复现）

**Comment by pinghe** [comment]
我也遇到同样的问题

**Comment by wanglin2** [comment]
已修复，v0.9.13+版本生效
