### ISSUE TITLE
缺失 is-wsl

### ISSUE THREAD

**Issue by pinghe** [wanglin2/mind-map#664]
open 包建议替换为 shell.openPath()

https://www.npmjs.com/package/open
This is meant to be used in command-line tools and scripts, not in the browser.

If you need this for Electron, use [shell.openPath()](https://www.electronjs.org/docs/api/shell#shellopenpathpath) instead.

This package does not make any security guarantees. If you pass in untrusted input, it's up to you to properly sanitize it.

**Comment by wanglin2** [comment]
已替换
