### ISSUE TITLE
【节点收起与展开问题】：使用showChildren方法未生效

### ISSUE THREAD

**Issue by quanzhongxian** [wanglin2/mind-map#665]
当一开始渲染，默认所有都为未展开（expand:false），渲染完成后，调用  this.activeNodes.forEach((item)=>{ item.showChildren() })，方法节点并没有展开。我估计是，这个节点的子节点还没有创建，所有没有展开。还有就是当点击减号图标收起所有节点时，调用展开的方法也不行，应该还是那个问题（子节点没有了）。

**Comment by quanzhongxian** [comment]
所以，想要的是调用这个方法，如果节点没有创建就给他创建并展开

**Comment by wanglin2** [comment]
设置节点展开要使用命令
![image](https://github.com/wanglin2/mind-map/assets/17272433/b07a2e5e-8382-4eaf-be3c-bce5e0331504)

show方法并不会展开节点
