### ISSUE TITLE
新建文件后，旧文件丢失

### ISSUE THREAD

**Issue by Huiguorou12** [wanglin2/mind-map#669]
大佬，我在网页端点了新建后，原来正在编辑的导图不见了啊啊啊！我哭
![00E35C68](https://github.com/wanglin2/mind-map/assets/110574680/c03ddd57-48bd-4216-a13b-e3f45fe3b8e3)
！有什么办法找回吗
![00E3E222](https://github.com/wanglin2/mind-map/assets/110574680/e6de561e-47f4-4620-bbca-8e83143e129d)

**Comment by wanglin2** [comment]
回不来了，下个版本增加一个提示好了

**Comment by Huiguorou12** [comment]
好吧😥555555～



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年06月03日 09:19 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [wanglin2/mind-map] 新建文件后，旧文件丢失 (Issue #669) |

回不来了，下个版本增加一个提示好了
