### ISSUE TITLE
【展开收缩节点性能问题】500~600个节点，收缩 超过10秒

### ISSUE THREAD

**Issue by quanzhongxian** [wanglin2/mind-map#671]
![wt](https://github.com/wanglin2/mind-map/assets/84429231/31d08f0c-9763-4133-bb5a-197f753b8829)

**Comment by quanzhongxian** [comment]
v0.9.13+ 大概什么时候更新呢

**Comment by wanglin2** [comment]
你用的哪个版本，12秒太夸张了，2000个节点也不可能这么慢

**Comment by quanzhongxian** [comment]
最新版本 @wanglin2

**Comment by quanzhongxian** [comment]
先展开所有节点，然后选择一个所起它的子节点，就是这样，很慢，节点100左右就快一点

**Comment by quanzhongxian** [comment]
我找到原因了，是一个富文本编辑器渲染后造成的 @wanglin2 ，不是你们插件原因

**Comment by wanglin2** [comment]
下个版本这周会更新
