### ISSUE TITLE
移动端双指缩放范围无法控制

### ISSUE THREAD

**Issue by yangyuxin21-tal** [wanglin2/mind-map#676]

**Comment by wanglin2** [comment]
没听懂，麻烦详细描述一下

**Comment by yangyuxin21-tal** [comment]
就是希望能在touchEvent插件中提供api，可以传入画布可以缩放的比例，达到可以控制最大和最小的缩放范围

**Comment by wanglin2** [comment]
新增了minTouchZoomScale和maxTouchZoomScale两个实例化选项，v0.10.1+生效
