### ISSUE TITLE
如何监听节点移动事件(上移、下移节点)

### ISSUE THREAD

**Issue by ES-2077** [wanglin2/mind-map#679]
如何监听节点移动事件(上移、下移节点)
之前使用data_change_detail监听更新的变动，但上移下移节点时发现data_change_detail只返回了一个node，不太方便区分是哪种类型。

**Comment by shuangru-momenta** [comment]
如果是通过拖动节点的上移下移，可以根据 node_dragend 事件判断

**Comment by wanglin2** [comment]
data_change_detail事件可以判断啊，对比一下子节点的顺序应该就可以了
