### ISSUE TITLE
请问有什么方法可以拦截拖动事件吗？当前的回调方法无法通过返回值限制图表更新。

### ISSUE THREAD

**Issue by shuangru-momenta** [wanglin2/mind-map#680]
我们使用mind-map管理了一个树状的数据，需要在各个修改数据的环节增加卡控能力。
增加节点/删除节点/编辑节点 都可以做到，

但是拖动节点改变节点顺序和拖动节点改变节点父子级关系，无法进行拦截。
无法进行二次确认，也无法实现在数据更新后再更新视图。

请问是否可以支持。on('node_dragend') 方法的回调函数根据返回值控制拖拽行为是否生效；

**Comment by wanglin2** [comment]
新增了实例化选项beforeDragEnd来拦截，v0.10.1+生效
