### ISSUE TITLE
在根节点使用‘/’快捷键，收缩根节点时，没有展示子节点数量

### ISSUE THREAD

**Issue by huang-yf3160** [wanglin2/mind-map#686]
在根节点使用‘/’快捷键，收缩根节点时，没有展示子节点数量

解决方案1: 切换激活节点的展开状态时，先判断是否是根节点
解决方案2: 显示子节点数量和expand按钮

**Comment by wanglin2** [comment]
已修复，根节点不允许收起，v0.10.1+生效
