### ISSUE TITLE
Demo补充

### ISSUE THREAD

**Issue by misakichan** [wanglin2/mind-map#687]
0.9.12+增加的节点前后追加自定义内容功能：createNodePostfixContent
希望可以在demo或者文档里介绍一下具体用法，现在尝试通过DOMParser将字符串转为dom对象塞过去是用不了的

**Comment by wanglin2** [comment]
如果你直接塞的是domparser.parseFromString方法的返回值，那是不行的，因为它返回的是完整的html文档，得返回文档中的节点才行。

**Comment by wanglin2** [comment]
web demo中已增加示例，v0.10.2+生效
