### ISSUE TITLE
请问一下这个支持拖拽节点放到不同的方向吗？我好像没在文档中看到

### ISSUE THREAD

**Issue by ZzYAmbition** [wanglin2/mind-map#690]
![image](https://github.com/wanglin2/mind-map/assets/54825098/b37d3867-d347-401d-801b-42036cfabbd7)
![image](https://github.com/wanglin2/mind-map/assets/54825098/6537b412-fdda-4bee-b893-350c2984495e)

如图1到图2所示的这种功能，可用把右边的节点拖拽到左边

**Comment by wanglin2** [comment]
拖拽改变节点的层级是可以的，改变方向是不行的，结构只有固定的几种
