### ISSUE TITLE
问题反馈：异常框选效果

### ISSUE THREAD

**Issue by misakichan** [wanglin2/mind-map#699]
当用户在节点内按住鼠标框选时，可以跨节点框选多个节点的文本。
且该种情况出现后需要用户点击节点内部才能取消
<img width="465" alt="image" src="https://github.com/wanglin2/mind-map/assets/16569274/5e145b43-0ba1-49f2-ae02-ae1c661786e6">

<img width="788" alt="image" src="https://github.com/wanglin2/mind-map/assets/16569274/60cd93fe-afd4-40b7-8e10-743c0db8a594">

**Comment by wanglin2** [comment]
相同问题：https://github.com/wanglin2/mind-map/issues/697
