### ISSUE TITLE
AI如何实时生成思维导图

### ISSUE THREAD

**Issue by nickolboy** [wanglin2/mind-map#702]
文档里有提到实现AI生成节点内容，但好像是一个节点一个节点更新，而且还是json的
AI输出的一般是markdown的，输出上并不是像json一样递归的
有方法能将markdown的数据实时更新到思维导图上吗，而且一个字一个字的输出

**Comment by wanglin2** [comment]
markdown转json需要自己实现，一个个字不推荐，很耗性能

**Comment by misakichan** [comment]
> markdown转json需要自己实现，一个个字不推荐，很耗性能

对，我们现在也是等节点出来了之后，再一批批的给前端
