### ISSUE TITLE
请支持自定义备注图标，还希望为这个图标加上点击事件

### ISSUE THREAD

**Issue by quanzhongxian** [wanglin2/mind-map#703]
原因是可能使用者定义图标不叫备注，可能叫超链接，图标可能不太符合，还希望为这个图标加上点击事件。比如我希望点击图标出现弹窗

**Comment by wanglin2** [comment]
可以考虑使用
![image](https://github.com/wanglin2/mind-map/assets/17272433/93cf9e11-ab31-4bad-a291-ce19eff2b8a6)
这个配置来实现你的需求
