### ISSUE TITLE
为啥设置不了样式

### ISSUE THREAD

**Issue by quanzhongxian** [wanglin2/mind-map#707]
![image](https://github.com/wanglin2/mind-map/assets/84429231/a8675f64-a2e6-42b1-b709-69e46776863f)

**Comment by quanzhongxian** [comment]
![image](https://github.com/wanglin2/mind-map/assets/84429231/46f25378-1f69-41ff-b4c7-aba5e54f0a1e)

**Comment by wanglin2** [comment]
SET_NODE_STYLE命令不支持设置多个节点

**Comment by wanglin2** [comment]
设置多个用SET_NODE_STYLES命令

**Comment by quanzhongxian** [comment]
![image](https://github.com/wanglin2/mind-map/assets/84429231/ef684bdb-fd3c-4963-9d39-48026b07739b)
也不生效

**Comment by quanzhongxian** [comment]
@wanglin2 
![image](https://github.com/wanglin2/mind-map/assets/84429231/ab3d6acf-9f2d-4c6a-929f-eff7fe5477e8)
也不生效

**Comment by wanglin2** [comment]
SET_NODE_STYLE和SET_NODE_STYLES命令都不支持同时给多个节点设置样式，这里chuan传数组是没用的

**Comment by wanglin2** [comment]
![image](https://github.com/wanglin2/mind-map/assets/17272433/86569510-b831-49a7-9676-969301291b73)
