### ISSUE TITLE
地图组件问题

### ISSUE THREAD

**Issue by huang-yf3160** [wanglin2/mind-map#716]
1. 在小地图上拖拽选中区域时，不应该选中区域会变化，很难操作
2. 小地图上拖拽时，鼠标移动到外部，还在响应事件，会很影响交互

可以参照 https://g6.antv.antgroup.com/zh/examples/tool/minimap/#imageMinimap antvg6 miniMap的操作逻辑

**Comment by wanglin2** [comment]
新增了小地图内视图框的拖拽。v0.10.2+生效
