### ISSUE TITLE
节点数量1000左右，全部展开节点，点击去激活节点有明显卡顿，全部收缩之后，点击也有卡顿，并且收缩单个节点也有卡顿

### ISSUE THREAD

**Issue by quanzhongxian** [wanglin2/mind-map#721]

**Comment by wanglin2** [comment]
是这样的

**Comment by quanzhongxian** [comment]
@wanglin2 可不可以在可视区域内才渲染，不在可视区域的内的就不渲染

**Comment by wanglin2** [comment]
> @wanglin2 可不可以在可视区域内才渲染，不在可视区域的内的就不渲染

想法是美好的，实际是很难做到的。

**Comment by quanzhongxian** [comment]
@wanglin2 现在展开与收缩都触发node_tree_render_end，不知道是不是全部节点都渲染，才导致渲染慢？哪一个收缩或者展开就渲染哪一个，每个svg的g标签都保存uid,找起来应该挺快的，g标签的顺序应该不影响渲染吧，不知道行不行

**Comment by quanzhongxian** [comment]
可能我想的太简单了，哈哈哈

**Comment by quanzhongxian** [comment]
前面的节点应该不用计算了，间隔不用管，不知道行不行

**Comment by wanglin2** [comment]
> 前面的节点应该不用计算了，间隔不用管，不知道行不行

实际上现在就是这样的，数据没有更新的节点都是不会重新创建的，不然慢到你无法想象

**Comment by wanglin2** [comment]
0.10.4版本增加了优化了一下性能，可以在在线demo里试试，
![image](https://github.com/user-attachments/assets/7ea42803-6353-49a3-8f65-6f3387b4d390)

**Comment by quanzhongxian** [comment]
> 0.10.4版本增加了优化了一下性能，可以在在线demo里试试， ![image](https://private-user-images.githubusercontent.com/17272433/352347453-7ea42803-6353-49a3-8f65-6f3387b4d390.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NjIyNzgsIm5iZiI6MTcyMTk2MTk3OCwicGF0aCI6Ii8xNzI3MjQzMy8zNTIzNDc0NTMtN2VhNDI4MDMtNjM1My00OWEzLThmNjUtNmYzMzg3YjRkMzkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDAyNDYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlOTQ1NzczNjA1NDJkNDFkZGJkNmJkZDYwMmUyNjA2NzZmNDczOWI1OGY5Mjc5YmRhYTExNWVkZWRmYzI5NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.widNVIlnfknxZIXE7JxvFZf9eppTkJOVLDlcLVVSBts)

确实快了

**Comment by quanzhongxian** [comment]
> 0.10.4版本增加了优化了一下性能，可以在在线demo里试试， ![image](https://private-user-images.githubusercontent.com/17272433/352347453-7ea42803-6353-49a3-8f65-6f3387b4d390.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NjY0NzUsIm5iZiI6MTcyMTk2NjE3NSwicGF0aCI6Ii8xNzI3MjQzMy8zNTIzNDc0NTMtN2VhNDI4MDMtNjM1My00OWEzLThmNjUtNmYzMzg3YjRkMzkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDAzNTYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5ZmUwNDEwMmM3ZTNmYjVlNjkzNWU3ZmU0OGZmN2QyMTUxZWU5MzgwMWUzMDUxNWMwYjA3ZWFmNDJkMTZmNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3TEuv2P5hzKrSdJ0yy3taquTcZzNbQcG2e0A40TwlYE)

但是为啥npm i simple-mind-map ，还是下载0.10.3版本的
