### ISSUE TITLE
使用快捷键添加节点的时候rich_text_selection_change事件没有触发，只有双击会触发

### ISSUE THREAD

**Issue by DerrickTel** [wanglin2/mind-map#723]
【before_show_text_edit】事件是否可以返回节点的位置信息？我需要添加一个弹窗。目前很难办到

**Comment by quanzhongxian** [comment]
@DerrickTel 直接使用激活节点获取位置信息就行了，你点击的时候这个节点肯定是激活了

**Comment by DerrickTel** [comment]
> @DerrickTel 直接使用激活节点获取位置信息就行了，你点击的时候这个节点肯定是激活了

点击之后，又点击的时候就不会触发了

**Comment by quanzhongxian** [comment]
> > @DerrickTel 直接使用激活节点获取位置信息就行了，你点击的时候这个节点肯定是激活了
> 
> 点击之后，又点击的时候就不会触发了

你点击节点肯定是激活了，再次点击节点也是激活状态，除非点击画布或者点击其它节点，否则这个节点还是激活的，不是有个监听方法，然后使用数组保留着激活的节点吗

**Comment by DerrickTel** [comment]
> > > @DerrickTel 直接使用激活节点获取位置信息就行了，你点击的时候这个节点肯定是激活了
> > 
> > 
> > 点击之后，又点击的时候就不会触发了
> 
> 你点击节点肯定是激活了，再次点击节点也是激活状态，除非点击画布或者点击其它节点，否则这个节点还是激活的，不是有个监听方法，然后使用数组保留着激活的节点吗

再点击那个监听不执行了....

**Comment by quanzhongxian** [comment]
> > > > @DerrickTel 直接使用激活节点获取位置信息就行了，你点击的时候这个节点肯定是激活了
> > > 
> > > 
> > > 点击之后，又点击的时候就不会触发了
> > 
> > 
> > 你点击节点肯定是激活了，再次点击节点也是激活状态，除非点击画布或者点击其它节点，否则这个节点还是激活的，不是有个监听方法，然后使用数组保留着激活的节点吗
> 
> 我想拿到哪个节点的位置，然后放一个我的弹窗，数组的话我位置会乱。我现在是用的作者的方案

我一直都是用激活节点的方法，因为我这边最多只能激活应该节点，实现也没有问题

**Comment by DerrickTel** [comment]
> > > @DerrickTel 直接使用激活节点获取位置信息就行了，你点击的时候这个节点肯定是激活了
> > 
> > 
> > 点击之后，又点击的时候就不会触发了
> 
> 这个再次点击不触发也没关系，因为数组已经保留了这个节点

我这里有一个需求，就是快捷键出来的节点也需要有弹窗，这样的会不会激活？

**Comment by quanzhongxian** [comment]
> > > > @DerrickTel 直接使用激活节点获取位置信息就行了，你点击的时候这个节点肯定是激活了
> > > 
> > > 
> > > 点击之后，又点击的时候就不会触发了
> > 
> > 
> > 这个再次点击不触发也没关系，因为数组已经保留了这个节点
> 
> 我这里有一个需求，就是快捷键出来的节点也需要有弹窗，这样的会不会激
默认不就是激活当前创建的节点吗，你看节点高亮就是已经激活了

**Comment by wanglin2** [comment]
刚创建的节点不会触发rich_text_selection_change事件，如果有需要，可以自己再监听一下quill的事件，可以参考：https://github.com/wanglin2/mind-map/blob/main/simple-mind-map/src/plugins/RichText.js#L394

**Comment by quanzhongxian** [comment]
> > > > @DerrickTel 直接使用激活节点获取位置信息就行了，你点击的时候这个节点肯定是激活了
> > > 
> > > 
> > > 点击之后，又点击的时候就不会触发了
> > 
> > 
> > 这个再次点击不触发也没关系，因为数组已经保留了这个节点
> 
> 我这里有一个需求，就是快捷键出来的节点也需要有弹窗，这样的会不会激活？

认不就是激活当前创建的节点吗，你看节点高亮就是已经激活了

**Comment by quanzhongxian** [comment]
> > > > @DerrickTel 直接使用激活节点获取位置信息就行了，你点击的时候这个节点肯定是激活了
> > > 
> > > 
> > > 点击之后，又点击的时候就不会触发了
> > 
> > 
> > 这个再次点击不触发也没关系，因为数组已经保留了这个节点
> 
> 我这里有一个需求，就是快捷键出来的节点也需要有弹窗，这样的会不会激活？

mindMap.on('node_active', (node, activeNodeList) => {
    activeNodes = activeNodeList
}) ，激活节点都在activeNodes 数组啊，这样不用管接听了，随时拿activeNodes 值就行。
