### ISSUE TITLE
新建节点之前是否考虑添加拦截事件

### ISSUE THREAD

**Issue by congcongluren** [wanglin2/mind-map#724]
我有一个场景，在新建节点之前，需要后端生成一个uid 和一些默认值，然后根据后端这个uid生成节点。

**Comment by wanglin2** [comment]
可以调完接口后再调用创建节点的命令，传入uid和其他数据：
![image](https://github.com/wanglin2/mind-map/assets/17272433/d91cb016-9de4-47d6-b96a-5f5ab0ab6a5f)

快捷键的话可以覆盖，https://wanglin2.github.io/mind-map/#/doc/zh/keyCommand

**Comment by congcongluren** [comment]
感谢大佬的意见，我尝试一下
