### ISSUE TITLE
标签的颜色或者说样式要如何配置？

### ISSUE THREAD

**Issue by DerrickTel** [wanglin2/mind-map#727]
如题

**Comment by wanglin2** [comment]
只有这一个配置，
![image](https://github.com/wanglin2/mind-map/assets/17272433/7939e92e-b905-498e-9ddc-0998e4574944)

要动态切换标签颜色不太行

**Comment by DerrickTel** [comment]
我想给标签加圆角之类的要怎么加？直角太僵硬了

**Comment by wanglin2** [comment]
这个目前不支持

**Comment by DerrickTel** [comment]
请问一下什么时候可以配置一下tag的样式，我主要是想加一下圆形的tag

**Comment by DerrickTel** [comment]
@wanglin2 

> 请问一下什么时候可以配置一下tag的样式，我主要是想加一下圆形的tag

**Comment by wanglin2** [comment]
下个版本可能会加，几个星期以后把
