### ISSUE TITLE
使用鼠标滚轮操作后，就不能再使用任何键盘快捷键的问题

### ISSUE THREAD

**Issue by w1025872892** [wanglin2/mind-map#729]
问题版本是0.10.2，只要使用鼠标滚轮缩小放大操作后，就不能再使用任何键盘操作，比如enter建立同级节点、tab建立下一级节点、delete删除节点等等操作都无效了，要关闭文件再打开才行。

**Comment by wanglin2** [comment]
已修复，v0.10.3+生效
