### ISSUE TITLE
功能建议：Node实例支持插入自定义数据对象

### ISSUE THREAD

**Issue by suka233333** [wanglin2/mind-map#73]
目前Node节点支持备注，标签，图表，超链接等等数据。如果能支持插入自定义数据对象的话，感觉灵活度与易用度可以更高。
例如，插入 “评价” 数据对象
Node节点上可以显示自定义的图标，例如：
![image](https://user-images.githubusercontent.com/115850846/221148107-303cb362-2291-4545-867a-c2716722e381.png)
并且，可以暴露出mousemove,click等等常用事件来供二次开发具体功能
谢谢大佬的项目，很好用，拜读了掘金的实现思路，很厉害。
------------------------------------------------------------------
顺便想要请教下，单个Node实例有mousemove事件么，没有在文档上找到，如果没有的话，请教一下有什么思路可以获取呢

**Comment by wanglin2** [comment]
你好，后续会尝试开放自定义节点的功能，大概是使用svg的foreignObject标签嵌入自定义的html。
mousemove事件是什么场景下需要呢？

**Comment by suka233333** [comment]
> 你好，后续会尝试开放自定义节点的功能，大概是使用svg的foreignObject标签嵌入自定义的html。 mousemove事件是什么场景下需要呢？
最近在基于您的包二次开发思源笔记的思维导图插件，其中有项想要实现的功能是：鼠标指向超链接，如果这个超链接指向思源笔记内部的某一段文字或者某一个文档，那么就调用思源笔记的api，直接悬浮展示指向的那个文档。
以下是视频说明，大概在39秒前后：
[视频描述](https://b3logfile.com/file/2023/02/%E8%B6%85%E9%93%BE%E6%8E%A5-DNl6bdw.mp4)
----------------------------------------------------------------------------------------------------------------
发现最新版本节点支持富文本了，请问节点支持markdown吗，这样，单个节点就可以有多个不同的超链接可以进行跳转到不同的地方了

**Comment by suka233333** [comment]
> 你好，后续会尝试开放自定义节点的功能，大概是使用svg的foreignObject标签嵌入自定义的html。 mousemove事件是什么场景下需要呢？




最近在基于您的包二次开发思源笔记的思维导图插件，其中有项想要实现的功能是：鼠标指向超链接，如果这个超链接指向思源笔记内部的某一段文字或者某一个文档，那么就调用思源笔记的api，直接悬浮展示指向的那个文档。
以下是视频说明，大概在39秒前后：
[视频描述](https://b3logfile.com/file/2023/02/%E8%B6%85%E9%93%BE%E6%8E%A5-DNl6bdw.mp4)

发现最新版本节点支持富文本了，请问节点支持markdown吗，这样，单个节点就可以有多个不同的超链接可以进行跳转到不同的地方了

**Comment by wanglin2** [comment]
如果数据是你自己控制的话，直接创建a标签就可以了：
`{
                        "data": {
                            "text": `<a href="http://lxqnsys.com/" target="_blank">理想去年实验室</a>`,
                            "richText": true
                        },
                        "children": []
                    }`

**Comment by suka233333** [comment]
> 如果数据是你自己控制的话，直接创建a标签就可以了： <img alt="image" width="845" src="https://user-images.githubusercontent.com/17272433/221341864-da6828d1-1419-4eb6-a92b-9b0eb3ec5bcf.png">


了解了 ，感谢
