### ISSUE TITLE
节点拖拽问题探讨

### ISSUE THREAD

**Issue by DerrickTel** [wanglin2/mind-map#732]
目前在节点拖拽的时候只有将节点拖入某个节点的整个div内才可以完成整个拖拽的动作，是否可以将范围扩大？或者说哪里可以配置？

**Comment by wanglin2** [comment]
目前是以鼠标移入节点判断的，不是你说的以节点

**Comment by DerrickTel** [comment]
> 目前是以鼠标移入节点判断的，不是你说的以节点

怎么配置将范围扩大？我看了一下文档没有这方面的配置，如果要直接改Drag.js 文件的话，大概是在什么地方修改？能不能帮忙给点建议？

**Comment by wanglin2** [comment]
不支持配置，可以试试修改checkIsOverlap方法
