### ISSUE TITLE
节点添加概要后，还能继续添加概要

### ISSUE THREAD

**Issue by huang-yf3160** [wanglin2/mind-map#734]
节点添加概要后，还能继续添加概要

预期：该节点添加概要后，不能继续添加

**Comment by wanglin2** [comment]
同一个节点只能添加一个概要啊

**Comment by huang-yf3160** [comment]
> 同一个节点只能添加一个概要啊

多个相同的节点，还能添加多个概要

**Comment by wanglin2** [comment]
> > 同一个节点只能添加一个概要啊
> 
> 多个相同的节点，还能添加多个概要

多个相同节点是啥意思

**Comment by huang-yf3160** [comment]
> > > 同一个节点只能添加一个概要啊
> > 
> > 
> > 多个相同的节点，还能添加多个概要
> 
> 多个相同节点是啥意思

![test](https://github.com/wanglin2/mind-map/assets/56285360/7fd29d0e-a1c3-470f-8c39-37a7a8277a36)

选中多个节点，能一直添加概要

**Comment by wanglin2** [comment]
已修复，v0.10.3+版本生效
