### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by tingjiangcao** [wanglin2/mind-map#737]
首先我想表达我的喜欢和肯定。

库本身功能已经很强大了。我觉得应该回归一下，多关注“基础功能体验”。

这里面我最想提出来的就是“动画”。设计原则上讲，画布里所有元素的“出现、消失、移动、折叠” 都应该是“有理由的动画渐现”
如果想感受一下什么区别，可以关注一下mac上的mindnode 或者 markmap库 的动画。

**Comment by wanglin2** [comment]
动画不会考虑，因为本来性能就不太好，加上动画会卡上加卡

**Comment by quanzhongxian** [comment]
@wanglin2 确实我也觉得功能已经足够了，优化一下性能，可能比较好
