### ISSUE TITLE
0.10.2版本后，插件监听了window的鼠标移动事件，阻止了默认行为。导致画布外文本框内容无法选择；

### ISSUE THREAD

**Issue by wangji1042** [wanglin2/mind-map#740]
0.10.2版本后，插件监听了window的鼠标移动事件，阻止了默认行为。导致画布外文本框内容无法选择；
希望能够改进一下，改为可配置是否阻止默认行为；或者把监听范围限制在画布内，不影响画布外的dom元素；

<img width="729" alt="20240712141503" src="https://github.com/user-attachments/assets/ea6e3215-81ba-4de1-b98b-05c2ed1a3542">

**Comment by wanglin2** [comment]
我的在线demo里画布外可以选中啊

**Comment by wanglin2** [comment]
已删除默认阻止的代码，v0.10.6+生效
