### ISSUE TITLE
数学公式导出时节点框收缩遮掩部分数学符号

### ISSUE THREAD

**Issue by idealkindom** [wanglin2/mind-map#741]
![1](https://github.com/user-attachments/assets/add5482d-5182-46c4-a571-24cecbbd9dbf)
如图，导出svg图时就会出现这种情况，节点框比在窗口时中貌似收缩了，导致数学符号被遮挡

**Comment by wanglin2** [comment]
你有设置resetCss实例化选项么

**Comment by idealkindom** [comment]
您说的这个设置是指浏览器吗？？在软件里我没找到诶

在 2024-07-15 09:30:28，"街角小林" ***@***.***> 写道：


你有设置resetCss实例化选项么

**Comment by idealkindom** [comment]
另外我换了个电脑之后，用edge打开导出的带数学公式的svg，发现全都显示的latex码，而不像我笔记本电脑上正常显示，这又是什么设置原因呢？

在 2024-07-15 09:30:28，"街角小林" ***@***.***> 写道：


你有设置resetCss实例化选项么

**Comment by idealkindom** [comment]
用的离线程序 0.10.2版本

在 2024-07-15 16:36:45，"街角小林" ***@***.***> 写道：


你用的是在线版么，什么浏览器上使用

**Comment by wanglin2** [comment]
客户端么

**Comment by idealkindom** [comment]
对，客户端。

在 2024-07-15 16:38:50，"街角小林" ***@***.***> 写道：


客户端么

**Comment by wanglin2** [comment]
![image](https://github.com/user-attachments/assets/e92849aa-7472-4aba-8cd4-8505072feff2)

![image](https://github.com/user-attachments/assets/6628aefa-5987-4e95-aba2-9fe155876258)

这两张图，哪张是你遇到的现象

**Comment by idealkindom** [comment]
> ![image](https://private-user-images.githubusercontent.com/17272433/348668383-e92849aa-7472-4aba-8cd4-8505072feff2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNTM0NTQsIm5iZiI6MTcyMTA1MzE1NCwicGF0aCI6Ii8xNzI3MjQzMy8zNDg2NjgzODMtZTkyODQ5YWEtNzQ3Mi00YWJhLThjZDQtODUwNTA3MmZlZmYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDE0MTkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyZmUxZTMwZGI0MDZiNGRmNDlhOWI0NzgwNTQ2MzlhYmNjNDljMjlmNGZkYTg0NTMxZWMwM2Y4NGUxM2FiZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TpEh_FHZoEarBGFt0CiR-sKqEtM_JqYuFO3Ez1icPWY)
> 
> ![image](https://private-user-images.githubusercontent.com/17272433/348668435-6628aefa-5987-4e95-aba2-9fe155876258.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNTM0NTQsIm5iZiI6MTcyMTA1MzE1NCwicGF0aCI6Ii8xNzI3MjQzMy8zNDg2Njg0MzUtNjYyOGFlZmEtNTk4Ny00ZTk1LWFiYTItOWZlMTU1ODc2MjU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDE0MTkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4NjI4ODkxMjRhOGUwNmE2YmNhMGI1YTI4MTk5YjE3ZDBiMjQ2Njk5NGU2NmM5MGJmODMxYjc2NjBjMmU3MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7JevkppkZZccAay-_JicziH3RBGoeHxrY9vtIEPVY64)
> 
> 这两张图，哪张是你遇到的现象

我试了一下，可能是浏览器的原因。同一个svg文件在不同的浏览器，例如Edge和火狐中显示出来的效果就不同，一个正常，一个遮挡了部分公式。
但是工作的台式机上的Edge打开时数学公式显示为LaTex代码实在是无语。应该也是浏览器的原因。

**Comment by wanglin2** [comment]
稍微优化了一下公式公式问题

**Comment by idealkindom** [comment]
感谢！！

在 2024-07-18 10:14:00，"街角小林" ***@***.***> 写道：


稍微优化了一下公式公式问题
