### ISSUE TITLE
需求：希望可以在节点上面添加徽标数

### ISSUE THREAD

**Issue by DerrickTel** [wanglin2/mind-map#746]

**Comment by DerrickTel** [comment]
@wanglin2 大佬近期会有排期吗？还有https://github.com/wanglin2/mind-map/issues/745

**Comment by wanglin2** [comment]
徽标是啥

**Comment by DerrickTel** [comment]
> 徽标是啥

https://ant.design/components/badge-cn

**Comment by wanglin2** [comment]
这个感觉不是很必要，应该不会加

**Comment by DerrickTel** [comment]
> 这个感觉不是很必要，应该不会加

如果自己实现的话，有没有思路？

**Comment by wanglin2** [comment]
思路就是自己修改Node类

**Comment by DerrickTel** [comment]
> 思路就是自己修改Node类

我有一个想法你看看会不会成熟，把Tag的样式可以自定义。

**Comment by wanglin2** [comment]
> > 思路就是自己修改Node类
> 
> 我有一个想法你看看会不会成熟，把Tag的样式可以自定义。

节点标签已经支持设置一些样式了

**Comment by DerrickTel** [comment]
> > > 思路就是自己修改Node类
> > 
> > 
> > 我有一个想法你看看会不会成熟，把Tag的样式可以自定义。
> 
> 节点标签已经支持设置一些样式了

我看文档还没更新，有空的时候帮忙更新一下

**Comment by DerrickTel** [comment]
> > > 思路就是自己修改Node类
> > 
> > 
> > 我有一个想法你看看会不会成熟，把Tag的样式可以自定义。
> 
> 节点标签已经支持设置一些样式了

https://wanglin2.github.io/mind-map/#/
在线例子添加标签没反应。而且也没报错

**Comment by wanglin2** [comment]
更新了，
![image](https://github.com/user-attachments/assets/e8c09315-f86a-461f-86a6-83f86332b98d)

**Comment by wanglin2** [comment]
有反应的，你再研究下
