### ISSUE TITLE
BUG：使用node.setText来设置html标签，不生效

### ISSUE THREAD

**Issue by suka233333** [wanglin2/mind-map#75]
### 复现链接：
https://codesandbox.io/p/github/suka233/siyuan-Kmind/dev?file=%2Fsrc%2Fcomponents%2FNodeEditor%2Fcomponents%2FRichEditor%2FRichEditor.vue
### 复现步骤：
新建一个子节点 -点击 【备注】 按钮-点击 【设置node文本】 按钮
### 复现图片：
![Snipaste_2023-02-28_18-07-41](https://user-images.githubusercontent.com/115850846/221832610-a160fb16-245b-4ac9-95a0-c87593913ff1.png)

**Comment by wanglin2** [comment]
升级到`0.4.2`版本，然后这样试试`node.setText('xxx', true)`

**Comment by suka233333** [comment]
> 

试了一下，暂无问题了，感谢
