### ISSUE TITLE
如何让这个画布固定住

### ISSUE THREAD

**Issue by xuxiansdasjhd** [wanglin2/mind-map#750]
现在有个问题 我在网页上滚动 我只希望正常滚动页面 但是一滚动到画布，就只能在画布中滚动了。看了api只有zomm和move两个选项。

**Comment by wanglin2** [comment]
可以试试执行：mindMap.el.removeEventListener('wheel', mindMap.event.onMousewheel)

**Comment by xuxiansdasjhd** [comment]
解决了 ，谢谢作者。思维导图开发的很棒。期待能多出其他图👍
