### ISSUE TITLE
以图片的方式导出，节点中的图片不显示 （作者demo也是一样）

### ISSUE THREAD

**Issue by YAANLE** [wanglin2/mind-map#751]
图片地址 **https://anle163.com/dist/bg.png**    _这个是测试图片_

操作过程，使用 作者的[示例](https://wanglin2.github.io/mind-map/#/) 

1. 往节点中添加图片
![001](https://github.com/user-attachments/assets/3335794f-5799-4ad5-8572-ff184115607a)

2.以url的形式添加图片  地址为 **https://anle163.com/dist/bg.png** 
![002](https://github.com/user-attachments/assets/2167fe2b-a4b1-4938-8324-be5402aded3e)

3.shagn上传图片之后以以png格式导出
![003](https://github.com/user-attachments/assets/1223de8c-deae-4b17-912d-43d1ac8657d0)
![004](https://github.com/user-attachments/assets/b31f9e90-6b6f-4075-8418-0ad7fd266b8b)

5.导出之后 节点中的图片不显示
![005](https://github.com/user-attachments/assets/b40dc8c4-f799-48c5-bdfc-f2cd86800f33)

**Comment by wanglin2** [comment]
跨域图片可以显示无法导出。
