### ISSUE TITLE
导出为json功能时export功能报错

### ISSUE THREAD

**Issue by WINGSIGOD** [wanglin2/mind-map#755]
![image](https://github.com/user-attachments/assets/f8d87c37-99c8-4300-b06f-6a78df6942a1)
无论是exportjson还是png都报错
使用的是官方https://wanglin2.github.io/mind-map/#/doc/zh/course17/%E5%AF%BC%E5%85%A5代码示例
环境:
`  "dependencies": {
    "@toast-ui/editor": "^3.2.2",
    "axios": "^1.7.2",
    "pinia": "^2.1.7",
    "qs": "^6.12.3",
    "simple-mind-map": "^0.10.3",
    "unplugin-auto-import": "^0.18.0",
    "unplugin-vue-components": "^0.27.3",
    "vue": "^3.4.31",
    "vue-router": "^4.4.0",
    "vuex": "^4.1.0"
  },
  `

**Comment by wanglin2** [comment]
需要注册导出插件
