### ISSUE TITLE
请问一下，导图中，鼠标滚轮的默认事件可以拦截吗

### ISSUE THREAD

**Issue by suka233333** [wanglin2/mind-map#76]
当前的鼠标滚轮的默认事件是，向前滚动，缩小导图，向后滚动，放大导图。
请问可以拦截这个默认事件吗？如何可以的话，该怎么做呢？
原因有两个：
一是：现在有些鼠标有左右滚动，而源码中只判断了上下滚动，导致左右滚动总是会触发导图放大的效果；
![image](https://user-images.githubusercontent.com/115850846/223023174-cad05aaa-4f5d-4f41-bdc2-c9ab08caa909.png)

二是：因为想要自己自定义配置鼠标滚轮的事件，实现鼠标滚轮来调整导图的上下左右位置（类似xmind的操作习惯）

**Comment by wanglin2** [comment]
你好，暂时不支持，着急的话可以自己修改源码哈，不急的话可以等待下一个版本更新~

**Comment by suka233333** [comment]
> 你好，暂时不支持，着急的话可以自己修改源码哈，不急的话可以等待下一个版本更新~

好的~~感谢解答

**Comment by wanglin2** [comment]
已经增加了拦截的配置，另外鼠标滚动默认也支持切换成上下移动视图~

**Comment by wanglin2** [comment]
详见文档：https://wanglin2.github.io/mind-map/#/doc/zh/constructor/%E5%AE%9E%E4%BE%8B%E5%8C%96%E9%80%89%E9%A1%B9

**Comment by suka233** [comment]
> 已经增加了拦截的配置，另外鼠标滚动默认也支持切换成上下移动视图~

谢谢作者 ~· 太神速了~
