### ISSUE TITLE
桌面端，移动画布就会触发文件发生修改 处于未保存状态

### ISSUE THREAD

**Issue by liqiwenx** [wanglin2/mind-map#760]
如题，点击空白处移动画布，就会提示文件产生了修改，处于未保存状态。
桌面端0.10.2 版本

![image](https://github.com/user-attachments/assets/e8404127-5967-4247-8443-21b1b1f245ca)

**Comment by wanglin2** [comment]
是这样的，画布的位置也会保存和还原
