### ISSUE TITLE
配置厘设置  创建新节点行为  激活新节点及编辑 时 回车创建新节点后并无反应

### ISSUE THREAD

**Issue by idealkindom** [wanglin2/mind-map#764]
如题。

另外，好像在不同层级上有Enter键（创建新同级节点）无反应的情况

**Comment by wanglin2** [comment]
实例化代码截一下

哪个层级上enter无反应？

**Comment by idealkindom** [comment]
我发现可能是只要在操作过程中切换过主题颜色，之后所有快捷键都不起作用了

在 2024-07-29 09:32:40，"街角小林" ***@***.***> 写道：


Reopened #764.

**Comment by idealkindom** [comment]
奇怪的触发原因，常驻后台有Listary,everything,snipaste.

在 2024-07-29 09:32:40，"街角小林" ***@***.***> 写道：


Reopened #764.

**Comment by wanglin2** [comment]
你是用的客户端？

**Comment by idealkindom** [comment]
对，我现在也魔怔了，一个台式机一个笔记本都是win 10，也不知道什么情况下会触发快捷键全停。

在 2024-07-29 17:03:18，"街角小林" ***@***.***> 写道：


你是用的客户端？

**Comment by wanglin2** [comment]
用的哪个版本

**Comment by idealkindom** [comment]
github release最新版windows，免安装和安装版我都用了。

在 2024-07-29 17:18:52，"街角小林" ***@***.***> 写道：


用的哪个版本
