### ISSUE TITLE
npm run build 打包失败

### ISSUE THREAD

**Issue by J-Rainbow** [wanglin2/mind-map#770]
你好，我通过git 拉取项目 git clone https://github.com/wanglin2/mind-map.git
在web目录下打包失败

![企业微信截图_17224087991368](https://github.com/user-attachments/assets/12123702-8120-4da0-bcd9-882b73392b66)

**Comment by wanglin2** [comment]
node版本多少

**Comment by J-Rainbow** [comment]
> node 版本多少
node v18.16.0

**Comment by wanglin2** [comment]
太高了，可以切换为14试试
