### ISSUE TITLE
节点里面的内容不能自由的选中,可以优化一下

### ISSUE THREAD

**Issue by Yam1-1224** [wanglin2/mind-map#772]

**Comment by wanglin2** [comment]
自由选中是啥意思呢

**Comment by Yam1-1224** [comment]
就是像图片里面这样 就鼠标拖动想选择某些文字 就选中不了






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wanglin2/mind-map"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月1日(星期四) 下午4:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wanglin2/mind-map] 节点里面的内容不能自由的选中,可以优化一下 (Issue #772)





 
自由选中是啥意思呢

**Comment by wanglin2** [comment]
这个没啥办法，鼠标功能会冲突，要复制文字可以双击进入编辑再复制

**Comment by Yam1-1224** [comment]
好的 没事 以后可以慢慢解决 作者大大加油




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wanglin2/mind-map"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月1日(星期四) 下午4:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wanglin2/mind-map] 节点里面的内容不能自由的选中,可以优化一下 (Issue #772)





 
这个没啥办法，鼠标功能会冲突，要复制文字可以双击进入编辑再复制
