### ISSUE TITLE
怎么获取快捷键插入的节点比如tab，只要插入的节点，现在是能获取所有节点，太多了

### ISSUE THREAD

**Issue by onlyis** [wanglin2/mind-map#776]
怎么获取快捷键插入的节点比如tab，只要插入的节点，现在是能获取所有节点，太多了

**Comment by wanglin2** [comment]
需要重写快捷键，先移除：
mindMap.keyCommand.removeShortcut('Tab')
再添加：
mindMap.keyCommand.addShortcut('Tab', () => {
      mindMap.execCommand('INSERT_CHILD_NODE')
    })
此时，可以自己添加插入节点命令的额外参数，具体怎么获取刚插入的节点可以参考这个教程：https://wanglin2.github.io/mind-map/#/doc/zh/course3/%E6%8F%92%E5%85%A5%E5%AD%90%E8%8A%82%E7%82%B9
