### ISSUE TITLE
客户端：节点文本编辑框中鼠标无法多选文字

### ISSUE THREAD

**Issue by cijiabei** [wanglin2/mind-map#777]
点击矩形结构的主题，会进入到下一层主题，该如何操作

**Comment by wanglin2** [comment]
矩形结构是啥，文字滑动不能选中是啥意思

**Comment by cijiabei** [comment]
就是3*4/4*4/4*5类似这种自定义宫格子主题

**Comment by cijiabei** [comment]
https://github.com/user-attachments/assets/80363f76-c018-4b08-90e6-a8f48ad0e1a4

**Comment by wanglin2** [comment]
> 就是3_4/4_4/4*5类似这种自定义宫格子主题

这种结构不支持

**Comment by wanglin2** [comment]
> QQ.20240808113017.mp4

试了一下，客户端好像会有这个问题，在线的没有

**Comment by cijiabei** [comment]
![FE55AC7236411EDB30FF092D4DE9A52E](https://github.com/user-attachments/assets/f497693d-4082-4218-9f9f-bdfdf45420d1)
zi子主题多个版块，这样可以吗
