### ISSUE TITLE
0.10.5版本，手绘插件接入不生效

### ISSUE THREAD

**Issue by ZwjDreamMail** [wanglin2/mind-map#780]
![1723357249205](https://github.com/user-attachments/assets/58849422-ab8a-414f-b364-2e23b0d6e0c2)
![1723357284030](https://github.com/user-attachments/assets/b7487847-ff5e-48d1-be7f-3c02554ec787)

**Comment by wanglin2** [comment]
![image](https://github.com/user-attachments/assets/285b9d82-6263-4909-902a-ecf30d1c996b)

![image](https://github.com/user-attachments/assets/d2a50d7f-0645-4954-b8bb-95e6ce2d2cd0)

试了一下没问题啊，注册的其他插件生效么

**Comment by wanglin2** [comment]
试试立即注册，不要放到函数中

**Comment by ZwjDreamMail** [comment]
好的，我用的0.10.4版本，已经可以了
