### ISSUE TITLE
如何限制最大层数？

### ISSUE THREAD

**Issue by Tamcony** [wanglin2/mind-map#783]
配置里面好像没有这个选项？
而且也没有beforeCreateNode这个事件来自行处理。

**Comment by wanglin2** [comment]
默认不支持限制层数，可以自己在调用插入节点的命令前判断，内置创建节点的快捷键也可以删除然后重写。

**Comment by Tamcony** [comment]
![image](https://github.com/user-attachments/assets/b77e6ed3-efde-45bc-bb24-37c2e39949a1)
请问'Tab'快捷键这块是不是还有其他操作？我按照如图代码实现的逻辑创建出来的节点聚焦但是无法输入。
可以提供一下这块的源码链接吗？我刚刚没找到

**Comment by wanglin2** [comment]
https://github.com/wanglin2/mind-map/blob/main/simple-mind-map/src/core/render/Render.js#L341

没有其他操作

**Comment by Tamcony** [comment]
> https://github.com/wanglin2/mind-map/blob/main/simple-mind-map/src/core/render/Render.js#L341
> 
> 没有其他操作

明白，关于上面我提到的聚焦无法输入的问题，我简单复现了一下，应该是和elment的dialog冲突了，复现链接：https://codesandbox.io/p/live/878eb38e-1b1a-41fd-b31a-35023e99ee79，您看看有什么思路或办法解决吗？

**Comment by wanglin2** [comment]
链接没权限

**Comment by Tamcony** [comment]
> 链接没权限

不好意思，这个工具用的不多，这样应该可以了 。
https://codesandbox.io/p/devbox/mind-map-2snyg3
