### ISSUE TITLE
网页demo的Bug提交：有关回退功能；有关主题切换；有关右下角输入缩放率的问题；有关搜索与替换功能

### ISSUE THREAD

**Issue by xiaobu474** [wanglin2/mind-map#784]
1.有关回退功能，smm好像将激活节点设置为可回退的一步了，具体表现为：进行一次撤回操作（例如撤回创建节点操作）后，再点击一次任意节点，那么之前撤回的那个操作（创建节点的操作）就无法恢复了
2.有关主题切换功能：在更改基础样式后切换主题，在弹出的“是否覆盖基础样式”的提示框内选中覆盖，接下来，再更改一个基础样式，然后之前覆盖的基础样式都恢复了
3.有关右下角输入缩放率的问题，如果在激活节点的状态下，在右下角的缩放率中进行输入，那么输入的文本会输入在激活的节点内
4.有关搜索与替换功能，有两个问题：当鼠标移出搜索框内时，输入框失焦了，无法输入文字；中文输入法下，输入的第一个字母无法被输入法捕捉

**Comment by wanglin2** [comment]
非常感谢发现了这么多问题，123都已修复，4暂时没有办法，v0.10.6+生效

**Comment by xiaobu474** [comment]
您好，在使用搜索功能时，鼠标移出搜索框失焦的问题确实困扰到了我，在使用搜索功能时，经常会下意识将鼠标移走，所以我看了下这边的源码，有以下问题：
1.看到您在change log的v0.6.10版本介绍中提到“优化搜索:鼠标不在搜索区域内不聚焦,解决鼠标不在搜索区域内无法删除输入的文字的问题”，我想问下“鼠标不在搜索区域内无法删除输入的文字”是当鼠标移出搜索框范围时，无法删除搜索框内的文字吗？如果是这个问题的话，我在删除search.vue文件中鼠标失焦的函数后，好像并没有遇到，请问您是如何遇到这个问题的呢？这个问题能否复现？
2.我在删除search.vue文件中鼠标失焦的函数后，遇到的问题是：点击画布无法取消搜索框的焦点模式，这导致在激活搜索框时，输入文本或使用backspace，都会操作搜索框内的文本，我认为这个问题应该会比较好解决吧

**Comment by xiaobu474** [comment]
有关搜索框失焦问题:
-我在克隆了v0.6.9-fix1与v0.6.10版本的项目，并与v0.10.5项目的源码对比后，发现v0.6.9-fx1版本确实存在“鼠标不在搜索区域内无法删除输入的文字的问题”，我通过将在v0.6.9-fix1添加"@keydown.native.stop"命令解决问题
-目前情况为：v0.10.5版本，删除鼠标失焦函数后，没有“鼠标不在搜索区域内无法删除输入的文字"问题，遇到"鼠标点击画布无法使搜索框失焦"问题v0.6.9-fix1版本，添加"@keydown.native.stop"命令，没有"鼠标不在搜索区域内无法删除输入的文字"问题，且能够实现“鼠标点击画布无法使搜索框失焦"功能
