### ISSUE TITLE
tree导出文件目录树转化为导图

### ISSUE THREAD

**Issue by RyanLei-icer** [wanglin2/mind-map#785]
在linux下可以使用tree命令生成txt文件的文件夹目录树，能否支持将此目录树转化为思维导图。
.
├── d_ip_cell_wrapper
│   ├── cell_wrapper
│   │   ├── bef
│   │   │   ├── cln16ffc
│   │   │   │   ├── cpf
│   │   │   │   ├── cpm
│   │   │   │   ├── ctl
│   │   │   │   ├── def
│   │   │   │   ├── gds
│   │   │   │   ├── lef
│   │   │   │   ├── lib
│   │   │   │   ├── parasitics
│   │   │   │   ├── post_v
│   │   │   │   ├── pre_v
│   │   │   │   ├── sdf
│   │   │   │   └── upf
│   │   │   └── cln22ull
│   │   │       ├── cpf
│   │   │       ├── cpm
│   │   │       ├── ctl
│   │   │       ├── def
│   │   │       ├── gds
│   │   │       ├── lef
│   │   │       ├── lib
│   │   │       ├── parasitics
│   │   │       ├── post_v
│   │   │       ├── pre_v
│   │   │       ├── sdf
│   │   │       └── upf
│   │   ├── bfm
│   │   ├── cell_wrapper_table2rtl.csh
│   │   ├── cell_wrapper_table.csv
│   │   ├── def.v
│   │   ├── DUT.v
│   │   ├── filelist
│   │   │   ├── bcf
│   │   │   │   └── rtl_bcf.py
│   │   │   ├── __pycache__
│   │   │   │   └── rtl.cpython-37.pyc
│   │   │   ├── rtl.py
│   │   │   └── stub.py
│   │   ├── incisive
│   │   │   ├── coverage
│   │   │   │   └── all
│   │   │   └── wave
│   │   │       └── all

**Comment by wanglin2** [comment]
自己写个方法转成树结构，再传给思维导图渲染就行
