### ISSUE TITLE
需求建议：希望初始化配置的时候可以给每个节点增加自定义属性，并能在 Node 节点实例中可以获取到

### ISSUE THREAD

**Issue by jijiucheng** [wanglin2/mind-map#789]
需求建议：希望初始化配置的时候可以给每个节点增加自定义属性，并能在 Node 节点实例中可以获取到

**Comment by wanglin2** [comment]
直接在节点数据里加就可以了，{data:{text: 'xxx', _xxx: '自定义数据}, children: []}
获取：node.getData('_xxx')
