### ISSUE TITLE
使用打包后的 umd 版本库，生成的 mindMap 左右上下拖动时，会有一个明显的边界感，不像直接引用非打包文件时的无边界感。

### ISSUE THREAD

**Issue by zhoujingking** [wanglin2/mind-map#792]
import MindMap from 'simple-mind-map/dist/simpleMindMap.umd' 创建 mindMap 会触发这个问题

**Comment by quanzhongxian** [comment]
可能是默认        isLimitMindMapInCanvasWhenHasScrollbar: true,限制了拖拽范围

**Comment by zhoujingking** [comment]
> isLimitMindMapInCanvasWhenHasScrollbar

非常感谢，确实是这个问题引起的，把这个值设为false就好了
