### ISSUE TITLE
剪切板直接粘贴的图片,无法保存.

### ISSUE THREAD

**Issue by strongasahorse** [wanglin2/mind-map#793]
剪切板直接粘贴的图片,操作当时可以正常显示,但是保存后,再次打开文件则是不能正确显示了.
应该是保存时没有把图片作为附件单独保存.
但是我观察思维导图文件大小,发现直接粘贴图片后的文件大小变大了.感觉图片内容应该是保存到文件中,但是再次打开没有正确显示出来.

**Comment by wanglin2** [comment]
客户端吗，试了几次，几个文件，所有都不行么
