### ISSUE TITLE
浏览器默认行为：“拖动鼠标选中文本”失效

### ISSUE THREAD

**Issue by jinying134** [wanglin2/mind-map#797]
![1723787467998](https://github.com/user-attachments/assets/a254c770-5159-41d9-b1b9-a665dcbb21f0)

Event.js文件中的 118 行 e.preventDefault() 导致浏览器默认行为：“拖动鼠标选中文本”失效

//  鼠标移动事件
  onMousemove(e) {
    e.preventDefault()

谷歌浏览器版本：70.0.3538.110

**Comment by wanglin2** [comment]
0.10.6版本已经去除
