### ISSUE TITLE
希望增加 自定义图标的功能

### ISSUE THREAD

**Issue by ZhangMingZhao1** [wanglin2/mind-map#798]
现在图标的设置都是内置的，希望增加一个注册自定义图标组的功能，能插入自己的自定义的图标。

**Comment by wanglin2** [comment]
可以开展的，https://wanglin2.github.io/mind-map/#/doc/zh/course19

**Comment by ZhangMingZhao1** [comment]
<img width="773" alt="image" src="https://github.com/user-attachments/assets/c5bce705-cc0d-4de6-acff-e5b38c07672e">
那这块的文档可能过时了 😂
