### ISSUE TITLE
能否实现连线样式多样化，现在只有直角线条

### ISSUE THREAD

**Issue by ouyang7923** [wanglin2/mind-map#80]
![image](https://user-images.githubusercontent.com/105358618/225180960-a45f0947-71e5-4af0-98df-6e5ebed8a5b7.png)
能切换线条样式为框内所示也不错了

**Comment by suka233333** [comment]
兄弟你似乎反馈错地方啦，这个思源挂件是基于这个库进行二次开发的，库作者的完整导图功能示例请看这里：
https://wanglin2.github.io/mind-map/

然后反馈这个思源挂件的问题的地方在这里：
https://github.com/suka233/siyuan-Kmind
