### ISSUE TITLE
您好，在深度使用smm的网页demo过后，我发现以下问题，以及我的小建议

### ISSUE THREAD

**Issue by xiaobu474** [wanglin2/mind-map#800]
1.我在firefox中使用smm时粘贴非smm节点格式的内容（如图片）时，在激活节点并直接粘贴图片时，需要按下ctrl+V后，会弹出一个“粘贴”按钮，需要点击其两次才能够正常粘贴，这个问题在使用chrome打开smm时没遇到，希望能够将这这两个“粘贴”给跳过
2.在使用smm过程中想要查找包含特定搜索文字（如“工作”）的时候发现：按下回车只能找到下一个包含这段文字的节点（定位下一个包含“工作”的节点），无法找到所有节点或者搜索上一个节点，这个功能很不方便，希望能够增加显示所有包含这段文字（“工作”）节点的功能
3.我在导入我的xmind文件时，发现我的xmind中的“矩阵图”结构在导入smm后会变得不正常（您可以尝试一下，xmind中的“矩阵图”中的第二行会变成对应列的标签），希望您能够同步xmind与smm的结构，保证导入导出格式一样；此外还希望您能让smm支持单独修改某一个节点的结构功能（我想要导入的xmind文件正好有一个节点为“矩阵图”结构，其他节点为逻辑图结构）
4.有关格式刷功能问题，我发现，一个节点初始化的样式，没法作为被复制的格式传递下去（如复制一个字号大小在创建后就没改过的节点格式，没办法将字号粘贴到字号很大的节点），希望能够将这个问题解决掉，即使是初始化的格式也能够传递下去
5.我发现基础样式的修改（如修改背景颜色）无法被撤回，建议将基础样式的修改也作为可撤回的操作
6.只读模式打开时，依然可以修改“基础样式”，我觉得这与“只读”是矛盾的，认为应该在“只读模式”下禁用基础样式
7.有关节点内图片建议，建议增加可以调节节点内图片与文字相对位置的功能，如设置图片在节点下方，文字在节点上方
8.我在激活节点节点后使用“撤回”与“前进”功能时，发现会出现右侧大纲与画布内节点不同步的问题（可以多次点击“撤回”与“前进”触发这个问题），希望能够解决不同步的问题
9.在打开“全屏查看”后，依然可以拖动节点、收起展开节点操作，我认为在“全屏查看”时不应该能编辑思维导图，应该禁用前面说的操作功能
10.在性能模式下，想要拖拽一个分支在屏幕外（性能模式下，屏幕外的节点不会加载）的节点，是无法实现的，希望能够将无法拖拽移动节点的问题解决一下
11.我在firefox浏览器中打开网页demo的使用过程中发现在超多节点（我正在编辑的思维导图节点数量达到2500个）下在会占用很多的内存，并且每次操作响应时间很长，我在尝试换了个浏览器比如chrome后发现这些问题都有所改善（内存占用变小，且操作的相应时间也缩短了），我觉得smm对于firefox这个浏览器会有一些性能问题，需要对其进行性能优化
12.有关回退功能，激活节点依旧是一个可以撤回的操作，希望可以解决这个问题
13.有关右下角输入缩放率，在缩放率输入框输入缩放率按下回车后，缩放率输入框内仍然有光标闪烁；且输入框是可以输入文字的（如“dw”），希望可以解决

**Comment by xiaobu474** [comment]
1.chrome与firefox中的smm对超多节点的处理区别（ff中的smm明显差于chrome）：
-firefox浏览器中打开网页demo的使用过程中发现在超多节点（我正在编辑的思维导图节点数量达到2500个）下在会占用很多的内存，并且每次操作响应时间很长
-chrome后发现这些问题都有所改善，内存占用变小，且操作的相应时间也缩短了
-我觉得smm对于firefox这个浏览器会有一些性能问题，需要对其进行性能优化
2.firefox中粘贴非smm节点内容时（如图片），需要按下ctrl+V后，会弹出一个“粘贴”按钮，需要点击其两次才能够正常粘贴

**Comment by wanglin2** [comment]
1.目前只能去掉一次粘贴提示，怎么完全去除，不知道
![image](https://github.com/user-attachments/assets/329915e6-957c-4787-963c-4fee9e3511b0)

**Comment by wanglin2** [comment]
2.增加了一个搜索结果列表
6，8，13改了，其他暂不考虑或改不了
