### ISSUE TITLE
升级Quill编辑器带来的问题

### ISSUE THREAD

**Issue by wanglin2** [wanglin2/mind-map#806]

**Comment by wanglin2** [comment]
目前问题：

1.无法拦截默认的Enter键阻止换行；

2.shift+enter换行后的新行没有样式；

**Comment by wanglin2** [comment]
4.quill.clipboard.addMatcher方法无法拦截到剪贴板的图片，详见[issue4337](https://github.com/slab/quill/issues/4337)。所以库的做法是当剪贴板里有图片只能整个拦截，带来的问题就是剪贴板里同时存在图片和文本时也无法粘贴

**Comment by watermelon0314** [comment]
<img width="1027" alt="image" src="https://github.com/user-attachments/assets/90b0fd8f-da9a-4413-a949-c34502c68e19">
使用文档里面的vue3版本demo，然后升级到11.2版本后报错，需要怎么解决呢？
