### ISSUE TITLE
请问被掩藏的节点，页面渲染是否还会计算。我的导图有几千个节点，我掩藏了大多数节点，只显示几个节点，想由此避免页面卡的问题。掩藏后编辑等操作依然卡。

### ISSUE THREAD

**Issue by jinying134** [wanglin2/mind-map#809]

**Comment by wanglin2** [comment]
收起的节点不会渲染，是可以解决卡的问题的，如果觉得不行，可以试试性能模式，
![image](https://github.com/user-attachments/assets/32f6079e-ffcc-46c8-b8d6-985bd18f5d1e)

**Comment by wanglin2** [comment]
文档地址换了：https://wanglin2.github.io/mind-map-docs/

**Comment by jinying134** [comment]
在线文档一直打不开，页面空白

**Comment by jinying134** [comment]
能否掩藏父节点  
![image](https://github.com/user-attachments/assets/9021334f-bba5-4e53-babc-4cfc379e4691)

**Comment by jinying134** [comment]
请问被掩藏的节点，页面渲染是否还会计算。我的导图有几千个节点，我掩藏了大多数节点，只显示几个节点，想由此避免页面卡的问题。掩藏后编辑等操作依然卡


这里是掉用hide掩藏
