### ISSUE TITLE
需求支持：希望增加mac触摸板移动画布的灵敏度选项

### ISSUE THREAD

**Issue by ZhangMingZhao1** [wanglin2/mind-map#810]
![image](https://github.com/user-attachments/assets/a6a7f734-5904-4091-a7c1-7f9bb962264c)

看到滚轮移动画布的灵敏度都实现了，触摸板的希望也能支持一下，现在默认mac触摸板触发的画布移动灵敏度太高了，体验不好。

**Comment by wanglin2** [comment]
优化了一下mac触控板的双指拖动，直接使用事件对象里的拖动距离，达到和手指同步的效果，并且同步了快速拖动时的惯性效果，v0.11.0+生效
