### ISSUE TITLE
需求支持：希望主题增加根节点，一级节点，二级节点 的节点默认边距设置

### ISSUE THREAD

**Issue by ZhangMingZhao1** [wanglin2/mind-map#811]
现在在自定义主题设置里配置 root,second, node下面的paddingX, paddingY，都不生效。想在不同主题里配置不同级别节点的默认大小，现在无法满足。

**Comment by GrandeJu** [comment]
+1，希望支持

**Comment by wanglin2** [comment]
已支持，v0.11.2+生效
