### ISSUE TITLE
需求：希望增加一个配置项动态控制鼠标滚轮行为

### ISSUE THREAD

**Issue by GrandeJu** [wanglin2/mind-map#812]
在富文本编辑器中集成思维导图后，鼠标滚动查看文档时，经常误触发思维导图画布滚动。想实现语雀文档中的效果，思维导图聚焦后再响应鼠标滚轮行为。

**Comment by wanglin2** [comment]
可以参考下面的代码实现

> let enableWheel = false
      this.mindMap.el.removeEventListener(
        'wheel',
        this.mindMap.event.onMousewheel
      )
      this.mindMap.el.addEventListener('wheel', e => {
        if (enableWheel) {
          this.mindMap.event.onMousewheel(e)
        }
      })
      this.mindMap.el.addEventListener('click', e => {
        e.stopPropagation()
        enableWheel = true
      })
      document.body.addEventListener('click', e => {
        enableWheel = false
      })
