### ISSUE TITLE
需求支持：希望增加节点背景色的渐变角度选项

### ISSUE THREAD

**Issue by ZhangMingZhao1** [wanglin2/mind-map#814]
<img width="1293" alt="image" src="https://github.com/user-attachments/assets/beec6aa3-d177-43af-9b8d-a0e9849221bd">

目前节点渐变色选项默认就是从左到右，希望能增加linear-gradient的方向选项，比如我希望是从上到下的渐变，传180(deg)

**Comment by wanglin2** [comment]
已支持，v0.11.1+可用
