### ISSUE TITLE
问题反馈：全屏画布容器无法编辑节点，只能全屏body dom才能编辑

### ISSUE THREAD

**Issue by ZhangMingZhao1** [wanglin2/mind-map#816]
我看官网源码是将容器全屏后只能查看，将body全屏后才能编辑。但是因为我的body下面有左侧栏和header，那我怎么实现将画布全屏且能编辑呢。

**Comment by wanglin2** [comment]
并没有全屏限制编辑，文本编辑框没出来大概率是因为默认是添加到body下面的，只全屏容器元素当然不会显示，可以通过该选项修改，
![image](https://github.com/user-attachments/assets/24406234-e21d-4b2e-a0c0-054db32062c0)
