### ISSUE TITLE
如何在ts项目更好地使用

### ISSUE THREAD

**Issue by xmengweb** [wanglin2/mind-map#820]
以修改节点样式为例,需要在项目中调用节点的setStyle方法
![image](https://github.com/user-attachments/assets/8cb55cf8-96c8-4c58-b63d-9d09c62278b0)
但是会报错:
![image](https://github.com/user-attachments/assets/cad4c700-02ce-4ef1-8d7d-c481e424d972)
原因是提供的Node类型并没有setStyle类型
![image](https://github.com/user-attachments/assets/545b82c0-c0a2-4c0b-8437-d2d75b77b971)
对于以上问题有什么解决方式吗?

**Comment by wanglin2** [comment]
其他方法在其他文件里定义了，你看看能不能扩展一下
![image](https://github.com/user-attachments/assets/887e813b-dc50-403f-b4b5-9bcdca0af951)
