### ISSUE TITLE
问题反馈：全屏模式下添加外框，外框位置错位

### ISSUE THREAD

**Issue by ZhangMingZhao1** [wanglin2/mind-map#822]
<img width="690" alt="image" src="https://github.com/user-attachments/assets/213138b6-2adf-41b1-b037-961ca079ad49">

如图，全屏模式，在图中高亮的节点添加外框，外框位置出现在左边，位置错位

**Comment by wanglin2** [comment]
具体怎么添加的，代码样式截图一下

**Comment by ZhangMingZhao1** [comment]
用命令添加：
![image](https://github.com/user-attachments/assets/0a7aa407-5f83-4cde-98e8-9f9baa125058)
全屏模式相关：
![image](https://github.com/user-attachments/assets/7b71c72f-ce0b-46eb-a62f-4d19a89c4403)
customInnerElsAppendTo的属性也是这个editContainer

**Comment by ZhangMingZhao1** [comment]
mindMapContainer是画布容器

**Comment by ZhangMingZhao1** [comment]
> 用命令添加： ![image](https://private-user-images.githubusercontent.com/29058747/361639367-0a7aa407-5f83-4cde-98e8-9f9baa125058.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Mjg3ODcsIm5iZiI6MTcyNDcyODQ4NywicGF0aCI6Ii8yOTA1ODc0Ny8zNjE2MzkzNjctMGE3YWE0MDctNWY4My00Y2RlLTk4ZTgtOWY5YmFhMTI1MDU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAzMTQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhMDQ5MjI1NmM1YWQ0YjE2MDNiYzE1ZmQwMTc1NDA1NGM0YzhlNGUxMWRkMjg0MmYxY2YwMjBhYjg3NWYxNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.76ZOw1F7tIlMOWvqAUEMX6uxplHgBbjtT28mg56fswc) 全屏模式相关： ![image](https://private-user-images.githubusercontent.com/29058747/361639504-7b71c72f-ce0b-46eb-a62f-4d19a89c4403.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Mjg3ODcsIm5iZiI6MTcyNDcyODQ4NywicGF0aCI6Ii8yOTA1ODc0Ny8zNjE2Mzk1MDQtN2I3MWM3MmYtY2UwYi00NmViLWE2MmYtNGQxOWE4OWM0NDAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAzMTQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5MWFjZTNlNGZmMmQzODMxZjZlYTRkZTYxZmI5MjZiMzZhZGU1NGNjMmU5MjgxYWQ0NTlhMWFmZDUyMzRiNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bzcldQEgn95BwwDFNU9ggy4xFQ7x704kavKvt69gtPo) customInnerElsAppendTo的属性也是这个editContainer

mindMapContainer是画布容器

**Comment by wanglin2** [comment]
复现不出来，我这边没有问题，
![image](https://github.com/user-attachments/assets/a7afe48c-a505-4a8a-a438-ba8f22e6a6cc)

**Comment by ZhangMingZhao1** [comment]
![image](https://github.com/user-attachments/assets/a3a3dd93-3ad8-4967-be91-5997b79265ca)
在线demo画布默认就是全屏大小的，试一下有header和left-sider(边栏)的布局，这种情况下脑图画布默认不是全屏再调全屏。我这里调全屏后，我发现画布容器是全屏了，但下一层级的svg还是原来的大小(如图)，是不是这个问题导致的

**Comment by ZhangMingZhao1** [comment]
> ![image](https://private-user-images.githubusercontent.com/29058747/362518512-a3a3dd93-3ad8-4967-be91-5997b79265ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MDE0MDksIm5iZiI6MTcyNDkwMTEwOSwicGF0aCI6Ii8yOTA1ODc0Ny8zNjI1MTg1MTItYTNhM2RkOTMtM2FkOC00OTY3LWJlOTEtNTk5N2I3OTI2NWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDAzMTE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5MDk0NDFlNGZmN2VmMGQ4NzYzMTRlYTI3ODA5NDI0ZDA5MDdjODM1MzM4ZGRlZTkwZTIyZWQ2MGFkNDI4OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TiV4kUd7cUOcUXoqvAbjE1nQpbkkpYvEcjRXp2YrTJM) 在线demo画布默认就是全屏大小的，试一下有header和left-sider(边栏)的布局，这种情况下脑图画布默认不是全屏再调全屏。我这里调全屏后，我发现画布容器是全屏了，但下一层级的svg还是原来的大小(如图)，是不是这个问题导致的

也发现新问题，就是调容器的全屏，内层的svg画布没发生变化，导致出现下面情况：
![image](https://github.com/user-attachments/assets/8034f445-aa1a-4a79-a609-65148881597d)

**Comment by Tamcony** [comment]
我也遇到了类似的问题，整个浏览器最大化的时候svg是占满他的容器div的（见图1），但是如果浏览器窗口化了就占不满容器div了（见图2图3）

![image](https://github.com/user-attachments/assets/2ac7eb15-2d03-4ac7-91f9-8eecd65e4173)
![img_v3_02e7_b6379bb6-2f28-43e7-8b0d-323474be910g](https://github.com/user-attachments/assets/7a781630-11ce-44bc-958f-7699a039493b)
![img_v3_02e7_abd257a8-7e52-4f6a-8151-af913007448g](https://github.com/user-attachments/assets/5d68a091-a924-4b27-899e-d1a38bb1ad12)

**Comment by ZhangMingZhao1** [comment]
> 我也遇到了类似的问题，整个浏览器最大化的时候svg是占满他的容器div的（见图1），但是如果浏览器窗口化了就占不满容器div了（见图2图3）
> 
> ![image](https://private-user-images.githubusercontent.com/49635772/362577074-2ac7eb15-2d03-4ac7-91f9-8eecd65e4173.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTczODYsIm5iZiI6MTcyNDkxNzA4NiwicGF0aCI6Ii80OTYzNTc3Mi8zNjI1NzcwNzQtMmFjN2ViMTUtMmQwMy00YWM3LTkxZjktOGVlY2Q2NWU0MTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA3MzgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmYTFlYzM2NTI5N2Q1NDNlZWI5Mzc5YzRlZjRlYTY1ZTQxMTUzYjBlMmQ4MTNiYTU0ODVjZTZmNDM0YzBmNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aGqW6j-rDjjNTQcM3iLcKKgEhRCKRUGijYsK42kRbrw) ![img_v3_02e7_b6379bb6-2f28-43e7-8b0d-323474be910g](https://private-user-images.githubusercontent.com/49635772/362578844-7a781630-11ce-44bc-958f-7699a039493b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTczODYsIm5iZiI6MTcyNDkxNzA4NiwicGF0aCI6Ii80OTYzNTc3Mi8zNjI1Nzg4NDQtN2E3ODE2MzAtMTFjZS00NGJjLTk1OGYtNzY5OWEwMzk0OTNiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA3MzgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4ZmUzMjIyOTg4ZDE2YTQ5OTMyMDY2MjlhODBlYmYyM2Y3MDhlMmRmNTM0MzdjODU4N2M0MGNjM2FhMTk3YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s8FLpijwJLOGXWLZUGauDUkJg0MTflEexpR4BglB3UU) ![img_v3_02e7_abd257a8-7e52-4f6a-8151-af913007448g](https://private-user-images.githubusercontent.com/49635772/362578873-5d68a091-a924-4b27-899e-d1a38bb1ad12.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTczODYsIm5iZiI6MTcyNDkxNzA4NiwicGF0aCI6Ii80OTYzNTc3Mi8zNjI1Nzg4NzMtNWQ2OGEwOTEtYTkyNC00YjI3LTg5OWUtZDFhMzhiYjFhZDEyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA3MzgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlOWM2Mzg3OWZiYjBkY2JkMjc3OGYyZTMyOGEwNTU5YzNiOGUwMWNkZTcxNDM1NTA4YzMwMWQ4OGZlNmNiN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5pHEE-qKa0tzuMCH-2jaWS0RqX1uRCDUAsRCJ2EExRA)

你的问题好像本质和我一样，形式是相反的，本质问题是画布svg只在初始化的时候固定宽高，一旦全屏/窗口化，svg画布大小不会发生变化，导致脑图拖动范围还是之前的范围而不是现在窗口的大小，还会导致一些计算错误问题，如上图中我提到的外框位置问题

**Comment by Tarrency** [comment]
svg那层应该根据容器大小的变化，计算出缩放比例和位置

**Comment by Tarrency** [comment]
svg那层应该根据容器大小的变化，计算出缩放比例和位置，自动调节？

**Comment by wanglin2** [comment]
全屏应该也会触发resize事件，无论是全屏还是调整窗口大小，或者是其他方式更改了容器元素的大小和位置，需要调用库的方法更新：
![image](https://github.com/user-attachments/assets/3d7dfdc2-b2fd-4c30-a4bd-c51dd2c1023a)

**Comment by Tamcony** [comment]
> > 我也遇到了类似的问题，整个浏览器最大化的时候svg是占满他的容器div的（见图1），但是如果浏览器窗口化了就占不满容器div了（见图2图3）
> > ![image](https://private-user-images.githubusercontent.com/49635772/362577074-2ac7eb15-2d03-4ac7-91f9-8eecd65e4173.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTczODYsIm5iZiI6MTcyNDkxNzA4NiwicGF0aCI6Ii80OTYzNTc3Mi8zNjI1NzcwNzQtMmFjN2ViMTUtMmQwMy00YWM3LTkxZjktOGVlY2Q2NWU0MTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA3MzgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmYTFlYzM2NTI5N2Q1NDNlZWI5Mzc5YzRlZjRlYTY1ZTQxMTUzYjBlMmQ4MTNiYTU0ODVjZTZmNDM0YzBmNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aGqW6j-rDjjNTQcM3iLcKKgEhRCKRUGijYsK42kRbrw) ![img_v3_02e7_b6379bb6-2f28-43e7-8b0d-323474be910g](https://private-user-images.githubusercontent.com/49635772/362578844-7a781630-11ce-44bc-958f-7699a039493b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTczODYsIm5iZiI6MTcyNDkxNzA4NiwicGF0aCI6Ii80OTYzNTc3Mi8zNjI1Nzg4NDQtN2E3ODE2MzAtMTFjZS00NGJjLTk1OGYtNzY5OWEwMzk0OTNiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA3MzgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4ZmUzMjIyOTg4ZDE2YTQ5OTMyMDY2MjlhODBlYmYyM2Y3MDhlMmRmNTM0MzdjODU4N2M0MGNjM2FhMTk3YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s8FLpijwJLOGXWLZUGauDUkJg0MTflEexpR4BglB3UU) ![img_v3_02e7_abd257a8-7e52-4f6a-8151-af913007448g](https://private-user-images.githubusercontent.com/49635772/362578873-5d68a091-a924-4b27-899e-d1a38bb1ad12.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTczODYsIm5iZiI6MTcyNDkxNzA4NiwicGF0aCI6Ii80OTYzNTc3Mi8zNjI1Nzg4NzMtNWQ2OGEwOTEtYTkyNC00YjI3LTg5OWUtZDFhMzhiYjFhZDEyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA3MzgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlOWM2Mzg3OWZiYjBkY2JkMjc3OGYyZTMyOGEwNTU5YzNiOGUwMWNkZTcxNDM1NTA4YzMwMWQ4OGZlNmNiN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5pHEE-qKa0tzuMCH-2jaWS0RqX1uRCDUAsRCJ2EExRA)
> 
> 你的问题好像本质和我一样，形式是相反的，本质问题是画布svg只在初始化的时候固定宽高，一旦全屏/窗口化，svg画布大小不会发生变化，导致脑图拖动范围还是之前的范围而不是现在窗口的大小，还会导致一些计算错误问题，如上图中我提到的外框位置问题

我感觉我的问题还是不太一样，我三张图都是刚初始化svg的时候截的，不是先初始化再改变浏览器窗口大小，只不过第一张是浏览器全屏初始化svg截的，第二三张是浏览器窗口化初始svg截的。相反如果是先渲染再窗口化，我这边因为监听了容器宽高调用resize方法还能保证容器和svg宽高是一致的。

**Comment by Tamcony** [comment]
> 全屏应该也会触发resize事件，无论是全屏还是调整窗口大小，或者是其他方式更改了容器元素的大小和位置，需要调用库的方法更新： ![image](https://private-user-images.githubusercontent.com/17272433/362602328-3d7dfdc2-b2fd-4c30-a4bd-c51dd2c1023a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MjE0MDEsIm5iZiI6MTcyNDkyMTEwMSwicGF0aCI6Ii8xNzI3MjQzMy8zNjI2MDIzMjgtM2Q3ZGZkYzItYjJmZC00YzMwLWE0YmQtYzUxZGQyYzEwMjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA4NDUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwOTcwNzM5YjgzZWNkM2YxZDhmNDBhNWJiMWQ0NjE0M2ZiNTVjZDA2ZGU4MWYyMDMyNjQ4ZTg2NDU2OThjMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9VQG948PXJfBNrQv96tSAkc1I2HNvc_h-4_oLimbMgQ)

我怀疑内容刚渲染的时候，svg宽高和不止和容器宽高有关系，还和浏览器窗口化或者说浏览器宽高有关系

**Comment by wanglin2** [comment]
> > 全屏应该也会触发resize事件，无论是全屏还是调整窗口大小，或者是其他方式更改了容器元素的大小和位置，需要调用库的方法更新： ![image](https://private-user-images.githubusercontent.com/17272433/362602328-3d7dfdc2-b2fd-4c30-a4bd-c51dd2c1023a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MjE0MDEsIm5iZiI6MTcyNDkyMTEwMSwicGF0aCI6Ii8xNzI3MjQzMy8zNjI2MDIzMjgtM2Q3ZGZkYzItYjJmZC00YzMwLWE0YmQtYzUxZGQyYzEwMjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA4NDUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwOTcwNzM5YjgzZWNkM2YxZDhmNDBhNWJiMWQ0NjE0M2ZiNTVjZDA2ZGU4MWYyMDMyNjQ4ZTg2NDU2OThjMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9VQG948PXJfBNrQv96tSAkc1I2HNvc_h-4_oLimbMgQ)
> 
> 我怀疑内容刚渲染的时候，svg宽高和不止和容器宽高有关系，还和浏览器窗口化或者说浏览器宽高有关系

并没有这回事，svg宽高只会根据容器元素计算

**Comment by wanglin2** [comment]
抖动是肯定的，因为重新计算了

**Comment by Tamcony** [comment]
> > > 全屏应该也会触发resize事件，无论是全屏还是调整窗口大小，或者是其他方式更改了容器元素的大小和位置，需要调用库的方法更新： ![image](https://private-user-images.githubusercontent.com/17272433/362602328-3d7dfdc2-b2fd-4c30-a4bd-c51dd2c1023a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MjE0MDEsIm5iZiI6MTcyNDkyMTEwMSwicGF0aCI6Ii8xNzI3MjQzMy8zNjI2MDIzMjgtM2Q3ZGZkYzItYjJmZC00YzMwLWE0YmQtYzUxZGQyYzEwMjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA4NDUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwOTcwNzM5YjgzZWNkM2YxZDhmNDBhNWJiMWQ0NjE0M2ZiNTVjZDA2ZGU4MWYyMDMyNjQ4ZTg2NDU2OThjMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9VQG948PXJfBNrQv96tSAkc1I2HNvc_h-4_oLimbMgQ)
> > 
> > 
> > 我怀疑内容刚渲染的时候，svg宽高和不止和容器宽高有关系，还和浏览器窗口化或者说浏览器宽高有关系
> 
> 并没有这回事，svg宽高只会根据容器元素计算

我刚刚看了一下源码，您使用了getBoundingClientRect来获取容器宽高，但是我刚刚打印了一下结果，同样使用这个api来获取宽高和vueuse的useElementSize获取宽高是有出入的，我想bug应该出在这里。
![image](https://github.com/user-attachments/assets/73cd178f-d516-4a78-91b0-6089c4d492cd)

**Comment by Tamcony** [comment]
两组值分别对应svg宽高和我的容器宽高
![image](https://github.com/user-attachments/assets/70526385-e6c0-4bc9-a385-e1a25bdd3a26)
![image](https://github.com/user-attachments/assets/0370c879-22ee-4607-a053-6f1593aedd23)

**Comment by 15378214096** [comment]
感谢,试了下抖动问题可以用addEventListener('resize')解决

**Comment by ZhangMingZhao1** [comment]
> 感谢,试了下抖动问题可以用addEventListener('resize')解决

解决了抖动问题？重新计算抖动是避免不了吧
