### ISSUE TITLE
有关使用格式刷将新创建的节点A的样式复制到节点B的思路

### ISSUE THREAD

**Issue by xiaobu474** [wanglin2/mind-map#826]
- 作者您好，我在查看格式刷插件的源码时，发现格式刷的实现方法为：将A节点的样式字段复制到style数组，再将style的字段复制到B节点内
- 这样会导致A中节点没有字段的样式（如A节点为刚创建的，它就不包含任何样式字段），无法复制到B节点，如新创建的节点A的字体为“微软雅黑”，B节点的字体为“宋体”，无法将A节点的“微软雅黑”样式复制到B节点
- 为了解决这个问题，我的思路为：在将style数组的样式字段复制到B之前，先将B节点的样式清除一下（我看到在Render.js文件中有去除一个节点的样式的方法），然后再将style数组的样式字段复制到B
- 希望我的探索能够成为解决这个问题的思路

**Comment by wanglin2** [comment]
很好的思路，已修改，v0.11.1+生效
