### ISSUE TITLE
自定义节点中的文本框失去焦点事件失效

### ISSUE THREAD

**Issue by ying-zhao-zy** [wanglin2/mind-map#827]
作者大大您好，我在vue3项目中使用了此插件
我用的一个vue3的组件作为自定义节点的内容，组件里有input文本框，但是在点击input框外面时 失去焦点的方法没办法触发了
期待您的回复

**Comment by wanglin2** [comment]
默认会阻止画布的mousedown事件的默认行为，所以只能通过监听画布的点击事件，来手动让输入框失焦

**Comment by ying-zhao-zy** [comment]
非常感谢
