### ISSUE TITLE
问题反馈：触摸板双指放大缩小灵敏度太高

### ISSUE THREAD

**Issue by ZhangMingZhao1** [wanglin2/mind-map#829]
双指缩放几乎控制不了，灵敏度太高。也希望有个最大最小缩放比例限制(可以用户传入配置)，类似processOn是20%-400%

**Comment by ZhangMingZhao1** [comment]
#533

**Comment by Tarrency** [comment]
<img width="287" alt="微信图片_20240918094606" src="https://github.com/user-attachments/assets/c62282f4-4ed0-4a46-9d13-cace361e9245">
这个公式等号右边/10大概率可以

**Comment by Tarrency** [comment]
区分触控板和鼠标行为的规则不太对，之前的规则无法给isTouchPad赋值为true。规律上如果是触控板行为，e.deltaY的绝对值是小于1的，我加了这行规则后，触控板行为是可以识别到的，放大缩放等的比例感觉正常了。
<img width="681" alt="image" src="https://github.com/user-attachments/assets/ed3f41c5-284f-474a-8308-e32ffa291c8e">

**Comment by Tarrency** [comment]
看了一下源码，判断是否是触控板的时候，监听了wheel事件的wheelDeltaY属性（Y轴滚动量）来区分鼠标和触控板行为。一般而言鼠标一次滚动130左右，触控板在10以内。但是这个参数在MDN上已经弃用了，wheelDeltaY目前对于鼠标和触控板的一次滚动行为都是130左右，因此无法区分鼠标和触控板行为。目前wheel事件使用deltaY来替代wheelDeltaY属性，用deltaY来区分即可，10以内判断为触控板行为应该就可以了。
<img width="530" alt="image" src="https://github.com/user-attachments/assets/5a401038-4097-43d2-a0b0-e907a33cada8">
<img width="391" alt="image" src="https://github.com/user-attachments/assets/ed61df51-1cea-412b-b4c9-0271b94683ef">

**Comment by wanglin2** [comment]
> 看了一下源码，判断是否是触控板的时候，监听了wheel事件的wheelDeltaY属性（Y轴滚动量）来区分鼠标和触控板行为。一般而言鼠标一次滚动130左右，触控板在10以内。但是这个参数在MDN上已经弃用了，wheelDeltaY目前对于鼠标和触控板的一次滚动行为都是130左右，因此无法区分鼠标和触控板行为。目前wheel事件使用deltaY来替代wheelDeltaY属性，用deltaY来区分即可，10以内判断为触控板行为应该就可以了。 <img alt="image" width="530" src="https://private-user-images.githubusercontent.com/47913683/368437864-5a401038-4097-43d2-a0b0-e907a33cada8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MDgyODAsIm5iZiI6MTcyNjcwNzk4MCwicGF0aCI6Ii80NzkxMzY4My8zNjg0Mzc4NjQtNWE0MDEwMzgtNDA5Ny00M2QyLWEwYjAtZTkwN2EzM2NhZGE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDAxMDYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxYzIwOTYzYTk4ZjQ0OTc3NTYyNGRlYzI0YWE3ZDNkMWE5NjgzMzc0ZjYzMTdjZDc4N2QwYjQxZTQ4Njg0ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zE_tKLvC2QAz2_zoftOtrmhAg2nRoLRLwNgSyB0xZ00"> <img alt="image" width="391" src="https://private-user-images.githubusercontent.com/47913683/368438319-ed61df51-1cea-412b-b4c9-0271b94683ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MDgyODAsIm5iZiI6MTcyNjcwNzk4MCwicGF0aCI6Ii80NzkxMzY4My8zNjg0MzgzMTktZWQ2MWRmNTEtMWNlYS00MTJiLWI0YzktMDI3MWI5NDY4M2VmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDAxMDYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3OWIyZjdjMWJiNzI2NjcxOGVhNDkyMTZiYjRmYzYyZDRkMGI5NWFkYzQ3NGMyMzAzNWYyMDM5M2E0OWJmODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tCdGrfiL4uSBF9uIomnkzM4Hbu7lGb3uVcZORaQvicY">

仅这样判断其实也不够，双指滑动稍微快一点就超过10了

**Comment by Tarrency** [comment]
是的，其实可以监听touchmove事件，isTouchPad = true放在这个事件里。
<img width="517" alt="image" src="https://github.com/user-attachments/assets/6d72252a-2b47-499b-9566-61fc8ffbab81">

**Comment by Tarrency** [comment]
这个我可以研究一下，晚点提个pr

**Comment by Tarrency** [comment]
调研了一下，目前没有可靠的方法明确区分触控板和鼠标的滚动行为，阈值区分是可行的方法，大小可以设置成单次鼠标滚动量最小值，超过就是鼠标行为，反之是触控板。我这边测试，单次鼠标滚动的deltaY大概是73，单次触控板滚动是0.73，刚好是10倍。触控板的滚动分辨率很高，滚动量很低，一般用于进行微小的动作，思维导图上细雕的也很少用触控板大滑。个人认为deltaY阈值可以设高一点到50左右，同时触控板的大滑这种不常见的可以视作一次鼠标滚动行为。

**Comment by Tarrency** [comment]
也试了一下TouchEvent里的touchmove、touchstart、touchend，对触控板行为没反应，可能只对触摸屏有反应。
<img width="421" alt="image" src="https://github.com/user-attachments/assets/238cc51c-fda1-4161-991f-a50bc54d5dc3">

**Comment by Tarrency** [comment]
提了个pr https://github.com/wanglin2/mind-map/pull/886

**Comment by huangjincq** [comment]
@wanglin2 在mac触控板上，双指向下快速滑动的时候回产生x轴方向的偏移

我看查看了代码，是由于`isTouchPad=false`导致`stepX` `stepY` 的值获取错误

![Image](https://github.com/user-attachments/assets/761ff3a4-0509-4084-ae83-16416332f90c)

为什么会这样呢，是因为这个判断有问题

![Image](https://github.com/user-attachments/assets/10fb0b72-3ab0-4124-9c08-f0e5713354db)

当快速滚动的时候 deltaY 的值会大于10，进入了非触控板的条件

![Image](https://github.com/user-attachments/assets/30a499b5-d466-474c-9032-8e93f45625c1)

### 可能方案，无需判断 isTouchPad，直接都用  wheelDeltaX，wheelDeltaY, 是否可行？
