### ISSUE TITLE
退格键不能正常使用

### ISSUE THREAD

**Issue by shenxj1228** [wanglin2/mind-map#83]
页面上包含一个输入框，在下面绘制一个xmind之后，输入框使用退格键删除数据不能正常实现，现在通过
`
mindMap.keyCommand.pause()
`
来停止快捷键，好麻烦啊。

**Comment by suka233333** [comment]
建议看看文档
https://wanglin2.github.io/mind-map/#/doc/zh/render/%E6%96%B9%E6%B3%95

**Comment by wanglin2** [comment]
已修复~
