### ISSUE TITLE
【🐛bug】浏览器窗口化时，svg渲染的宽高和容器实际宽高不一致

### ISSUE THREAD

**Issue by Hakityc** [wanglin2/mind-map#830]
原因：svg渲染时通过getBoundingClientRect获取元素宽高，但浏览器窗口化时，getBoundingClientRect方法里的width和height与容器实际宽高不一致。
浏览器窗口化时用各种api获取容器宽高结果如图：
![image](https://github.com/user-attachments/assets/5fc28f85-c76e-486c-aff9-1971e2d5aa93)

**Comment by wanglin2** [comment]
浏览器窗口化是啥意思

**Comment by Tamcony** [comment]
![image](https://github.com/user-attachments/assets/a17fa899-0b2a-43a0-a96e-1962f6fe7948)

**Comment by Tamcony** [comment]
更深层次的原因我还在找，目前就发现只要是浏览器窗口化就会不一致

**Comment by Tamcony** [comment]
> ![image](https://private-user-images.githubusercontent.com/17272433/362644469-bf7c573d-7e72-45a0-9bd5-6831c52a94e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MjgwOTYsIm5iZiI6MTcyNDkyNzc5NiwicGF0aCI6Ii8xNzI3MjQzMy8zNjI2NDQ0NjktYmY3YzU3M2QtN2U3Mi00NWEwLTliZDUtNjgzMWM1MmE5NGU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDEwMzYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZTNkMWUxNzA5ZmQwNDFmYjQwODFmMmY3Mjk4OWQzMzY3YmM2ZjU5YmNhNmU4YTBjODZmODY1M2U4ZmRiMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QfKyVEkyumt5JvtwXeG6DDUb-YnGlsuS33lv15QBViw) ![image](https://private-user-images.githubusercontent.com/17272433/362644545-9b773a63-be80-4427-8471-145dfda698dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MjgwOTYsIm5iZiI6MTcyNDkyNzc5NiwicGF0aCI6Ii8xNzI3MjQzMy8zNjI2NDQ1NDUtOWI3NzNhNjMtYmU4MC00NDI3LTg0NzEtMTQ1ZGZkYTY5OGRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDEwMzYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkOWRhZWZmZDBkNGMyMjI5NmIzNDc4ZjBkODE4MzAwYjY0OGEwM2RlMzA2ZDFlYjY3YWJlNmJlY2IzZTVmMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VuEObNJYtsL2LaiJdpztfZEIQ82da_QKfQynIXTp9Wk) 调整窗口大小看着没问题

先变成窗口化再进入页面出发首次加载呢？我调整的时候也没发现问题，主要是初次加载的时候处于窗口化。

**Comment by wanglin2** [comment]
初次也没有问题
