### ISSUE TITLE
自定义收起显示内容的函数expandBtnNumHandler的具体实现与API文档不符

### ISSUE THREAD

**Issue by GrandeJu** [wanglin2/mind-map#835]
现在收起按钮显示的是该节点所有子孙的数量，但大多数思维导图软件的收起按钮显示是该节点直接后代的数量，想用expandBtnNumHandler自定义一下，文档上写的接受参数是节点实例，但查看源码发现传入参数还是算好的所有子孙数据
<img width="351" alt="微信图片_20240831110214" src="https://github.com/user-attachments/assets/721899f1-77c0-431c-8471-2ba68a42e6db">
<img width="491" alt="微信图片_20240831110220" src="https://github.com/user-attachments/assets/1cf2bd31-3f05-4094-a240-6a28ca9d4566">
希望能支持收起按钮显示直接后代数量

**Comment by wanglin2** [comment]
增加节点实例的回调参数，v0.11.1+生效
