### ISSUE TITLE
跪求大佬支持Freemind 格式

### ISSUE THREAD

**Issue by GettionHub** [wanglin2/mind-map#836]
Freemind 的文件夹目录生成脑图功能极为好用，然而其保存格式为.mm，无法导入到 mind-map 中，而 mind-map 的格式是.smm，在 Freemind 里同样也无法使用。在此，衷心希望有大佬能够进行适配。

**Comment by quanzhongxian** [comment]
导入到 mind-map ，我感觉可以自己解析文件

**Comment by wanglin2** [comment]
已支持，v0.11.1+可用
