### ISSUE TITLE
需求支持：组织结构模式支持曲线的连线

### ISSUE THREAD

**Issue by ZhangMingZhao1** [wanglin2/mind-map#838]
组织结构作为常用的一种结构，目前组织结构不支持曲线的连线：
![image](https://github.com/user-attachments/assets/cf99c2bc-b4f8-4067-b7bc-80668a46590a)

希望组织结构下也能选择左右视图的那种曲线，类似效果：
![image](https://github.com/user-attachments/assets/c5bf5b88-902d-4bb2-8f4c-751d7ba9ef2e)

**Comment by wanglin2** [comment]
已支持，v0.11.1+生效
