### ISSUE TITLE
联系线可否能支持手动调整位置，并且输入联系文本？

### ISSUE THREAD

**Issue by suka233333** [wanglin2/mind-map#84]
![image](https://user-images.githubusercontent.com/115850846/226240712-99860d2e-590f-4dd3-8e55-d732776a5e23.png)
如图

**Comment by wanglin2** [comment]
更新了一个版本，控制点可以调整了，文本后面再做吧，累了累了

**Comment by suka233333** [comment]
> 更新了一个版本，控制点可以调整了，文本后面再做吧，累了累了

大佬牛！！
