### ISSUE TITLE
mind新增节点后在naiveui的n-modal无法回退按钮

### ISSUE THREAD

**Issue by WINGSIGOD** [wanglin2/mind-map#841]
我使用了naiveui的表格作为父组件 
mind作为子组件
n-modal作为子组件用于修改naiveui的信息
点击行以后再进行跳转到mind 然后在mind只进行增加节点操作(只增加节点) 
再退回naiveui的表格 使用n-modal修改表格信息 无法使用backspace按钮(可以新增字符 无法回退)

**Comment by wanglin2** [comment]
可以给你表格的keydown和keyup事件阻止冒泡
