### ISSUE TITLE
动态请求并插入多级节点出现栈溢出的报错，该如何解决？

### ISSUE THREAD

**Issue by Hiohk** [wanglin2/mind-map#842]
背景：我每次点击节点请求下一级数据，并插入请求到的节点数据，当节点数量或操作级别一多时，就出现栈溢出的报错，请问该如何解决？
<img width="944" alt="255054665001" src="https://github.com/user-attachments/assets/846cb5dd-ae1a-4137-8916-53dc47121520">

**Comment by wanglin2** [comment]
提供一下关键代码

**Comment by Hiohk** [comment]
<img width="531" alt="255066695276" src="https://github.com/user-attachments/assets/61b11dfc-50da-46ad-953b-43ff881ac717">
这是插入请求到的节点的步骤，我是每次点击请求下一级节点

**Comment by Hiohk** [comment]
![Uploading 17255068812174.png…]()

**Comment by Hiohk** [comment]
<img width="960" alt="5068812174" src="https://github.com/user-attachments/assets/34731ba8-ecef-4bad-990b-4226ff803002">

**Comment by quanzhongxian** [comment]
我感觉你这个node_tree_render_end监听，导致无限循环

**Comment by wanglin2** [comment]
> <img alt="255066695276" width="531" src="https://private-user-images.githubusercontent.com/72732320/364612516-61b11dfc-50da-46ad-953b-43ff881ac717.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MzAzMDIsIm5iZiI6MTcyNTUzMDAwMiwicGF0aCI6Ii83MjczMjMyMC8zNjQ2MTI1MTYtNjFiMTFkZmMtNTBkYS00NmFkLTk1M2ItNDNmZjg4MWFjNzE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDA5NTMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1Yjk5NDllYWU3ZDQ1NTdlZDkzNzQ2ZTJlYmFmYTA0MmE4YTljOTAxZTliMWI1ZjNlOTkyYzU0MjYxY2ExMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9PLm6xDF743GTkp5USWVZ04pWoTT3xEn_ae_gBrFrXM"> 这是插入请求到的节点的步骤，我是每次点击请求下一级节点

点击啥呢，节点吗

**Comment by Hiohk** [comment]
是的，我的需求是右键菜单点击选项加载下一级节点，请求数据并插入新的节点，因为数据太多一次请求页面渲染时会卡死

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月05日 17:55 |
| 收件人 | wanglin2/mind-map ***@***.***> |
| 抄送人 | Hiohk ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [wanglin2/mind-map] 动态请求并插入多级节点出现栈溢出的报错，该如何解决？ (Issue #842) |

这是插入请求到的节点的步骤，我是每次点击请求下一级节点

点击啥呢，节点吗

**Comment by wanglin2** [comment]
按你的代码试了一下，没出现问题，除非能提供更多信息，不然我也不知道

**Comment by Hiohk** [comment]
不是一操作就会报错，当添加的节点多会问题，不知道您是否试过在多节点下进行操作

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月05日 18:06 |
| 收件人 | wanglin2/mind-map ***@***.***> |
| 抄送人 | Hiohk ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [wanglin2/mind-map] 动态请求并插入多级节点出现栈溢出的报错，该如何解决？ (Issue #842) |

按你的代码试了一下，没出现问题，除非能提供更多信息，不然我也不知道

**Comment by wanglin2** [comment]
> 不是一操作就会报错，当添加的节点多会问题，不知道您是否试过在多节点下进行操作
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年09月05日 18:06 | | 收件人 | wanglin2/mind-map ***@***.***> | | 抄送人 | Hiohk ***@***.***>, Author ***@***.***> | | 主题 | Re: [wanglin2/mind-map] 动态请求并插入多级节点出现栈溢出的报错，该如何解决？ (Issue #842) | 按你的代码试了一下，没出现问题，除非能提供更多信息，不然我也不知道 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

多节点是啥意思

**Comment by Hiohk** [comment]
就是渲染的数据比较多的情况下，多次插入子节点

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月05日 18:31 |
| 收件人 | wanglin2/mind-map ***@***.***> |
| 抄送人 | Hiohk ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [wanglin2/mind-map] 动态请求并插入多级节点出现栈溢出的报错，该如何解决？ (Issue #842) |

不是一操作就会报错，当添加的节点多会问题，不知道您是否试过在多节点下进行操作
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 发送日期 | 2024年09月05日 18:06 | | 收件人 | wanglin2/mind-map @.> | | 抄送人 | Hiohk @.>, Author @.> | | 主题 | Re: [wanglin2/mind-map] 动态请求并插入多级节点出现栈溢出的报错，该如何解决？ (Issue #842) | 按你的代码试了一下，没出现问题，除非能提供更多信息，不然我也不知道 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***>

多节点是啥意思

**Comment by Hiohk** [comment]
> 虽然不知道你node_tree_render_end代码，但是我感觉你这个node_tree_render_end监听，有别的操作，导致无限循环在node_tree_render_end里面
我感觉应该不是这个问题导致的，因为我只有在小地图中监听了node_tree_render_end，其余并未使用，我注释掉小地图那部分组件，还是有这个问题

**Comment by Hiohk** [comment]
> 虽然不知道你node_tree_render_end代码，但是我感觉你这个node_tree_render_end监听，有别的操作，导致无限循环在node_tree_render_end里面

我感觉应该不是这个问题导致的，因为我只有在小地图中监听了node_tree_render_end，其余并未使用，我注释掉小地图那部分组件，还是有这个问题

**Comment by wanglin2** [comment]
默认会激活新创建的节点，所以如果连续调用插入多个节点的命令，就会给所有新创建的节点继续执行添加命令，那是会卡死的

**Comment by Hiohk** [comment]
该如何解决呢？

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月05日 18:50 |
| 收件人 | wanglin2/mind-map ***@***.***> |
| 抄送人 | Hiohk ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [wanglin2/mind-map] 动态请求并插入多级节点出现栈溢出的报错，该如何解决？ (Issue #842) |

默认会激活新创建的节点，所以如果连续调用插入多个节点的命令，就会给所有新创建的节点继续执行添加命令，那是会卡死的

**Comment by wanglin2** [comment]
试试createNewNodeBehavior选项设置为NOT_ACTIVE，如果还不行，那只能想办法避免连续调用

**Comment by Hiohk** [comment]
> 默认会激活新创建的节点，所以如果连续调用插入多个节点的命令，就会给所有新创建的节点继续执行添加命令，那是会卡死的

我每次加载并插入节点之前是先执行的右键操作（先激活该节点），所以应该不会激活上一步创建的节点把？我的理解不知道对不对？

**Comment by Hiohk** [comment]
> 试试createNewNodeBehavior选项设置为NOT_ACTIVE，如果还不行，那只能想办法避免连续调用

行，我试试
