### ISSUE TITLE
[BUG] 一个页面存在过多个思维导图（创建多个或先创建删除再创建）场景，FormulaPlugin存在内存泄漏问题

### ISSUE THREAD

**Issue by GrandeJu** [wanglin2/mind-map#844]
1、FormulaPlugin的extendQuill操作没有像RichTextPlugin加了一个extended标志位防止重复Quill.register相同的功能，会导致可以Quill.register多个formats/formula的CustomFormulaBlot
2、FormulaPlugin的extendQuill里面通过self=this引用了本身，此CustomFormulaBlot又被register到Quill里，被Quill引用，销毁思维导图时，这些对象都无法释放（Quill->CustomFormulaBlot->FormulaPlugin->MindMap）

**Comment by wanglin2** [comment]
已修改，v0.11.2+生效
