### ISSUE TITLE
view.fit 位置错误

### ISSUE THREAD

**Issue by DerrickTel** [wanglin2/mind-map#845]
容器div，默认是`right: -1000`，渲染完毕，点击按钮改成`right: 0` （抽屉效果。）这个时候，enlarge放大，narrow缩小。位置都不会变化。而`fit`他的默认位置不是当前的重心，而是默认情况下`right: -1000`的中心。

**Comment by wanglin2** [comment]
容器位置改变了请调用mindMap.,getElRectInfo()更新库的状态
