### ISSUE TITLE
客户端：能不能增加一个记住窗口大小的功能

### ISSUE THREAD

**Issue by 106088076** [wanglin2/mind-map#846]
它能记住节点在画布上的位置，已经很好用了，如果能记住上次打开窗口大小那就完美了，不然每次打开都要调整窗口大小

**Comment by quanzhongxian** [comment]
> 它能记住节点在画布上的位置，已经很好用了，如果能记住上次打开窗口大小那就完美了，不然每次打开都要调整窗口大小

如果是自己使用插件的话，存一下本地不就行了？或者存服务器

**Comment by wanglin2** [comment]
说的应该是客户端把

**Comment by 106088076** [comment]
额！就是创建的文件，打开的时候那个窗口

> 说的意思是客户端把

**Comment by 106088076** [comment]
> > 它可以记住剩余在剩余上的位置，已经很好用了，如果能记住刚才打开窗口大小那就完美了，否则每次打开都要调整窗口大小
> 
> 如果是自己使用插件的话，存一下本地不就行了？或者存服务器

可以用插件保持文件窗口的大小吗？

**Comment by wanglin2** [comment]
已支持，v0.11.2+生效
