### ISSUE TITLE
html文件怎么使用啊，为什么报错，路径是对的

### ISSUE THREAD

**Issue by quanzhongxian** [wanglin2/mind-map#852]
![image](https://github.com/user-attachments/assets/230f1221-e1b5-4a7f-b9b6-16827d594a8a)

**Comment by wanglin2** [comment]
请看文档：https://wanglin2.github.io/mind-map-docs/start/start.html

**Comment by quanzhongxian** [comment]
> 请看文档：https://wanglin2.github.io/mind-map-docs/start/start.html

为什么会出现乱码
![image](https://github.com/user-attachments/assets/ce473bb0-fb94-4b59-9317-2b064b630457)
