### ISSUE TITLE
请问如何利用API来动态添加、删除节点？

### ISSUE THREAD

**Issue by yc-huang** [wanglin2/mind-map#86]
我的场景里期望有类似这样的api： addChild(parentNode, {data...}) 和 removeNode(node)，parentNode或者node并不是当前激活的node。添加或者删除后，脑图上应该及时渲染来添加、删除对应的节点，并且不要影响其他的部分，不知道目前设计下应该怎么调用来实现？

添加这块尝试下来好像用parentNode.nodeData.children.push({ data...}) 然后mindmap.render()好像是可以的， 但parentNode.addChild(new Node({data...}))就工作不正常。

删除这块还没找到完全工作正常的调用组合；用renderer.removeOneNode(node)然后mindmap.render()总是删除不干净，连线是没了，不过文字好像总是还在。

**Comment by wanglin2** [comment]
添加子节点就是你写的这样parentNode.nodeData.children.push({ data...}) 然后mindmap.render()，addChildren方法不会修改原始数据，只会在类中添加，所以是不行的。
删除的话确实比较麻烦，你可以这样试试：
const removeNode = (node) => {
    if (node.isRoot) {
        // 根节点
        root.children.forEach(child => {
            child.remove()
          })
          root.children = []
          root.nodeData.children = []
    } else {
        if (node.isGeneralization) {
          // 如果是概要节点
          this.mindMap.renderer.setNodeData(node.generalizationBelongNode, {
            generalization: null
          })
          node.generalizationBelongNode.update()
        } else {
            // 其他节点
            this.mindMap.renderer.removeOneNode(node)
        }
    }
    this.mindMap.render()
}
这两个方法后续版本会加上。

**Comment by yc-huang** [comment]
谢谢，在我的环境里老是删除不干净，哪怕删除的是叶子结点（没有children的），用removeOneNode 或者 exeCommand('REMOVE_NODE')删除, 然后render/reRender都会遗留些东西；但我看demo应用好像就不会有这样的问题...

**Comment by yc-huang** [comment]
采用了一种workaround方案， 就是改成自己来维护data， 然后mindmap.setData() & render()

**Comment by yc-huang** [comment]
目前的add实现有一个潜在问题，就是add后再getChildren，很可能不能看到刚add的。。。
