### ISSUE TITLE
为什么text多了这些标签？我明明是纯文本的

### ISSUE THREAD

**Issue by quanzhongxian** [wanglin2/mind-map#861]
![image](https://github.com/user-attachments/assets/c8ff52f6-415b-4530-947f-ff66739ae5ec)

**Comment by wanglin2** [comment]
可能因为你注册了RichText插件

**Comment by quanzhongxian** [comment]
> 可能因为你注册了RichText插件

我这样引入的    <script type="text/javascript" src="__STATIC__/simple-mind-map/dist/simpleMindMap.umd.js"></script>
没有注册

**Comment by wanglin2** [comment]
打包后的文件是包含所有插件的

**Comment by quanzhongxian** [comment]
> 打包后的文件是包含所有插件的

怎么解决呢

**Comment by wanglin2** [comment]
![image](https://github.com/user-attachments/assets/5ad078ad-89ba-4092-91d4-1d3dc4a70ab9)
