### ISSUE TITLE
富文本模式下，新建节点与新导入smm的思维导图的节点的“样式字段”依旧都是乱序排序的

### ISSUE THREAD

**Issue by xiaobu474** [wanglin2/mind-map#867]
问题如标题所示，具体表现为：
1.富文本模式，在smm中新导入一个思维导图后，对其中节点双击打开编辑模式，即使未修改文本也会添加历史记录
2.在上述操作之后，再进行“双击打开编辑模式”操作，未修改文本时，“双击打开编辑模式”操作就不会添加历史记录
3.因此认为在导入思维导图时，也需要对其节点的“样式字段”排下序

补充：富文本模式下，当新建节点时，其样式字段也是乱序的

**Comment by wanglin2** [comment]
暂不修改，1.只要编辑过的富文本，下次导出后也不会乱序，那么每次导入都排序没有必要；2.新建节点不是样式乱序的问题，而是quill会修改样式，比如会将16进制的颜色值修改为rgba，所以没有办法
