### ISSUE TITLE
M1 Mac打开提示已损坏

### ISSUE THREAD

**Issue by xygkevin** [wanglin2/mind-map#871]
M1 Mac打开提示已损坏

<img width="260" alt="image" src="https://github.com/user-attachments/assets/6bb10228-8638-4519-a836-ad9e8f536ed8">
<img width="472" alt="image" src="https://github.com/user-attachments/assets/525ecba5-72ca-4c74-b5dc-8f558d38d9d5">

**Comment by wanglin2** [comment]
![image](https://github.com/user-attachments/assets/cf97f1fc-3fb9-4770-9d23-eeffd5f56284)
这三个都不行？

**Comment by xygkevin** [comment]
arm64的不行，univarsal的可以

**Comment by wanglin2** [comment]
那就用univarsal的呗
