### ISSUE TITLE
问题交流：simple-mind-map如何发包

### ISSUE THREAD

**Issue by ZhangMingZhao1** [wanglin2/mind-map#872]
![image](https://github.com/user-attachments/assets/d2df941f-fa61-4c68-94c2-6a4d1045ac39)
![image](https://github.com/user-attachments/assets/ccd12593-2c91-47db-99be-b61fbae0fb49)

simple-mind-map 源码里没看到build相关命令，但npm包里有多个格式的dist文件和types文件，是作者没把本地的打包命令暴露出来吗，如果我现在想基于自己的simple-mind-map二次开发分支发一个私有包，是需要自己实现build这块脚本吗，想问下有没有能复用的地方呢？

**Comment by wanglin2** [comment]
复用了web项目的vue-cli来打包的
