### ISSUE TITLE
当节点比较多时，导出png和pdf报错

### ISSUE THREAD

**Issue by DjMok** [wanglin2/mind-map#873]
当节点比较多时，导出svg没问题，导出png时，png文件大小为0，导出pdf时期，前端js报错
![导出成pdf报错](https://github.com/user-attachments/assets/a1505ac0-0209-47ec-8674-b1009682b603)
![惠阳区受纳场导图](https://github.com/user-attachments/assets/5a2d09af-de77-4d19-adf8-ec9ec4f53d8c)
[数据格式.json](https://github.com/user-attachments/files/17002053/default.json)

**Comment by wanglin2** [comment]
图片超出canvass大小限制导出失败的问题已修复。v0.11.2+生效
