### ISSUE TITLE
切换主题时报错，页面会一直处于loading状态，官方在线页面可以复现

### ISSUE THREAD

**Issue by lshahah** [wanglin2/mind-map#879]
<img width="1436" alt="image" src="https://github.com/user-attachments/assets/b2d38f8d-6ed8-4255-9c6e-609ae7838e97">
[思维导图.json](https://github.com/user-attachments/files/17042124/default.json)

**Comment by wanglin2** [comment]
已修复，v0.11.2+版本生效
