### ISSUE TITLE
使用自定义节点后，开始自由拖拽enableFreeDrag失效

### ISSUE THREAD

**Issue by s-kuswin** [wanglin2/mind-map#880]
使用自定义节点后，开始自由拖拽enableFreeDrag，也不能拖拽节点

**Comment by wanglin2** [comment]
不自定义节点是可以的？

**Comment by wanglin2** [comment]
自定义节点并没有限制拖拽，可以检查一下是否阻止了自定义元素鼠标相关事件的冒泡，以及是否注册了Drag插件
