### ISSUE TITLE
右键菜单超出边界

### ISSUE THREAD

**Issue by vicenteyu** [wanglin2/mind-map#881]
![image](https://github.com/user-attachments/assets/ad65864e-2bc5-49f5-badf-b5dca91c03cf)
如图，右键菜单的二级目录已经超出边界，无法正常使用。

**Comment by wanglin2** [comment]
![image](https://github.com/user-attachments/assets/05696944-d75b-4018-a799-983230d856d4)
版本是最新的么

**Comment by vicenteyu** [comment]
> ![image](https://private-user-images.githubusercontent.com/17272433/368853232-05696944-d75b-4018-a799-983230d856d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MjY1OTgsIm5iZiI6MTcyNjcyNjI5OCwicGF0aCI6Ii8xNzI3MjQzMy8zNjg4NTMyMzItMDU2OTY5NDQtZDc1Yi00MDE4LWE3OTktOTgzMjMwZDg1NmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDA2MTEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2MzZmNTdmMjE5NWVmZDc5Y2U3YjFjNWZmOTk3NzJlZWEwZWM4NzU3Zjc0OTNjMmQzMDMyMzNlZDY2YmZiNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-2PS9Jbe4azjRhZZelpsr9k1sxupZKtBuB575-YiBE4) 版本是最新的么

是的。0.11.1

**Comment by wanglin2** [comment]
最新的应该没有问题，不知道你是怎么触发的
![image](https://github.com/user-attachments/assets/0ff1ca88-2099-435a-8d17-13d371658bc8)

**Comment by vicenteyu** [comment]
使用Microsoft Edge 浏览器，跟这个有关？

**Comment by wanglin2** [comment]
![image](https://github.com/user-attachments/assets/a7b8538a-b01b-4d57-a281-5e473370e287)

试了一下也没问题，神奇了

**Comment by vicenteyu** [comment]
![20240919-145014](https://github.com/user-attachments/assets/eaf49ac4-1ca0-4f23-a65f-158a26580843)
[mind-map.zip](https://github.com/user-attachments/files/17054824/mind-map.zip)

**Comment by wanglin2** [comment]
已修复，v0.11.2+可用
