### ISSUE TITLE
Bug：节点富文本编辑能粘贴图片

### ISSUE THREAD

**Issue by wanglin2** [wanglin2/mind-map#885]

**Comment by wanglin2** [comment]
https://github.com/slab/quill/issues/4337

完了，改不动

**Comment by wanglin2** [comment]
已修复，v0.11.2+生效

**Comment by dingdangdog** [comment]
你好，我使用quill编辑器时也由于 https://github.com/slab/quill/issues/4337 问题导致图片处理异常，发现你的处理方案如下：
![image](https://github.com/user-attachments/assets/113d539d-c198-499c-aa46-4c17980a19d4)

但我尝试了一下，这样并没有阻止图片的粘贴，请问你这样做成功阻止了图片粘贴吗？

我现在需要手动删除默认粘贴的base64图片，才能起到不粘贴的效果，但是这样图片会闪一下，很别扭，所以来请教一下，我的代码：

![image](https://github.com/user-attachments/assets/93096e51-786d-4547-a7a9-b381237ff60b)

**Comment by dingdangdog** [comment]
经过调试发现 `e.preventDefault()` 确实是没起作用，你的解决方案中真正实现无法粘贴图片的功能的，应该在 `formatText` 相关的代码中，发现你只保留了 `string` 文本，所以没有粘贴上图片。不知道是不是这样？

**Comment by wanglin2** [comment]
起作用了的，没有这个拦截是可以粘贴图片的。

**Comment by wanglin2** [comment]
> 经过调试发现 `e.preventDefault()` 确实是没起作用，你的解决方案中真正实现无法粘贴图片的功能的，应该在 `formatText` 相关的代码中，发现你只保留了 `string` 文本，所以没有粘贴上图片。不知道是不是这样？

起作用了的，没有这个拦截是可以粘贴图片的。
