### ISSUE TITLE
中文输入法的第一个字母无法捕捉

### ISSUE THREAD

**Issue by xiaobu474** [wanglin2/mind-map#889]
客户端里：微软的中文输入法下，激活一个节点不打开编辑模式下，直接输入文字，输入的第一个字母不会被输入法捕捉（chrome打开的网页版不会出现问题），如图
![输入问题](https://github.com/user-attachments/assets/1a053b1e-b022-468a-9ada-03a1ac5f2c62)

**Comment by wanglin2** [comment]
v0.13.0+改为忽略第一个按键的值，仅用于触发进入编辑
