### ISSUE TITLE
拖拽逻辑可否再优化一下

### ISSUE THREAD

**Issue by suka233333** [wanglin2/mind-map#89]
如图：
![image](https://user-images.githubusercontent.com/115850846/228108718-08b8fd7d-5c3f-4741-99bd-20717d4fc178.png)

可能有用的信息：
1.这篇文章分析实现拖拽的方法很厉害，似乎可以参考一下：https://juejin.cn/post/7202495679405654075
2.[在线demo](https://rockyren.github.io/mindmaptree/resume.html?debug=1)

**Comment by wanglin2** [comment]
我觉得也不用这么麻烦，直接用鼠标当前的位置去计算就好了，除非上下两个节点完全挨在一起

**Comment by wanglin2** [comment]
已优化~
