### ISSUE TITLE
客户端需求：关闭全屏查看与全屏编辑

### ISSUE THREAD

**Issue by xiaobu474** [wanglin2/mind-map#890]
请问如果我想要关闭客户端中的“全屏查看”与“全屏编辑”这两个按钮，请问需要在哪个文件上操作呢

**Comment by wanglin2** [comment]
如果你是开发者，那么可以修改改文件，然后重新打包客户端：https://github.com/wanglin2/mind-map/blob/electron/web/src/pages/Edit/components/NavigatorToolbar.vue
如果不是，那是无法关闭的

**Comment by xiaobu474** [comment]
非常感谢您的回答，这解决了我的问题
