### ISSUE TITLE
结构为思维导图时，节点的排列逻辑与主流软件不同

### ISSUE THREAD

**Issue by Fly204810** [wanglin2/mind-map#891]
这是mind-map的
![image](https://github.com/user-attachments/assets/795bd035-9b84-4b43-8b80-9c50f4a5d18f)

这是xmind的
![image](https://github.com/user-attachments/assets/24cbee47-1284-4f8c-bc3f-57a3da1bf8e0)

注1：结构设为思维导图；添加分支节点时，顺序为1、2、3、4

注2：此时，“是否开启节点自由拖拽”选项失效

感谢您的付出。

**Comment by wanglin2** [comment]
已修改，v0.12.2+版本生效。
