### ISSUE TITLE
bug反馈：执行execCommand('INSERT_CHILD_NODE', false); 触发node_active的表现不一致

### ISSUE THREAD

**Issue by ZhangMingZhao1** [wanglin2/mind-map#894]
监听node_active的表现：

如果是执行execCommand('INSERT_CHILD_NODE') 不带false，会触发两次，参数传递为
<img width="313" alt="image" src="https://github.com/user-attachments/assets/d701919e-85b0-4320-b205-c0b495c03e40">

如果是执行execCommand('INSERT_CHILD_NODE', false)，带false，只会触发一次，参数为：
<img width="297" alt="image" src="https://github.com/user-attachments/assets/1e5c477f-e048-49ce-ac71-e6a3a5266584">

导致我一个公用的读取第一个参数node实例的方法读取不到数据，这个表现不一致的场景是bug 还是有什么考虑？

**Comment by wanglin2** [comment]
是bug，但是修不动

**Comment by wanglin2** [comment]
不确定是不是我理解的另一个问题，还是待我有空看看

**Comment by wanglin2** [comment]
不是bug，就是这么设计的，node_active的触发是不可控的，最好修改下你的代码
