### ISSUE TITLE
能否单独设置根节点的内边距，而非所有节点的内边距

### ISSUE THREAD

**Issue by wjw020206** [wanglin2/mind-map#895]
感谢作者大大的付出，不知道能否只设置根节点的内边距，就想默认根节点比其他节点大一点
我这里说的设置是指主题样式，我知道有 `node.setStyle`，但这个需要我自己触发，我想显示脑图的时候就默认那么大

**Comment by wanglin2** [comment]
给根节点数据带上内边距字段即可:
![image](https://github.com/user-attachments/assets/4446e079-19c4-4d25-86ba-ee866021ab0f)

**Comment by wjw020206** [comment]
> 给根节点数据带上内边距字段即可: ![image](https://private-user-images.githubusercontent.com/17272433/369785604-4446e079-19c4-4d25-86ba-ee866021ab0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNzc1MTMsIm5iZiI6MTcyNzA3NzIxMywicGF0aCI6Ii8xNzI3MjQzMy8zNjk3ODU2MDQtNDQ0NmUwNzktMTljNC00ZDI1LTg2YmEtZWU4NjYwMjFhYjBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDA3NDAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1ZDFmMDliMzVlYzFiYzJiMGYwZjRhZTE2YWMwOTg0ZTIxZjMwZDViMTAwYzMzYmZhMDY4MjgzMDZlNzM4OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J3g4kYnTRvLvxXrVI46EIyaLpfBBQInjvkj0oTkVZ1k)

好的，非常感谢作者大大的回复
