### ISSUE TITLE
怎么更改一个一个节点的文本 而不用整体都渲染一遍

### ISSUE THREAD

**Issue by onlyis** [wanglin2/mind-map#897]
怎么更改一个一个节点的文本 而不用整体都渲染一遍

**Comment by wanglin2** [comment]
不是很明白你的问题

**Comment by onlyis** [comment]
<img width="717" alt="image" src="https://github.com/user-attachments/assets/a017a15a-8da7-4531-98a5-f6f3726cad8b">
改节点文本内容

**Comment by wanglin2** [comment]
那别用这个方法就行，看看node实例的方法

**Comment by onlyis** [comment]
这个也行 但是我不确定比如我有1000节点 会只处理这一个编辑节点还是 都会处理 性能考虑，然后您说额node哪个方法可以呢

**Comment by onlyis** [comment]
setText 吧

**Comment by wanglin2** [comment]
对，没有只渲染单个节点的方法，都会整体过一遍的，但是数据没有变化的节点不会重新创建
