### ISSUE TITLE
问题反馈：在画布内点击，外部的dom contentEditable不会触发blur事件

### ISSUE THREAD

**Issue by ZhangMingZhao1** [wanglin2/mind-map#899]
<img width="699" alt="image" src="https://github.com/user-attachments/assets/50d7de15-0d95-4fc1-b655-37b5d4eeaa05">

如图，外面很多这种组件，有contentEditable的div编辑框，或者搜索下拉框，这些组件处于编辑态的时候，点击非画布区域，都能触发这些组件的失焦事件，但点击simple-mind-map画布或者点击画布内的节点/元素，触发不了这些组件的失焦事件，有没有什么解决思路

**Comment by wanglin2** [comment]
原因很简单，因为库阻止了容器元素mousedown事件的默认事件，增加了一个实例化选项来设置，v0.11.2+生效
