### ISSUE TITLE
问题反馈：节点active下，自己绘制的textrea 输入框聚焦状态下输入文字时 偶尔 会被节点输入事件拦截

### ISSUE THREAD

**Issue by ZhangMingZhao1** [wanglin2/mind-map#902]
![luzhi](https://github.com/user-attachments/assets/8fa89b28-8e05-4ff7-8165-b94d388c460b)

<img width="885" alt="image" src="https://github.com/user-attachments/assets/a0439dae-c87f-45c0-b928-eaceb5649a28">

点击编辑备注后，会在active节点下方渲染一个textarea，并且通过ref实例调用该textarea的focus自动聚焦，但有时候输入还是会被节点active接受键盘事件捕捉到(开启的节点选中自动接受键盘事件输入模式)，导致备注框自动消失，但有时候又不会被拦截(参考gif图的表现)，有什么解决思路？

**Comment by wanglin2** [comment]
阻止一下按键事件的冒泡试试吧

**Comment by ZhangMingZhao1** [comment]
> 阻止一下按键事件的冒泡试试吧

试了不行，keydown和keyup的阻止冒泡都试了

**Comment by ZhangMingZhao1** [comment]
![image](https://github.com/user-attachments/assets/a78fa8cc-1fec-4b3c-ab8b-d4d53c53fbc5)
![image](https://github.com/user-attachments/assets/278384e2-83f7-4f87-a34a-82b90fe0ec3d)

**Comment by ZhangMingZhao1** [comment]
![image](https://github.com/user-attachments/assets/4546fd98-6a42-4091-b213-224bfb7e5436)
看了下源码，节点的keydown事件simple-mind-map是绑定在windows上的，导致两个元素都会抢事件，我阻止冒泡也没用
