### ISSUE TITLE
公式为什么初始化不能渲染，而mindMap.execCommand('INSERT_FORMULA', 'a^2')就可以

### ISSUE THREAD

**Issue by quanzhongxian** [wanglin2/mind-map#903]
![image](https://github.com/user-attachments/assets/a505ec55-c0a9-441d-bb91-7e3aa03e4420)

**Comment by wanglin2** [comment]
公式渲染是需要调quill的方法的

**Comment by quanzhongxian** [comment]
没有找到这个quill在哪

**Comment by quanzhongxian** [comment]
> 公式渲染是需要调quill的方法的

文档没有找到
