### ISSUE TITLE
【BUG】demo中对于搜索替换功能，如果替换前是替换后的子串，则无法在点击enter搜索搜到替换后的内容

### ISSUE THREAD

**Issue by keep-link** [wanglin2/mind-map#904]
![WechatIMG1676](https://github.com/user-attachments/assets/4683c7a6-2339-4593-bb31-e22412b9d362)
如图所示
目录替换为小目录后，无法搜索到小目录节点

**Comment by wanglin2** [comment]
已修复，v0.11.3+生效
