### ISSUE TITLE
富文本编辑之后原来img的属性没有了？？？？

### ISSUE THREAD

**Issue by quanzhongxian** [wanglin2/mind-map#906]
![image](https://github.com/user-attachments/assets/8437f1b7-d436-499d-8e05-5b523003cd8e)

**Comment by quanzhongxian** [comment]
比如原本img 有一个属性 data-latex='6^6', 编辑之后，这个属性不见了

**Comment by wanglin2** [comment]
富文本只支持纯文本

**Comment by quanzhongxian** [comment]
这个可以保留img 的data-latex属性，在richtext.js开头使用，感觉可以支持一下，const Image = Quill.import('formats/image');

class LatexImage extends Image {
  static create(value) {
    let node = super.create(value);
    if (value.latex) {
      node.setAttribute('data-latex', value.latex);
    }
    return node;
  }

  static formats(domNode) {
    let formats = super.formats(domNode);
    if (domNode.hasAttribute('data-latex')) {
      formats.latex = domNode.getAttribute('data-latex');
    }
    return formats;
  }

  format(name, value) {
    if (name === 'latex') {
      if (value) {
        this.domNode.setAttribute('data-latex', value);
      } else {
        this.domNode.removeAttribute('data-latex');
      }
    } else {
      super.format(name, value);
    }
  }
}

LatexImage.blotName = 'image';
LatexImage.tagName = 'img';

Quill.register(LatexImage);

**Comment by quanzhongxian** [comment]
但是我不知道怎么传入覆盖

**Comment by wanglin2** [comment]
你可以直接修改RichText插件，然后注册你修改后的插件就行了

**Comment by wanglin2** [comment]
思维发散一下，插件就是一个js文件而已，你可以自己创建一个npm包，发布掉，其他人npm安装你的包然后引入注册就行
