### ISSUE TITLE
当富文本里面有图片时，编辑状态高度撑开了，但是结束编辑时，高度没有撑开

### ISSUE THREAD

**Issue by quanzhongxian** [wanglin2/mind-map#908]
![image](https://github.com/user-attachments/assets/98ec58b1-e02d-4a01-a642-985e9f07536d)

**Comment by wanglin2** [comment]
大兄弟，图片不在我的富文本支持范围内，有问题还需你自己研究

**Comment by quanzhongxian** [comment]
> 大兄弟，图片不在我的富文本支持范围内，有问题还需你自己研究

请问哪一个文件是计算节点高度的
