### ISSUE TITLE
Excel直接复制单元格无法粘贴到已激活的节点了

### ISSUE THREAD

**Issue by maybao** [wanglin2/mind-map#909]

**Comment by wanglin2** [comment]
啥意思

**Comment by maybao** [comment]
上个版本，我可以在excel里单击单元格（带有数字和公式）ctrl+c，然后在激活的节点里面ctrl+v，这样就能把excel里面的数字直接复制到节点里面，现在需要在excel里面单独数值数字才能成功粘贴到已经激活的节点里，或者直接ctrl+v生成子节点，会同时出现图片和文本。
![image](https://github.com/user-attachments/assets/da2f1e21-a0c0-4dd8-a180-aa4d0e458530)

![image](https://github.com/user-attachments/assets/de8e72eb-ec84-46e2-b655-9a77b6723fe6)
![image](https://github.com/user-attachments/assets/c98bac1d-c7f2-4fe8-b600-818f7b974488)

**Comment by maybao** [comment]
感谢大佬的软件，非常好用。

**Comment by wanglin2** [comment]
上个版本能粘贴是个bug。复制excel的单元格时会同时往剪贴板里塞文本和图片数据，文本编辑时粘贴会全部拦截掉，无法做到只拦截图片。至于激活节点直接粘贴时会同时出现图片和文本的问题，下个版本会修改成只粘贴文本。
