### ISSUE TITLE
问题反馈：getRect()返回的坐标数据没有文档解释

### ISSUE THREAD

**Issue by ZhangMingZhao1** [wanglin2/mind-map#912]
![image](https://github.com/user-attachments/assets/35493cb7-0fc8-4600-9c6c-ee672d2a7e11)

![image](https://github.com/user-attachments/assets/b75d71c1-562b-4421-8953-d20933271c50)

这坐标数据就返回了三种，不知道哪个是自己想要的，看源码调用了rbox方法，好像是svg.js提供的，看svgjs也没找到相关文档

**Comment by wanglin2** [comment]
其实我也不清楚，毕竟你也说了svgjs都没解释

**Comment by ZhangMingZhao1** [comment]
补充下为后面人做下解释吧，分别是矩形框矩形左上角，右下角，中心的坐标

**Comment by ZhangMingZhao1** [comment]
我这里补充下为后面人做下解释吧，应该分别是矩形框矩形左上角，右下角，中心的坐标
