### ISSUE TITLE
bug反馈：getRect()返回的数据有问题

### ISSUE THREAD

**Issue by ZhangMingZhao1** [wanglin2/mind-map#913]
#912 

这个api cx返回的是矩形节点中心坐标，x是左上角坐标，x2为右下角坐标，cx为中心坐标

<img width="492" alt="image" src="https://github.com/user-attachments/assets/75e9eef9-d950-490a-8838-eba4bb109d34">

![image](https://github.com/user-attachments/assets/987b3e99-f654-478c-9839-2d1a744f97b9)

点击图中框的两个二级节点，二级节点的x坐标应该是要相同的吧，但两个节点的getRect()实际返回的cx，x2横坐标两个都不相同，第一个有问题，第二个是正确的，导致我渲染备注框计算显示第一个有点歪了。除了二级节点，有多个同级节点情况下其他级别节点也有这种问题

**Comment by ZhangMingZhao1** [comment]
<img width="578" alt="image" src="https://github.com/user-attachments/assets/6027eee4-02ea-4a73-a545-cbdac0c3d4b9">
第一个没居中 有点歪

**Comment by ZhangMingZhao1** [comment]
![image](https://github.com/user-attachments/assets/1eb0f757-c7ea-43bb-a6eb-601133bca422)
因为两个width的宽度是不一样的

**Comment by ZhangMingZhao1** [comment]
发现有子节点和没有子节点，宽度就会有几px的差异

**Comment by wanglin2** [comment]
这不是bug就是这样的，group是节点最外层的容器，包括形状、边框、展开按钮整体的大小，你可以试节点实例本身的宽高和位置属性，或者通过节点的group获取里面某个元素的大小
