### ISSUE TITLE
bug反馈：node_active在设置节点第一次setIcon时触发一次，继续设置icon不再触发

### ISSUE THREAD

**Issue by ZhangMingZhao1** [wanglin2/mind-map#915]
节点都已经聚焦了，设置icon又会触发一次，我现在会在node_active里隐藏icon设置框， 导致第一次设置icon时icon隐藏(希望不隐藏)，后续设置又不隐藏，表现不一致。

**Comment by wanglin2** [comment]
算个bug，已修改，v0.11.3+生效
