### ISSUE TITLE
bug反馈：设置节点文字颜色后，备注icon颜色也变了。。

### ISSUE THREAD

**Issue by ZhangMingZhao1** [wanglin2/mind-map#916]
![image](https://github.com/user-attachments/assets/8e1acd91-9ec3-4627-b52f-9397cd31c6ba)

<img width="232" alt="image" src="https://github.com/user-attachments/assets/a67156c6-33bc-4ca7-9144-2a6ce97153a6">

有什么解决办法吗

**Comment by wanglin2** [comment]
不是bug，就是这么设计的

**Comment by ZhangMingZhao1** [comment]
> 如果你的个性化需求很多，建议还是fork一份自己修改源码

已经fork了，这里只是交流一下，看看是bug还是你的设计
