### ISSUE TITLE
需求支持：希望增加图片可拖拽最大值最小值的限制

### ISSUE THREAD

**Issue by ZhangMingZhao1** [wanglin2/mind-map#917]
![image](https://github.com/user-attachments/assets/1d43bfbc-30ad-4b58-a8d6-571dc71f4cfc)

主题里现在有imgMaxWidth, imgMaxHeight 图片显示的最大宽度高度，但图片拖拽插件可以无限制拖拽图片大小，和主题的这个限制没有兼容

**Comment by wanglin2** [comment]
已支持，v0.12.0+生效
