### ISSUE TITLE
关联线的箭头指向异常

### ISSUE THREAD

**Issue by Qpp0** [wanglin2/mind-map#918]
如图：
![image](https://github.com/user-attachments/assets/ac062d4d-6ade-4e13-a7cf-d82527b21ae5)

**Comment by Qpp0** [comment]
![image](https://github.com/user-attachments/assets/408c43a0-b767-43e7-83be-22da879b175e)
![image](https://github.com/user-attachments/assets/6148b86b-7304-4826-9009-5b00c054c5fa)

**Comment by wanglin2** [comment]
目前只能做到这样，你可以试试手动调整关联性
