### ISSUE TITLE
希望支持添加“任务节点” Task node

### ISSUE THREAD

**Issue by ninghsu267** [wanglin2/mind-map#919]
![image](https://github.com/user-attachments/assets/1fdd5a6f-4c78-4ac8-9f84-0c3724b59a72)
- 参考Xmind task node
- 支持增加带checkbox的任务节点task node

Nice to have
- 当子节点添加了多个任务节点时，根节点可根据子节点的完成情况显示进度

**Comment by wanglin2** [comment]
已支持，v0.12.1+可用。

进度显示暂不考虑。
