### ISSUE TITLE
bug反馈：在非富文本下，因为会删除reseRichText字段，所以“新建节点”操作需要撤回两次，这个问题会丢失一些历史操作

### ISSUE THREAD

**Issue by xiaobu474** [wanglin2/mind-map#920]
![image](https://github.com/user-attachments/assets/69c81b6e-5f52-41e7-9fd9-e185a0b8c930)

### 问题描述：
在已经关闭富文本的情况时，发现想要回退“新建节点”操作时，依旧需要点击回退按钮两次，原因如图所示：
-新建节点时，是包含reseRichText字段的
-在打开编辑模式并不进行文本修改，再关闭文本编辑模式后，reseRichText字段消失（注意这里一定要进入编辑模式后reseRichText字段才会被删除），被判断为可以撤回的一步，故撤回“新建节点”操作时，需要点击回退按钮两次

### 丢失操作：
-修改新建节点的行为“仅新增节点，不进入编辑模式”或“不激活节点”
-新建节点A，状态为A1，不进行编辑
-编辑节点B，由B1变成B2，撤回到B1
-双击A节点，不编辑，依旧为A1状态。此时B2的记录丢失

**Comment by wanglin2** [comment]
已修复，v0.12.0+生效
