### ISSUE TITLE
bug反馈：1. 备注无法识别本地文件的超链接。2. 桌面版无法拉伸改变节点边框长度。3. 桌面版打开超链接无法调用系统默认浏览器。

### ISSUE THREAD

**Issue by danhen** [wanglin2/mind-map#922]
1. 在**备注**中插入超链接，只能识别以http或https开头的超链接，无法识别本地文件的超链接，如：obsidian://adv-uri?vault=obsidian%E7%AC%94%E8%AE%B0%E6%9C%AC&uid=9c056be0-5331-41e4-b901-8ced98b244cb&block=9u2d1l。而不在备注中插入，直接用**超链接**功能，选择”无“，就能成功识别跳转。
![Snipaste_2024-10-07_16-37-57](https://github.com/user-attachments/assets/2273e995-6ade-46ce-ba4d-19a5d1d85544)
![Snipaste_2024-10-07_16-40-38](https://github.com/user-attachments/assets/c702a501-31d6-4d7d-a611-2e001ab344b7)

2. 桌面版节点边框不能拉伸改变长短，网页版的可以。
![Pasted image 20241007163254](https://github.com/user-attachments/assets/a5071372-0e7c-47df-bba2-1dc6a734843b)

3. 桌面版打开超链接无法调用系统默认浏览器，要是打开的是本地链接，会调出空白界面。
![Snipaste_2024-10-07_16-45-09](https://github.com/user-attachments/assets/02fee099-3e11-4b59-aaba-3836dedb932d)

软件很好用，简洁美观，小巧精悍😀😀😀

**Comment by wanglin2** [comment]
1.实现不了
2、3已支持，v0.12.1+可用
