### ISSUE TITLE
问题反馈：中文输入法第一次输入字符时，节点接受的文字颜色与主题节点文字颜色不符

### ISSUE THREAD

**Issue by ZhangMingZhao1** [wanglin2/mind-map#923]
中文输入法第一次输入的时候是黑色，如图：
![image](https://github.com/user-attachments/assets/9defa739-0530-4dfc-833f-c0418f4d78dd)

输入完成后才变为主题颜色
![image](https://github.com/user-attachments/assets/90ba0ab9-4ff9-4ead-8c59-135cd29a842f)

有文字后，后面再输入，颜色就恢复正常了：
![image](https://github.com/user-attachments/assets/c3231c47-a324-4add-9ac7-b3012b2f92ce)

**Comment by Tarrency** [comment]
这是quill富文本编辑器的问题。它默认的空行时候的状态就是这样，在空行状态下无法setAttribute，只有在有内容的时候才能setAttribute。
中文输入属于非直接输入，敲拼音的状态不属于输入实质内容，所以在空行没有中文只有拼音的时候，quill无法setAttribute。只有文本框里有直接输入的内容（中英文）的时候，quill才能setAttribute。

**Comment by wanglin2** [comment]
已修复，v0.13.0+生效
