### ISSUE TITLE
bug反馈：拖拽调整节点宽度后，图片导出异常

### ISSUE THREAD

**Issue by BoastKnight** [wanglin2/mind-map#924]
这是截图，第二个节点是拖拽过宽度的节点：
![image](https://github.com/user-attachments/assets/a80c8ea7-612d-450f-aa69-6ecef7b0fd99)

然后导出为图片后就是这样了：
![image](https://github.com/user-attachments/assets/902fc033-bd82-4ee6-9186-e856a2c39e83)

好像多输入一些文字就会变成这样

**Comment by watermelon0314** [comment]
想请教一下怎么实现的拖拽设置宽度呢

**Comment by wanglin2** [comment]
已修复，v0.12.0+生效
