### ISSUE TITLE
监听节点文本编辑框关闭事件hide_text_edit里修改当前节点文字样式无效

### ISSUE THREAD

**Issue by 51piaoling91** [wanglin2/mind-map#927]
我想在节点创建完成后默认修改为统一的样式

![image](https://github.com/user-attachments/assets/122ccef3-65cc-4ef7-a08c-91628859af61)
代码如上

![image](https://github.com/user-attachments/assets/bd8f5c51-2a9e-4f75-87cf-880e219080a4)
新增或者编辑节点回车后，控制栏就会一直打印

求大神看看怎么回事

**Comment by wanglin2** [comment]
可以试试如下方式：

mindMap.on('hide_text_edit', (a, b, node) => {
        node.setData({ fillColor: 'yellow', color: 'red', resetRichText: true })
      })

**Comment by 51piaoling91** [comment]
已经可以了，谢谢大佬！！！
