### ISSUE TITLE
感谢作者开发的工具，我基于你的工具开发了一个 Logseq 插件

### ISSUE THREAD

**Issue by b-yp** [wanglin2/mind-map#932]
仓库地址： https://github.com/b-yp/logseq-mind-map

该插件提供两个版本
- 插件版，运行在 [Logseq](https://logseq.com/) 中、
- Web 版，在线地址： https://logseq-mind-map.vercel.app/

再次感谢作者

**Comment by wanglin2** [comment]
点个赞
