### ISSUE TITLE
【BUG】在激活多个节点的时候，编辑某个激活节点，会导致所有的节点都被编辑

### ISSUE THREAD

**Issue by keep-link** [wanglin2/mind-map#936]
线上demo
![image](https://github.com/user-attachments/assets/26a493b4-7210-4714-bdd5-610a413d56e5)
![image](https://github.com/user-attachments/assets/ea719b9e-2fd6-48d9-8f24-afbdb654fdef)
![image](https://github.com/user-attachments/assets/c246df74-a37f-40fc-a7ef-68cf09564fc8)

**Comment by wanglin2** [comment]
已修改，v0.12.0+生效
