### ISSUE TITLE
bug反馈：开启原地编辑模式下且不使用富文本text，编辑时输入框定位会抖动

### ISSUE THREAD

**Issue by ZhangMingZhao1** [wanglin2/mind-map#940]
<img width="1267" alt="image" src="https://github.com/user-attachments/assets/8d30e3b6-9bf7-42bb-8228-2aa7495245d8">

条件：
openRealtimeRenderOnNodeTextEdit: true 
关闭richTextPlugin

单行输入时，输入框的left值计算会在两个值之间跳动导致输入框有抖动
![image](https://github.com/user-attachments/assets/1248f15c-e47f-4433-9884-beea059a9317)
![image](https://github.com/user-attachments/assets/d47ea7e1-c540-4e9f-9edc-9c07344348ef)
好像是updateTextEditNode这个方法的计算问题，但richText的这个方法没问题

**Comment by wanglin2** [comment]
已修复，v0.12.1+生效
