### ISSUE TITLE
bug反馈：设置maxImgResizeWidthInheritTheme: true后，第一次上传图片拖动图片到最大值会导致所有图片不能拖拽了

### ISSUE THREAD

**Issue by ZhangMingZhao1** [wanglin2/mind-map#942]
![image](https://github.com/user-attachments/assets/ed2bb4bb-4f9d-4c22-9045-f3c4aecb249d)

设置 maxImgResizeWidthInheritTheme: true

第一次上传图片，拖动到最大值，突然图片会闪一下，所有节点的图片hover时不再出现可拖拽选项，必须要强刷页面才能再拖拽

**Comment by wanglin2** [comment]
已修复，v0.12.1+生效
