### ISSUE TITLE
名字很长的话拖拽之后会出现错位

### ISSUE THREAD

**Issue by DerrickTel** [wanglin2/mind-map#944]
如题

**Comment by wanglin2** [comment]
不懂，截个图看看

**Comment by DerrickTel** [comment]
很抱歉，没法截图，公司内网不让拍照。

现在情况是：我拖拽一个比较长的节点之后，这个节点没有从父节点脱离。
导致这个被拖拽的节点有两个父节点了，一个拖拽后的，一个是拖拽前的。

**Comment by wanglin2** [comment]
或者你看看能不能在在线demo里复现，能的话说一下复现步骤
