### ISSUE TITLE
请问一下有没有同时移动X和Y的方法。文档里面没找到

### ISSUE THREAD

**Issue by DerrickTel** [wanglin2/mind-map#958]
https://wanglin2.github.io/mind-map-docs/api/view.html

**Comment by DerrickTel** [comment]
现在想向左下角或者右下角移动，要先X然后再Y不是很流畅

**Comment by wanglin2** [comment]
https://github.com/wanglin2/mind-map/blob/main/simple-mind-map/src/core/view/View.js#L184
