### ISSUE TITLE
多选节点设置样式，节点文本会被覆盖

### ISSUE THREAD

**Issue by suka233333** [wanglin2/mind-map#96]
![bug](https://user-images.githubusercontent.com/115850846/230294061-716e9bfd-18f8-48b9-a91d-ac2173642be6.gif)
步骤：
1.ctrl键+鼠标左键点选多个节点
2.任意设置节点样式
3.选中的节点的文本会被第一个点选的节点覆盖掉

**Comment by wanglin2** [comment]
已修复~
