### ISSUE TITLE
bug反馈：1.LaTex公式内容导出excel出现重复。2.较难触发节点拉伸状态。

### ISSUE THREAD

**Issue by danhen** [wanglin2/mind-map#962]
1. 桌面版和网页端的LaTex公式导出excel会将公式渲染前和渲染后的内容都导出来，希望去掉渲染后的，只导出渲染前的。如：“x²”会导出为“x2x^2﻿”，希望只导出为“x^2”。
![Snipaste_2024-10-29_11-24-55](https://github.com/user-attachments/assets/710ad204-faf5-4e8a-abc5-23760f5e75e6)

2. 桌面版和网页端的节点拉伸状态难以触发，需要将节点放大且比较小心移动鼠标才能比较容易触发拉伸节点状态，希望适当扩大鼠标在节点边缘时的触发范围或支持鼠标悬浮在节点边缘附近就触发。
![gif](https://github.com/user-attachments/assets/37a0e352-fedf-4511-8eda-b21ba0547bb9)

另外，能双击节点上的备注图标就能编缉备注内容就好了，现在每次改备注内容都得去点工具栏的图标，不是太方便。

LaTex公式编辑是目前我见过的最好的了，和其他文本无缝衔接，丝滑转换👍👍👍

**Comment by wanglin2** [comment]
1.已改为只导出公式源码
2.加大可拖拽区域大小
3.可以双击节点备注图标打开编辑弹窗
v0.12.2+可用。
