### ISSUE TITLE
拖动 超出视口问题

### ISSUE THREAD

**Issue by 2322312693** [wanglin2/mind-map#964]
文档中所有的demo 都 限制了 mindmap 不能拖动到视口意外

但是复制项目到本地开发 就会 可以拖动到视口意外

如下图

![image](https://github.com/user-attachments/assets/9726f36d-5ea4-43c9-803a-5bf7e4f5eb4b)
它可以无限被拖动

请问这是什么造成的

**Comment by wanglin2** [comment]
因为文档里的库包含了所有插件，包括滚动条插件，https://wanglin2.github.io/mind-map-docs/api/constructor/constructor-options.html#_9-scrollbar%E6%8F%92%E4%BB%B6，可以把这个选项改为false
