### ISSUE TITLE
问题探讨：0.11.2 版本好像并没有修复打开编辑框增加一次编辑历史记录的问题

### ISSUE THREAD

**Issue by ZhangMingZhao1** [wanglin2/mind-map#966]
#834 
我看834 issue是说0.11.1修复的，但本地版本0.11.2 发现还有这个问题，翻看历史commit ：https://github.com/wanglin2/mind-map/commit/1f303145c632427944f6cc24963c0c9a62eb0175

好像这个commit也不是解决这个问题的，但最新版本确实没有这个问题了，想问一下是在哪个commit解决的这个问题

**Comment by wanglin2** [comment]
就是这个commit修复的

**Comment by wanglin2** [comment]
不过不是完全修复，刚创建的节点，还是会有问题

**Comment by ZhangMingZhao1** [comment]
> 不过不是完全修复，刚创建的节点，还是会有问题

是的，我发现本地的问题就是tab 新建的子节点自动进入的编辑还是会多增加一条历史记录，这个我看在线demo中是问题的，但引用最新的包在我的工程发现还是有这个问题，这个是为什么呢
