### ISSUE TITLE
bug反馈：新建节点自动进入编辑模式，会默认多增加一条历史记录

### ISSUE THREAD

**Issue by ZhangMingZhao1** [wanglin2/mind-map#967]
表现上来看，新建用户没有对节点做额外操作，但实际多增加了一条记录，对新建操作要撤销两次才会把新建撤销掉

**Comment by Seven-Seven-7** [comment]
这个我看代码中data_change的事件触发了两次，针对一个增加节点的操作，其实变更了两次数据，第二次是失去焦点的时候会更改新增节点的样式。

**Comment by wanglin2** [comment]
已修复，v0.13.0+生效
