### ISSUE TITLE
主题切换bug反馈：亮色主题下对节点文字选择加粗，切换深色主题后，加粗过的节点文字样式没有应用主题样式，显示会变暗

### ISSUE THREAD

**Issue by ZhangMingZhao1** [wanglin2/mind-map#968]
![image](https://github.com/user-attachments/assets/24b5551d-4611-46a4-a6cc-c5fa08ac0180)
![image](https://github.com/user-attachments/assets/b15c78b0-9545-4539-a8a9-bc5e986b146f)
(设置开启的富文本模式，加粗是节点样式加粗方式)

**Comment by Tarrency** [comment]
显示不会变暗，但前面没有应用主题样式是个bug，提了个pr https://github.com/wanglin2/mind-map/pull/1000

**Comment by wanglin2** [comment]
已修改，v0.12.2+生效
