### ISSUE TITLE
需求支持：增加输入覆盖模式选项，节点选中模式下，键盘输入是直接覆盖所有文字，类似钉钉和飞书的脑图表现

### ISSUE THREAD

**Issue by ZhangMingZhao1** [wanglin2/mind-map#969]
![Kapture 2024-10-31 at 15 46 31](https://github.com/user-attachments/assets/20a67baa-6c7d-43a3-9e5d-6903be960793)

**Comment by Tarrency** [comment]
https://github.com/wanglin2/mind-map/pull/972

**Comment by Tarrency** [comment]
提了个prhttps://github.com/wanglin2/mind-map/pull/972

**Comment by Tarrency** [comment]
提了个pr https://github.com/wanglin2/mind-map/pull/972

**Comment by Tarrency** [comment]
提了个pr https://github.com/wanglin2/mind-map/pull/983

**Comment by wanglin2** [comment]
已支持，v0.12.2+生效
