### ISSUE TITLE
关于kity与svgjs该如何抉择呢？

### ISSUE THREAD

**Issue by liwuming** [wanglin2/mind-map#97]
作者您好，我也一直期望能开发一个思维导图，但是作为一个后端开发者，js技术太菜，看到您开发的这个思维导图真的太佩服了，想咨询您一个问题，关于kity与svgjs您当初是如何选择的？

我看了一些思维导图平台比如zhixi.com,还有gitmind.com,貌似都是使用的kity做的二次开发，但是kity的代码好多年没有更新了，技术比较旧，可能会有性能问题，所以想问一下您是如何选择的呢？

**Comment by wanglin2** [comment]
额，我当初就没考虑过用kity，一方面是因为不维护了，另一方面是文档都没看到，当初主要是在snap.svg和svgjs之间纠结了一些，至于zhixi和gitmind，他们可能是在kityminder-core基础上做的二次开发，因为kity和svgjs本质上只是操作svg的库，并没有任何思维导图的功能，所以如果不是因为想在kityminder-core上更快的开发，我实在想不出任何原因要使用kity

**Comment by liwuming** [comment]
好的，谢谢您
