### ISSUE TITLE
【问题】只读模式下无法触发node_contextmenu事件，导致对于节点的操作菜单无法展示

### ISSUE THREAD

**Issue by keep-link** [wanglin2/mind-map#971]
线上Demo，只读模式下右键点击节点展示的是svg的菜单
![image](https://github.com/user-attachments/assets/b5d9f8cf-680e-42c7-a376-c6f7c47a0f39)

**Comment by wanglin2** [comment]
只读模式是不显示右键菜单，因为不允许操作
