### ISSUE TITLE
[BUG]选中子节点展示的线条颜色不正确

### ISSUE THREAD

**Issue by Seven-Seven-7** [wanglin2/mind-map#977]
# 复现
1. 选中一个父节点，设置线条颜色为绿色
![image](https://github.com/user-attachments/assets/471b37df-4ee3-4696-a761-3499221b05fa)

2. 选中父节点的子节点，查看线条颜色，期望是绿色，实际没有变化
![image](https://github.com/user-attachments/assets/a73de648-38d5-4cc0-8149-7dcf2340d083)

**Comment by wanglin2** [comment]
不是bug，设计就是如此，设置只会影响节点本身的数据，不会影响下级节点的数据

**Comment by Seven-Seven-7** [comment]
现在的设计是设置父节点的线条会影响父节点以及所有子节点的颜色为绿色，

但是选中子节点展示的不是绿色。
