### ISSUE TITLE
问题反馈：当鼠标在画布内时，外部的input框处于聚焦状态时删除键(backspace)无效

### ISSUE THREAD

**Issue by ZhangMingZhao1** [wanglin2/mind-map#980]
![image](https://github.com/user-attachments/assets/61e99621-27fe-440c-b235-991047035fbc)

看起来好像是被画布内部画布拦截了删除键，其他键都是可以的，在线demo工程里也复现了这个问题

![image](https://github.com/user-attachments/assets/c503dc15-6e45-4bf7-897a-25d9a1b524a0)

**Comment by wanglin2** [comment]
阻止一下按键事件的默认事件好了

**Comment by wanglin2** [comment]
或者后面试试根据事件对象里的目标元素看看能不能不阻止

**Comment by ZhangMingZhao1** [comment]
> 或者后面试试根据事件对象里的目标元素看看能不能不阻止

 删除键这个拦截在哪里处理的呢，之前的冒泡问题（#930 ）我是在工程里用了一个全局的mouseDown监听来让画布内节点失焦解决的：
![image](https://github.com/user-attachments/assets/2bcafc86-3483-4906-aa7b-8aeb7ab7f8b7)

现在这个问题我没找到mind源码是哪里了拦截了backspace键

**Comment by wanglin2** [comment]
https://github.com/wanglin2/mind-map/blob/main/simple-mind-map/src/core/command/KeyCommand.js#L77

**Comment by ZhangMingZhao1** [comment]
<img width="749" alt="image" src="https://github.com/user-attachments/assets/166e48b9-3725-4f19-a9d4-3dc485e7895a">
我在这里加上了删除键的判断就好了，我看对画布节点的删除也没有影响，是否完全解决了这个问题呢？暂时也没发现引起其他问题

**Comment by wanglin2** [comment]
改为只有当事件目标为body和文本编辑框元素时才响应快捷键事件，v0.12.2+生效
