### ISSUE TITLE
复制粘贴问题

### ISSUE THREAD

**Issue by huang-yf3160** [wanglin2/mind-map#982]
[https://github.com/wanglin2/mind-map/blob/1d75e8519d98d6f75de9c6b139ae6cb87cefa78a/simple-mind-map/src/core/render/Render.js#L1194](url)

想了解一下为啥不以剪切板的数据为准，有什么特殊考虑吗？毕竟复制节点时也会往剪切板写内容

**Comment by wanglin2** [comment]
没有啥特殊考虑，只是当初这么做了而已，如果这样会有其他问题的话欢迎指出。

**Comment by huang-yf3160** [comment]
> 没有啥特殊考虑，只是当初这么做了而已，如果这样会有其他问题的话欢迎指出。

会出现某些不符合预期的情况

例如
当复制一个字符串 例如：https://wanglin2.github.io/mind-map/#/
然后在思维导图内粘贴
在复制一个节点，不粘贴
然后在复制一个和之前相同的字符串 https://wanglin2.github.io/mind-map/#/
此时粘贴出来的是节点，其实不太符合用户的预期

如果没有特殊考虑的话，感觉可以直接以剪切板的内容为准

**Comment by wanglin2** [comment]
已修改，v0.12.2+生效
