### ISSUE TITLE
bug反馈：富文本节点空格输入和回车输入渲染有一系列问题

### ISSUE THREAD

**Issue by ZhangMingZhao1** [wanglin2/mind-map#984]
1. 文字开头部分输入的空格，节点不能自适应增加宽度
![image](https://github.com/user-attachments/assets/8fdca578-e090-4581-b4bd-ab2b5b6fb23f)
输入结束的时候好像是会把开头的所有空格删除只留一个空格，但输入态空格又不能实时增加宽度，整体有点奇怪。

2. 输入数字加空格时，应该触发了quill的有序列表，输入态变成了：

![image](https://github.com/user-attachments/assets/bf0eef1c-2682-419c-87dc-8b949972989b)

输入结束后，节点渲染不支持这个样式，又消失了，整体也有点奇怪。(禁用quill的有序列表和无序列表应该可以解决)

3. shift + 回车换行时，光标已经换行，但节点高度没有变化，要输入文字后才会变化：
![image](https://github.com/user-attachments/assets/11896535-b525-4c9e-aaf6-840c4124b0ef)

**Comment by wanglin2** [comment]
都已修复，v0.12.2+生效
