### ISSUE TITLE
功能需求：希望在节点的右键菜单中实现“收起所有子分支”

### ISSUE THREAD

**Issue by xiaobu474** [wanglin2/mind-map#986]
### 需求总结
希望在节点的右键菜单中实现“收起所有子分支”
### 例子
前提：当A节点包含B子节点与C子节点，B与C又包含自己的子节点，B1、B2...与C1、C2...
1.目前：“折叠A节点”操作会将B与C折叠，且在“展开A节点”时，将B、C、B1、B2、C1、C2全部展开
2.希望做到：右键点击A接待你时，在菜单中可选“收起所有子分支”，达到目的：A的分支被收起了，将A展开时，只会显示B与C子节点，B1、B2、C1、C2依旧是收起状态
### 思路
这里实际上就是支持一键设置一个节点与其所有分支节点的“收起状态”

**Comment by wanglin2** [comment]
已添加，v0.12.2+可用
