### ISSUE TITLE
请问如何给节点加阴影？

### ISSUE THREAD

**Issue by xinnai** [wanglin2/mind-map#987]
没有找到节点阴影的配置，我尝试用自定义节点加阴影，但发现阴影还是会被节点截断，并且这个办法很麻烦，请问大佬们，有没有快捷方法？或者源码可以改哪块？感谢！
我的版本，富文本模式，0.12.1

**Comment by wanglin2** [comment]
foreignObject元素默认有overflow: hidden;的样式，可以试试自己覆盖掉

**Comment by xinnai** [comment]
感谢您快速回复，foreignObject对自定义节点好使，请问非自定义的节点怎么加呢？普通的富文本文字节点这种？

**Comment by wanglin2** [comment]
自己控制台样式调调咯，我也没研究过
