### ISSUE TITLE
切换主题，节点文字颜色不生效

### ISSUE THREAD

**Issue by xinnai** [wanglin2/mind-map#988]
您好，我的版本0.12.1，themes版本是1.0.0，使用的都是内置主题，当我切换主题的时候，文字的颜色总是最初default设置的颜色，根节点和其他节点**文字**颜色都没有改变，像边框、形状、背景色这些都是有效的，**只有文字颜色不好使**。
我尝试去掉default里的颜色设置，和节点数据里的颜色设置，都不好使，请大佬看看是什么原因。
`simpleMindMap.setTheme(v.value);
  simpleMindMap.setThemeConfig(v.theme);`

**Comment by wanglin2** [comment]
节点富文本设置的样式不会随主题切换，要去除请使用REMOVE_CUSTOM_STYLES或REMOVE_ALL_NODE_CUSTOM_STYLES命令
