### ISSUE TITLE
关于标签圆角不生效，能否加图标？

### ISSUE THREAD

**Issue by xinnai** [wanglin2/mind-map#989]
1、圆角设置不生效，颜色宽高是可以的
`{
        text: "标签",
        style: {
          background: "#55EAB1",
          fontSize: 14,
          borderRadius: 30, //不生效
          width: 60,
          height: 28,
          lineHeight: 28,
        },
      }`
2、能否为标签增加一个前置图标？

**Comment by wanglin2** [comment]
1.可能是你写的不对，可能是边框宽度为0
2.暂不考虑
