### ISSUE TITLE
富文本模式下，文字加粗功能不好使？

### ISSUE THREAD

**Issue by xinnai** [wanglin2/mind-map#990]
富文本模式下，默认主题设置`fontWeight: 'bold'`是可以加粗的，但如果执行`node.setStyle('fontWeight', 'normal')`之后，再次执行`node.setStyle('fontWeight', 'bold')`，就无法再次加粗了。
0.12.1版本

**Comment by wanglin2** [comment]
试了一下没问题，提问最好提供一下代码截图

**Comment by xinnai** [comment]
`
changeProperty(
      {
        fontWeight: !fontWeight.value || fontWeight.value == "normal" ? "bold" : "normal",
      }
    );
const changeProperty = (p: object) => {
    const nodes = mindmapStore.selectedNodeData;（activeNodeList）

    const key = Object.keys(p)[0];
    if (key == "rainbowLine") {
      if (p[key]) {
        changeAllLinkColor(key, p[key]);
      }
      return;
    }
    nodes.map((node) => {
      if (key == "icon") {
        //添加节点前面的图标
        addIcons(node, p[key]);

      } else if (key == "fillAvalible") {

        if (p[key]) {
          node.setStyle('fillColor', p["fillColor"])

        } else {
          node.setStyle('fillColor', "#FFFFFF00")

        }
        node.setStyle(key, p[key])

      } else if (key == "borderAvalible") {

        if (p[key]) {
          node.setStyle('borderColor', p["borderColor"])

        } else {
          node.setStyle('borderColor', "#FFFFFF00")

        }
        node.setStyle(key, p[key])

      }
      else {
        console.log("getSelfStyle", node.getSelfStyle());

        //修改文字颜色、加粗等
        node.setStyle(key, p[key])
      }
    })

    
  };
`
我打印了一下修改后的getSelfStyle，发现data里面的fontWeight变成**bold**了，但是text里面没有**font-weight: bold**这句
![image](https://github.com/user-attachments/assets/7fe9a8ec-93a1-477d-b248-1f87c476563e)
