### ISSUE TITLE
关于自定义组件切换主题的问题

### ISSUE THREAD

**Issue by xinnai** [wanglin2/mind-map#991]
1、我添加了一个自定义节点，是vue3组件，默认在default主题，当我切换主题之后，这个自定义节点被覆盖为普通的文字节点了，即使再切回原来的默认主题，也还是文字节点? 如何让自定义节点在所有主题下生效，哪怕是样式我自己改，就是让它还保留我vue组件，不被覆盖成文字？

![Snip20241108_5](https://github.com/user-attachments/assets/54997a03-35d6-4882-9ce8-e4c80224be03)
![Snip20241108_6](https://github.com/user-attachments/assets/54c14fea-e0db-4448-a063-b3582c9783d3)
2、另外，如果我在切换主题后，加入一个自定义节点，主题自动换成了default，请问是什么原因呢？

**Comment by wanglin2** [comment]
你这样描述我并看不懂，最好提供代码

**Comment by xinnai** [comment]
`
import SkillNode from "@/components/nodeTemplate/SkillNode.vue" //若干个vue3组件
import DateNode from "@/components/nodeTemplate/DateNode.vue"

const mindMap = new MindMap({
isUseCustomNodeContent: true,
      customCreateNodeContent: (node) => {
        const nodedata = node.nodeData.data;
        if (nodedata.category == 'Slider') {
          const el = document.createElement('div')
          const app = createApp(SkillNode, {// props
            ndata: node.nodeData.data
          })
          app.mount(el)
          return el
        } else if (nodedata.category == 'Date') { // 用category判断加载哪一个组件
          const el = document.createElement('div')
          const app = createApp(DateNode, {// props
            ndata: node.nodeData.data
          })
          app.mount(el)
          return el
        }


        // return你的自定义DOM节点
      },`

  切换的时候用的内置主题插件：
`simpleMindMap.setTheme(mindmapStore.gTheme.value);
  $simpleMindMap.setThemeConfig(mindmapStore.gTheme.theme);`

我发现切换主题之后，把我节点的data数据覆盖了，本来是带有`category`字段的我自己的数据，被覆盖成普通的文字节点数据，category字段也没了

**Comment by xinnai** [comment]
@wanglin2 hello，能否看下我的代码，哪里有问题
