### ISSUE TITLE
先删除再增加节点，结果删除了但是没有增加

### ISSUE THREAD

**Issue by onlyis** [wanglin2/mind-map#993]
<img width="693" alt="image" src="https://github.com/user-attachments/assets/b938c86f-76a7-4d43-8e06-0de1e8f37a16">
看图

**Comment by onlyis** [comment]
这个是操作有问题吗

**Comment by wanglin2** [comment]
![image](https://github.com/user-attachments/assets/651184f7-f27d-40ec-aed0-cd74372814b6)

试了没问题
