### ISSUE TITLE
小地图节点颜色问题

### ISSUE THREAD

**Issue by xinnai** [wanglin2/mind-map#994]
我配置了默认主题颜色，主节点是粉色背景，二级三级都是白色背景，但是小地图二三级都显示的是绿色，如何修改呢？
![Snip20241111_1](https://github.com/user-attachments/assets/b95a7c6d-57cf-421b-9c28-361e82c68742)
![Snip20241111_2](https://github.com/user-attachments/assets/fbbe1f62-45ae-4c1d-8ed8-30b5c3997c0c)

**Comment by wanglin2** [comment]
需要提供更多信息，不然我也不知道怎么复现
